import { expect, test } from "@playwright/test";
import { ambiguousKeyMidi } from "../support/midi-key-ambiguity-fixture";
import { captureDiagnostics, expectCleanDiagnostics, openStudio } from "./u1-chart-kit";

test.use({ userAgent: "OpenAI File Downloader, XaiImageApiFetch/1.0" });
for (const width of [1280, 390]) {
  test(`ambiguous key, explicit choice and undo at ${String(width)}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 });
    const diagnostics = captureDiagnostics(page);
    const requests: string[] = [];
    await page.route(/^https?:/, async (route) => { requests.push(route.request().url()); await route.abort(); });
    await openStudio(page);
    if (width === 390) await page.locator("#studio-open-library-sheet, #studio-transport-open-library").filter({ visible: true }).first().click();
    const input = page.getByTestId("midi-import-file").filter({ visible: true }).first();
    const payload = { name: "Symmetric.mid", mimeType: "audio/midi", buffer: Buffer.from(ambiguousKeyMidi()) };
    await input.setInputFiles(payload);
    await expect(page.getByText("4 tied choices; no key will be applied automatically.", { exact: true }).filter({ visible: true })).toBeVisible();
    await page.getByText("Advanced: chart text, readings, and every sonority", { exact: true }).filter({ visible: true }).click();
    const choice = page.getByTestId("midi-import-key-override").filter({ visible: true });
    await expect(choice).toHaveValue("");
    await expect(choice.locator("option")).toHaveCount(25);
    await expect(page.getByTestId("midi-import-key-ties").filter({ visible: true })).toHaveText("Tied keys: C minor, Eb minor, F# minor, A minor");
    await choice.selectOption("6/major");
    await expect(page.getByText("Key chosen by you", { exact: true }).filter({ visible: true })).toBeVisible();
    const groove = page.getByTestId("midi-import-groove-override").filter({ visible: true });
    await groove.selectOption({ index: 1 });
    const grooveId = await groove.inputValue();
    await expect(choice).toHaveValue("6/major");
    await choice.selectOption("");
    await expect(groove).toHaveValue(grooveId);
    await expect(page.getByText("4 tied choices; no key will be applied automatically.", { exact: true }).filter({ visible: true })).toBeVisible();
    await choice.selectOption("6/major");
    const include = page.getByTestId("midi-import-track-include").filter({ visible: true }).first();
    await include.uncheck();
    await expect(choice).toHaveValue("6/major");
    await include.check();
    await expect(choice).toHaveValue("6/major");
    const trace = page.getByTestId("midi-import-trace").filter({ visible: true });
    await trace.locator("summary").click();
    const traceText = await trace.locator("pre").innerText();
    expect(traceText).toContain('"subject": "tied-key"');
    expect(traceText).toContain('"reason": "user override"');
    await page.getByRole("button", { name: "Add to the chart", exact: true }).filter({ visible: true }).click();
    await expect(page.locator(".studio-chord-card")).toHaveCount(2);
    const notice = await page.getByTestId("midi-import-status").filter({ visible: true }).innerText();
    const undoCount = notice.includes("one edit") ? 1 : Number(/added as (\d+) edits/.exec(notice)?.[1]);
    expect(undoCount).toBeGreaterThan(0);
    expect(undoCount).toBeLessThanOrEqual(8);
    if (width === 390) await page.getByRole("button", { name: /^Close / }).filter({ visible: true }).first().click();
    for (let index = 0; index < undoCount; index++) await page.locator("#studio-undo").press("Enter");
    await expect(page.locator(".studio-chord-card")).toHaveCount(0);
    if (width === 390) await page.locator("#studio-open-library-sheet, #studio-transport-open-library").filter({ visible: true }).first().click();
    await input.setInputFiles([payload, { ...payload, name: "Second.mid" }]);
    await page.getByText("Advanced: chart text, readings, and every sonority", { exact: true }).filter({ visible: true }).click();
    await expect(choice).toHaveValue("");
    await choice.selectOption("6/major");
    await page.getByTestId("midi-import-candidate-1").filter({ visible: true }).click();
    await expect(choice).toHaveValue("");
    await expect(groove).toHaveValue("");
    expect(requests).toEqual([]);
    expectCleanDiagnostics(diagnostics);
    await testInfo.attach("key-ambiguity-evidence", { body: JSON.stringify({ width, traceText, notice, undoCount, requests, diagnostics }), contentType: "application/json" });
  });
}
