import {expect,test,type Page} from "@playwright/test";
import {createHash} from "node:crypto";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {pathToFileURL} from "node:url";
import {decodeDocumentShape} from "../../src/domain";
import {observeNativeSources} from "../support/u5-native-audio";
const artifact=resolve(process.env["JCPE_NOTE_FIRST_ARTIFACT"]??"jazz_chord_progression_editor.html"),url=pathToFileURL(artifact).href;
const hash=createHash("sha256").update(readFileSync(artifact)).digest("hex");
test.use({userAgent:"OpenAI File Downloader, XaiImageApiFetch/1.0",contextOptions:{reducedMotion:"reduce"}});
async function exported(page:Page){
  await page.locator("#studio-export-json").click();
  const pending=page.waitForEvent("download");await page.locator("#studio-lifecycle-download").click();
  const download=await pending;expect(await download.failure()).toBeNull();
  const bytes=readFileSync(await download.path());const json:unknown=JSON.parse(bytes.toString("utf8"));
  const decoded=decodeDocumentShape(json);if(!decoded.ok)throw new Error(JSON.stringify(decoded.errors));
  await expect(page.locator("#studio-lifecycle-export-dialog").getByRole("status")).toContainText("Handed off to your browser.");
  await page.getByRole("button",{name:"Close JSON export",exact:true}).click();return {document:decoded.value,bytes};
}
for(const width of [320,1280])test(`note-first exact audio and Manual bar roundtrip at ${String(width)}px`,async({page,browser},info)=>{
  const errors:string[]=[],requests:{url:string;allowed:boolean}[]=[];
  page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>{if(m.type()==="error")errors.push(m.text());});
  await page.route("**/*",async route=>{const allowed=route.request().isNavigationRequest()&&route.request().url()===url;requests.push({url:route.request().url(),allowed});if(allowed)await route.continue();else await route.abort();});
  try{
    await page.setViewportSize({width,height:900});await page.goto(url);await expect(page.locator(".studio-shell")).toHaveAttribute("data-app-ready","true");
    const before=await exported(page);await observeNativeSources(page);
    await page.locator("#studio-open-command-lane").click();
    const summary=page.getByText("Start from notes",{exact:true});await summary.focus();await page.keyboard.press("Enter");
    const panel=page.getByRole("region",{name:"Note-first entry"});
    await panel.getByLabel("Voicing notes").fill("C#4 F4 G#4");await panel.getByRole("button",{name:"Find chord names",exact:true}).click();
    await expect(panel).toContainText("enharmonic reading");await expect(panel).toContainText("Use this name as a Custom label");
    await panel.getByLabel("Add one full bar to").selectOption({index:1});
    await expect(panel.getByRole("button",{name:"Add bar from notes",exact:true})).toBeDisabled();
    await panel.getByLabel("Voicing notes").fill("A3 C4 E4 G4 A3");await panel.getByRole("button",{name:"Find chord names",exact:true}).click();
    await expect(panel).toContainText("Am7 — exact spelling");await expect(panel).toContainText("C6/A — exact spelling");
    await panel.getByRole("button",{name:/^All [0-9]+ names$/}).click();
    const alternative=panel.locator('input[type="radio"]:not([value="custom"])').last();
    await alternative.check();const selectedName=await alternative.inputValue();
    await panel.getByRole("button",{name:"Fewer names",exact:true}).click();
    await expect(panel.locator('input[type="radio"]:checked')).toBeVisible();
    expect(await panel.locator('input[type="radio"]:checked').inputValue()).toBe(selectedName);
    await panel.getByRole("radio",{name:/C6\/A — exact spelling/}).check();
    await panel.getByRole("button",{name:"Hear exact notes",exact:true}).click();
    await expect.poll(()=>page.evaluate(()=>window.u5NativeSourceCounts?.().started??0)).toBeGreaterThan(0);
    await panel.getByRole("button",{name:"Release notes",exact:true}).click();
    await expect.poll(()=>page.evaluate(()=>window.u5NativeSourceCounts?.().futureAttacks??-1)).toBe(0);
    expect(await panel.evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);
    await panel.getByRole("button",{name:"Add bar from notes",exact:true}).click();await expect(panel).toContainText("Added one bar");
    await page.getByRole("button",{name:"Close the command lane",exact:true}).click();
    const after=await exported(page),first=after.document.sections[0],oldFirst=before.document.sections[0];
    expect(first?.measures.length).toBe((oldFirst?.measures.length??0)+1);
    const inserted=first?.measures.at(-1)?.events[0];expect(inserted?.chord.sourceText).toBe("C6/A");
    if(inserted?.voicing.mode!=="manual")throw new Error("Expected stored Manual voicing");
    expect(inserted.voicing.pitches).toEqual([{step:"A",alter:0,octave:3},{step:"C",alter:0,octave:4},{step:"E",alter:0,octave:4},{step:"G",alter:0,octave:4},{step:"A",alter:0,octave:3}]);
    await page.locator("#studio-undo").click();expect((await exported(page)).document).toEqual(before.document);
    await page.locator("#studio-redo").click();expect((await exported(page)).document).toEqual(after.document);
    await expect(page.locator("#studio-recovery-status")).toContainText("Recovered locally at");
    await page.reload();await expect(page.locator(".studio-shell")).toHaveAttribute("data-app-ready","true");
    expect((await exported(page)).document).toEqual(after.document);
    expect(errors).toEqual([]);expect(requests.every(r=>r.allowed)).toBe(true);
    await info.attach("note-first-portable-document",{body:after.bytes,contentType:"application/json"});
  }finally{await info.attach("note-first-evidence",{body:JSON.stringify({hash,width,browser:browser.version(),errors,requests}),contentType:"application/json"});}
});
