import { expect, test } from "@playwright/test";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
const artifact=resolve(process.env["JCPE_PERFORMED_ARTIFACT"]??"jazz_chord_progression_editor.html");
const url=pathToFileURL(artifact).href;
const artifactHash=createHash("sha256").update(readFileSync(artifact)).digest("hex");
test.use({userAgent:"OpenAI File Downloader, XaiImageApiFetch/1.0",contextOptions:{reducedMotion:"reduce"}});
for(const width of [320,1280])test(`performed section MIDI downloads exact bytes at ${String(width)}px`,async({page,browser},info)=>{
 const errors:string[]=[],requests:{url:string;allowed:boolean}[]=[];
 page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>{if(m.type()==="error")errors.push(m.text());});
 await page.route("**/*",async route=>{const allowed=route.request().isNavigationRequest()&&route.request().url()===url;requests.push({url:route.request().url(),allowed});if(allowed)await route.continue();else await route.abort();});
 try{
  await page.setViewportSize({width,height:900});await page.goto(url);
  await expect(page.locator(".studio-shell")).toHaveAttribute("data-app-ready","true");
  const revision=await page.locator(".studio-document-status__revision").textContent();
  await page.locator("#studio-export-midi").click();
  const summary=page.getByText("Export performed arrangement",{exact:true});await summary.focus();await page.keyboard.press("Enter");
  const panel=page.getByRole("region",{name:"Performed arrangement MIDI"});
  await expect(panel).toBeVisible();
  const select=panel.getByLabel("Passage",{exact:true});
  await select.selectOption({index:1});
  await panel.getByRole("button",{name:"Prepare performed MIDI",exact:true}).click();
  await expect(panel).toContainText("Performed MIDI is ready");
  await panel.getByRole("button",{name:"Cancel preparation",exact:true}).click();
  await expect(panel.getByRole("button",{name:"Download performed MIDI",exact:true})).toBeDisabled();
  await panel.getByRole("button",{name:"Prepare performed MIDI",exact:true}).click();
  await expect(panel).toContainText("Performed MIDI is ready");
  const sha256=await panel.getAttribute("data-artifact-sha256");
  const pending=page.waitForEvent("download");
  await panel.getByRole("button",{name:"Download performed MIDI",exact:true}).click();
  const download=await pending;
  const downloaded=await download.path();
  expect(await download.failure()).toBeNull();
  const bytes=readFileSync(downloaded);expect([...bytes.subarray(0,14)]).toEqual([77,84,104,100,0,0,0,6,0,1,0,3,3,192]);
  expect(createHash("sha256").update(bytes).digest("hex")).toBe(sha256);
  expect(download.suggestedFilename()).toMatch(/^changes-performed-.*\.mid$/);
  await expect(panel).toContainText("handed to browser downloads");
  expect(await panel.evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);
  expect(await page.locator(".studio-document-status__revision").textContent()).toBe(revision);
  expect(errors).toEqual([]);expect(requests.every(r=>r.allowed)).toBe(true);
  await info.attach("performed-midi-file",{body:bytes,contentType:"audio/midi"});
 }finally{await info.attach("performed-midi-evidence",{body:JSON.stringify({artifactHash,browser:browser.version(),width,errors,requests}),contentType:"application/json"});}
});
