import { describe, expect, test } from "bun:test";

import { decodeDocumentShape, type ValidatedDocument } from "../../src/domain";
import {
  MAX_APPLICATION_REVISION,
  MAX_APPLICATION_SEQUENCE,
  MAX_HISTORY_RETAINED_BYTES,
  createStudioBootstrap,
  createStudioCompositionOverState,
  validateDocumentSemantics,
  type AppState,
  type ApplicationCommandDependencies,
  type PendingApplicationRequest,
  type StudioComposition,
  type StudioInterchangeOwnerDiagnostic,
} from "../../src/application";
import type {
  ImportNonUndoableConfirmationAcknowledgement,
  ImportReplacementHandoff,
  ImportReplacementPreparationRefusalCode,
  PrepareImportReplacementPublicationRequest,
  PreparedImportReplacementPublication,
  PublishCanonicalExportRevisionRequest,
} from "../../src/application/application-interchange-owner-contract";

/**
 * Production-boundary proof for the A0/E0 interchange owner ports
 * (docs/A0_E0_OWNER_PORTS_CONTRACT.md, bead jcpe-94yu.2): the five
 * controller-owned operations exercised against the real studio composition.
 * Every fixture below is authored by hand in this file; no expectation is
 * generated by the code under test.
 */

const REQUEST_ID = 101;
const STUB_ESTIMATE = 4_321;
const OVERSIZED_ESTIMATE = MAX_HISTORY_RETAINED_BYTES + 1;
const MARKER_SCHEMA = "changes.canonical-export-revision-publication.v1";

/** Independently authored zero-section candidate; F2/F3 publish it. */
const CANDIDATE_RAW = Object.freeze({
  schema: "changes.progression.v2",
  id: "owner-test-candidate",
  title: "Owner Bridge Candidate",
  description: "",
  meter: Object.freeze({ beatsPerBar: 4, beatUnit: 4 }),
  tempoBpm: 120,
  key: null,
  sections: Object.freeze([]),
  playback: Object.freeze({
    instrumentId: "mellow-keys",
    masterVolume: 0.8,
    reverbAmount: 0.2,
    countInBars: 0,
  }),
});

/** Structurally valid, semantically refused: a complete measure with no events. */
const SEMANTIC_INVALID_RAW = Object.freeze({
  ...CANDIDATE_RAW,
  sections: Object.freeze([
    Object.freeze({
      id: "owner-bad-section",
      name: "A",
      annotation: "",
      keyOverride: null,
      voiceLeadingBoundary: "reset",
      measures: Object.freeze([
        Object.freeze({
          id: "owner-bad-measure",
          events: Object.freeze([]),
          completion: Object.freeze({ kind: "complete" }),
        }),
      ]),
    }),
  ]),
});

function publishCandidate(raw: unknown): ValidatedDocument {
  const decoded = decodeDocumentShape(raw);
  if (!decoded.ok) throw new Error("OWNER_TEST_CANDIDATE_STRUCTURAL");
  const validated = validateDocumentSemantics(decoded.value);
  if (!validated.ok) throw new Error("OWNER_TEST_CANDIDATE_SEMANTIC");
  return validated.value;
}

type HarnessOptions = Readonly<{
  disposition?: "retained" | "explicitly-unavailable";
  estimate?: number;
  /**
   * The estimate the DISCLOSED impact was computed from, when it must stay
   * well-formed while the injected estimator misbehaves (REP-020 family).
   */
  disclosedEstimate?: number;
  transportGeneration?: number;
  nextSequence?: number;
  revision?: number;
  /** Skip the pending request + retiring transition (idle workflow). */
  idleTransition?: boolean;
}>;

type Harness = Readonly<{
  composition: StudioComposition;
  state: AppState;
  dependencies: ApplicationCommandDependencies;
  candidate: ValidatedDocument;
  request: PrepareImportReplacementPublicationRequest;
  acknowledgement: ImportNonUndoableConfirmationAcknowledgement | null;
  notifications: () => number;
  diagnostics: readonly StudioInterchangeOwnerDiagnostic[];
}>;

function createHarness(options: HarnessOptions = {}): Harness {
  const bootstrap = createStudioBootstrap();
  expect(bootstrap.ok).toBe(true);
  if (!bootstrap.ok) throw new Error("OWNER_TEST_BOOTSTRAP");
  const disposition = options.disposition ?? "retained";
  const estimate =
    options.estimate ??
    (disposition === "retained" ? STUB_ESTIMATE : OVERSIZED_ESTIMATE);
  const dependencies: ApplicationCommandDependencies = Object.freeze({
    ...bootstrap.value.dependencies,
    estimateHistoryRetainedBytes: () => estimate,
  });
  const candidate = publishCandidate(CANDIDATE_RAW);
  const revision = options.revision ?? bootstrap.value.state.revision;
  const base = bootstrap.value.state;
  const pending: PendingApplicationRequest = Object.freeze({
    kind: "document-transition",
    id: REQUEST_ID,
    documentId: base.document.id,
    baseRevision: revision,
    status: "running",
  });
  const transition = Object.freeze({
    kind: "retiring-transport",
    requestId: REQUEST_ID,
    origin: "canonical-import",
    baseRevision: revision,
    candidateDocumentId: candidate.id,
    undoDisposition: disposition,
  } as const);
  const state: AppState = Object.freeze({
    ...base,
    revision,
    ...(options.idleTransition === true
      ? {}
      : {
          pendingRequests: Object.freeze([pending]),
          documentTransition: transition,
        }),
    ...(options.transportGeneration === undefined
      ? {}
      : {
          transport: Object.freeze({
            ...base.transport,
            generation: options.transportGeneration,
          }),
        }),
    ...(options.nextSequence === undefined
      ? {}
      : { nextSequence: options.nextSequence }),
  });
  const diagnostics: StudioInterchangeOwnerDiagnostic[] = [];
  const composition = createStudioCompositionOverState(state, dependencies, {
    interchangeDiagnostics: (diagnostic) => diagnostics.push(diagnostic),
  });
  let notificationCount = 0;
  composition.controller.subscribe(() => {
    notificationCount += 1;
  });
  const disclosedEstimate = options.disclosedEstimate ?? estimate;
  const retainedImpact = Object.freeze({
    historyEntryRetainedBytes: disclosedEstimate,
    evictedUndoEntries: 0,
    redoEntriesCleared: 0,
    confirmationRequired: true,
    undoDisposition: "retained",
    undoEntriesAfterCommit: 1,
    undoRetainedBytesAfterCommit: disclosedEstimate,
    exportRecommended: false,
  } as const);
  const unavailableImpact = Object.freeze({
    historyEntryRetainedBytes: disclosedEstimate,
    evictedUndoEntries: 0,
    redoEntriesCleared: 0,
    confirmationRequired: true,
    undoDisposition: "explicitly-unavailable",
    undoEntriesAfterCommit: 0,
    undoRetainedBytesAfterCommit: 0,
    exportRecommended: true,
  } as const);
  const seed = Object.freeze({
    id: "owner-test-replace-1",
    label: "Import owner bridge candidate",
    logicalTimeMs: 5_000,
  });
  const identity = Object.freeze({
    requestId: REQUEST_ID,
    documentId: base.document.id,
    baseRevision: revision,
  });
  const acknowledgement: ImportNonUndoableConfirmationAcknowledgement | null =
    disposition === "explicitly-unavailable"
      ? Object.freeze({
          kind: "acknowledged",
          requirement: Object.freeze({
            schema: "changes.import-nonundoable-confirmation.v1",
            confirmationId: "owner-test-confirm-1",
            identity,
            candidateDocumentId: candidate.id,
            commandId: seed.id,
            disclosedImpact: unavailableImpact,
          }),
        } as const)
      : null;
  const request: PrepareImportReplacementPublicationRequest =
    disposition === "retained"
      ? Object.freeze({
          identity,
          sourceFormat: "canonical-json-v2",
          replacementOrigin: "canonical-import",
          candidate,
          replacementCommandSeed: seed,
          disclosedImpact: retainedImpact,
          currentTransition: transition as typeof transition & {
            undoDisposition: "retained";
          },
          nonUndoableConfirmation: null,
        } as const)
      : Object.freeze({
          identity,
          sourceFormat: "canonical-json-v2",
          replacementOrigin: "canonical-import",
          candidate,
          replacementCommandSeed: seed,
          disclosedImpact: unavailableImpact,
          currentTransition: transition as typeof transition & {
            undoDisposition: "explicitly-unavailable";
          },
          nonUndoableConfirmation:
            acknowledgement as ImportNonUndoableConfirmationAcknowledgement,
        } as const);
  return Object.freeze({
    composition,
    state,
    dependencies,
    candidate,
    request,
    acknowledgement,
    notifications: () => notificationCount,
    diagnostics,
  });
}

function preparedEcho(
  harness: Harness,
  request?: PrepareImportReplacementPublicationRequest,
): PreparedImportReplacementPublication {
  const result =
    harness.composition.interchangeOwner.prepareImportReplacementPublication(
      request ?? harness.request,
    );
  expect(result.ok).toBe(true);
  if (!result.ok) throw new Error("OWNER_TEST_PREPARE");
  return result.value;
}

function handoffFor(
  echo: PreparedImportReplacementPublication,
  retirement?: Partial<ImportReplacementHandoff["retirement"]>,
): ImportReplacementHandoff {
  return Object.freeze({
    prepared: echo,
    retirement: Object.freeze({
      requestId: REQUEST_ID,
      retiredTransportGeneration: 0,
      progressionRetired: true,
      previewRetired: true,
      noFutureAttack: true,
      ...retirement,
    } as const),
  });
}

function markerRequest(
  documentId: string,
  revision: number,
  schema: string = MARKER_SCHEMA,
): PublishCanonicalExportRevisionRequest {
  return Object.freeze({
    publication: Object.freeze({ schema, documentId, revision }),
  }) as PublishCanonicalExportRevisionRequest;
}

/** Recursively assert no state-bearing key crosses the owner boundary. */
function assertStateFree(value: unknown, path = "result"): void {
  if (typeof value !== "object" || value === null) return;
  if (Array.isArray(value)) {
    value.forEach((entry, index) => {
      assertStateFree(entry, `${path}[${String(index)}]`);
    });
    return;
  }
  for (const [key, child] of Object.entries(value)) {
    expect([
      "state",
      "currentState",
      "lastKnownState",
      "observedBefore",
    ]).not.toContain(key);
    assertStateFree(child, `${path}.${key}`);
  }
}

describe("A0/E0 owner ports: prepareImportReplacementPublication", () => {
  test("retained preparation returns the exact echo, installs nothing, and notifies nobody", () => {
    const harness = createHarness();
    const before = harness.composition.controller.getSnapshot();
    const result =
      harness.composition.interchangeOwner.prepareImportReplacementPublication(
        harness.request,
      );
    expect(result).toEqual({
      ok: true,
      value: {
        schema: "changes.prepared-import-replacement-publication.v1",
        identity: {
          requestId: REQUEST_ID,
          documentId: harness.state.document.id,
          baseRevision: 0,
        },
        sourceFormat: "canonical-json-v2",
        candidateDocumentId: harness.candidate.id,
        expectedTransportGeneration: 0,
        committingTransition: {
          kind: "committing",
          requestId: REQUEST_ID,
          origin: "canonical-import",
          baseRevision: 0,
          candidateDocumentId: harness.candidate.id,
          undoDisposition: "retained",
        },
      },
    });
    assertStateFree(result);
    expect(harness.composition.controller.getSnapshot()).toBe(before);
    expect(harness.notifications()).toBe(0);
    expect(
      harness.diagnostics.map((diagnostic) => diagnostic.event),
    ).toEqual([
      "call.prepare",
      "read.controller-state",
      "validate.request-envelope",
      "compare.complete-identity",
      "compare.transition-binding",
      "validate.command-metadata",
      "check.revision-and-sequence-capacity",
      "call.f2",
      "call.f3",
      "repair.bookmarks-and-focus",
      "estimate.history",
      "recompute.impact",
      "compare.confirmation",
      "inspect.registry-capacity-one",
      "allocate.registry-entry",
      "return.prepared",
    ]);
  });

  test("chart text routes to the canonical origin as a positive pairing", () => {
    const harness = createHarness();
    const request: PrepareImportReplacementPublicationRequest = Object.freeze({
      ...harness.request,
      sourceFormat: "chart-text-v1",
      replacementOrigin: "canonical-import",
    } as const);
    const echo = preparedEcho(harness, request);
    expect(echo.sourceFormat).toBe("chart-text-v1");
    expect(echo.committingTransition.origin).toBe("canonical-import");
  });

  test("the registry is capacity one: a second preparation refuses busy", () => {
    const harness = createHarness();
    preparedEcho(harness);
    const second =
      harness.composition.interchangeOwner.prepareImportReplacementPublication(
        harness.request,
      );
    expect(second).toEqual({
      ok: false,
      code: "import.replacement_preparation_busy",
    });
  });

  test("a refused preparation allocates nothing: the next valid preparation succeeds", () => {
    const harness = createHarness();
    const refused =
      harness.composition.interchangeOwner.prepareImportReplacementPublication(
        Object.freeze({
          ...harness.request,
          replacementCommandSeed: Object.freeze({
            id: "",
            label: "Import owner bridge candidate",
            logicalTimeMs: 5_000,
          }),
        }),
      );
    expect(refused).toEqual({
      ok: false,
      code: "import.replacement_command_id_invalid",
    });
    // The early-allocation mutant dies here: an allocated refusal would
    // make this second call refuse import.replacement_preparation_busy.
    expect(preparedEcho(harness).schema).toBe(
      "changes.prepared-import-replacement-publication.v1",
    );
  });

  test("identity and transition near misses refuse with their exact codes", () => {
    const cases: readonly Readonly<{
      mutate: (
        request: PrepareImportReplacementPublicationRequest,
      ) => PrepareImportReplacementPublicationRequest;
      code: ImportReplacementPreparationRefusalCode;
    }>[] = [
      {
        mutate: (request) =>
          Object.freeze({
            ...request,
            identity: Object.freeze({
              ...request.identity,
              documentId: "someone-else",
            }),
          }) as PrepareImportReplacementPublicationRequest,
        code: "import.replacement_wrong_document",
      },
      {
        mutate: (request) =>
          Object.freeze({
            ...request,
            identity: Object.freeze({
              ...request.identity,
              baseRevision: 1,
            }),
          }),
        code: "import.replacement_request_stale",
      },
      {
        mutate: (request) =>
          Object.freeze({
            ...request,
            identity: Object.freeze({
              ...request.identity,
              requestId: REQUEST_ID + 1,
            }),
          }),
        code: "import.replacement_request_stale",
      },
      {
        mutate: (request) =>
          Object.freeze({
            ...request,
            currentTransition: Object.freeze({
              ...request.currentTransition,
              candidateDocumentId: "someone-else",
            }),
          }) as unknown as PrepareImportReplacementPublicationRequest,
        code: "import.replacement_transition_mismatch",
      },
      {
        mutate: (request) =>
          Object.freeze({
            ...request,
            currentTransition: Object.freeze({
              ...request.currentTransition,
              requestId: REQUEST_ID + 1,
            }),
          }) as unknown as PrepareImportReplacementPublicationRequest,
        code: "import.replacement_transition_mismatch",
      },
      {
        // The disposition axis is an impact disagreement by contract.
        mutate: (request) =>
          Object.freeze({
            ...request,
            currentTransition: Object.freeze({
              ...request.currentTransition,
              undoDisposition: "explicitly-unavailable",
            }),
          }) as unknown as PrepareImportReplacementPublicationRequest,
        code: "import.replacement_impact_mismatch",
      },
      {
        mutate: (request) =>
          Object.freeze({
            ...request,
            smuggled: true,
          }),
        code: "import.replacement_request_invalid",
      },
      {
        mutate: (request) =>
          Object.freeze({
            ...request,
            identity: Object.freeze({ ...request.identity, extra: 1 }),
          }),
        code: "import.replacement_request_invalid",
      },
      {
        mutate: (request) =>
          Object.freeze({
            ...request,
            replacementOrigin: "legacy-import",
          }) as unknown as PrepareImportReplacementPublicationRequest,
        code: "import.replacement_request_invalid",
      },
    ];
    for (const { mutate, code } of cases) {
      const harness = createHarness();
      const result =
        harness.composition.interchangeOwner.prepareImportReplacementPublication(
          mutate(harness.request),
        );
      expect(result).toEqual({ ok: false, code });
      expect(harness.notifications()).toBe(0);
    }
  });

  test("command metadata refusals use the bounded-token and logical-time laws", () => {
    const seedCases: readonly Readonly<{
      seed: Readonly<{ id: string; label: string; logicalTimeMs: number }>;
      code: ImportReplacementPreparationRefusalCode;
    }>[] = [
      {
        seed: { id: "", label: "Import", logicalTimeMs: 5_000 },
        code: "import.replacement_command_id_invalid",
      },
      {
        seed: { id: "x".repeat(129), label: "Import", logicalTimeMs: 5_000 },
        code: "import.replacement_command_id_invalid",
      },
      {
        seed: { id: "ok", label: "y".repeat(161), logicalTimeMs: 5_000 },
        code: "import.replacement_command_label_invalid",
      },
      {
        seed: { id: "ok", label: "Import", logicalTimeMs: -1 },
        code: "import.replacement_logical_time_invalid",
      },
      {
        seed: { id: "ok", label: "Import", logicalTimeMs: 1.5 },
        code: "import.replacement_logical_time_invalid",
      },
    ];
    for (const { seed, code } of seedCases) {
      const harness = createHarness();
      const result =
        harness.composition.interchangeOwner.prepareImportReplacementPublication(
          Object.freeze({
            ...harness.request,
            replacementCommandSeed: Object.freeze(seed),
          }),
        );
      expect(result).toEqual({ ok: false, code });
    }
  });

  test("revision and sequence exhaustion refuse before any candidate work", () => {
    const revisionHarness = createHarness({
      revision: MAX_APPLICATION_REVISION,
    });
    expect(
      revisionHarness.composition.interchangeOwner.prepareImportReplacementPublication(
        revisionHarness.request,
      ),
    ).toEqual({ ok: false, code: "application.revision_exhausted" });
    expect(
      revisionHarness.diagnostics.map((diagnostic) => diagnostic.event),
    ).not.toContain("call.f2");

    const sequenceHarness = createHarness({
      nextSequence: MAX_APPLICATION_SEQUENCE,
    });
    expect(
      sequenceHarness.composition.interchangeOwner.prepareImportReplacementPublication(
        sequenceHarness.request,
      ),
    ).toEqual({ ok: false, code: "application.sequence_exhausted" });
  });

  test("candidate refusals map F2 and F3 to the owner vocabulary", () => {
    const structural = createHarness();
    expect(
      structural.composition.interchangeOwner.prepareImportReplacementPublication(
        Object.freeze({
          ...structural.request,
          candidate: Object.freeze({
            ...CANDIDATE_RAW,
            sections: "not-an-array",
          }) as unknown as ValidatedDocument,
        }) as PrepareImportReplacementPublicationRequest,
      ),
    ).toEqual({ ok: false, code: "import.candidate_structural_invalid" });

    const semantic = createHarness();
    expect(
      semantic.composition.interchangeOwner.prepareImportReplacementPublication(
        Object.freeze({
          ...semantic.request,
          candidate: SEMANTIC_INVALID_RAW as unknown as ValidatedDocument,
          currentTransition: semantic.request.currentTransition,
        }) as PrepareImportReplacementPublicationRequest,
      ),
    ).toEqual({ ok: false, code: "import.candidate_semantic_invalid" });
  });

  test("estimator and impact refusals separate failed, unavailable, and mismatched", () => {
    const failed = createHarness({
      estimate: -1,
      disclosedEstimate: STUB_ESTIMATE,
    });
    expect(
      failed.composition.interchangeOwner.prepareImportReplacementPublication(
        failed.request,
      ),
    ).toEqual({
      ok: false,
      code: "import.replacement_history_estimate_failed",
    });

    const nan = createHarness({
      estimate: Number.NaN,
      disclosedEstimate: STUB_ESTIMATE,
    });
    expect(
      nan.composition.interchangeOwner.prepareImportReplacementPublication(
        nan.request,
      ),
    ).toEqual({
      ok: false,
      code: "import.replacement_history_estimate_failed",
    });

    // Retained disclosure while retention is impossible: unavailable.
    const oversizedRetained = createHarness();
    const oversizedRequest = Object.freeze({
      ...oversizedRetained.request,
    }) as PrepareImportReplacementPublicationRequest;
    const oversizedHarness = createHarness({
      disposition: "retained",
      estimate: OVERSIZED_ESTIMATE,
    });
    // The harness recomputes disclosed impact from its own estimate, so
    // rebuild the disclosure with the small-estimate numbers to disagree.
    const disagreeing = Object.freeze({
      ...oversizedHarness.request,
      disclosedImpact: oversizedRequest.disclosedImpact,
    }) as PrepareImportReplacementPublicationRequest;
    expect(
      oversizedHarness.composition.interchangeOwner.prepareImportReplacementPublication(
        disagreeing,
      ),
    ).toEqual({ ok: false, code: "import.replacement_impact_unavailable" });

    // A one-number drift in the retained disclosure: mismatch.
    const mismatch = createHarness();
    expect(
      mismatch.composition.interchangeOwner.prepareImportReplacementPublication(
        Object.freeze({
          ...mismatch.request,
          disclosedImpact: Object.freeze({
            ...mismatch.request.disclosedImpact,
            historyEntryRetainedBytes: STUB_ESTIMATE + 1,
            undoRetainedBytesAfterCommit: STUB_ESTIMATE + 1,
          }),
        }) as PrepareImportReplacementPublicationRequest,
      ),
    ).toEqual({ ok: false, code: "import.replacement_impact_mismatch" });
  });

  test("an idle workflow has no live transition and refuses stale", () => {
    const harness = createHarness({ idleTransition: true });
    expect(
      harness.composition.interchangeOwner.prepareImportReplacementPublication(
        harness.request,
      ),
    ).toEqual({ ok: false, code: "import.replacement_request_stale" });
  });
});

describe("A0/E0 owner ports: non-undoable confirmation", () => {
  test("a matching acknowledgement prepares the explicitly-unavailable variant", () => {
    const harness = createHarness({ disposition: "explicitly-unavailable" });
    const echo = preparedEcho(harness);
    expect(echo.committingTransition.undoDisposition).toBe(
      "explicitly-unavailable",
    );
  });

  test("confirmation near misses refuse with their exact codes", () => {
    const mutations: readonly Readonly<{
      patch: (
        acknowledgement: ImportNonUndoableConfirmationAcknowledgement,
      ) => unknown;
      code: ImportReplacementPreparationRefusalCode;
    }>[] = [
      { patch: () => null, code: "history.nonundoable_confirmation_required" },
      {
        patch: (acknowledgement) => ({
          ...acknowledgement,
          requirement: {
            ...acknowledgement.requirement,
            commandId: "someone-elses-command",
          },
        }),
        code: "import.confirmation_identity_mismatch",
      },
      {
        patch: (acknowledgement) => ({
          ...acknowledgement,
          requirement: {
            ...acknowledgement.requirement,
            identity: {
              ...acknowledgement.requirement.identity,
              documentId: "someone-else",
            },
          },
        }),
        code: "import.confirmation_wrong_document",
      },
      {
        patch: (acknowledgement) => ({
          ...acknowledgement,
          requirement: {
            ...acknowledgement.requirement,
            identity: {
              ...acknowledgement.requirement.identity,
              baseRevision: 6,
            },
          },
        }),
        code: "import.confirmation_stale",
      },
      {
        patch: (acknowledgement) => ({
          ...acknowledgement,
          requirement: {
            ...acknowledgement.requirement,
            disclosedImpact: {
              ...acknowledgement.requirement.disclosedImpact,
              historyEntryRetainedBytes: OVERSIZED_ESTIMATE - 1,
            },
          },
        }),
        code: "import.confirmation_impact_mismatch",
      },
      {
        patch: (acknowledgement) => ({
          ...acknowledgement,
          requirement: {
            ...acknowledgement.requirement,
            confirmationId: "c".repeat(129),
          },
        }),
        code: "import.confirmation_identity_mismatch",
      },
      {
        patch: (acknowledgement) => ({
          ...acknowledgement,
          requirement: {
            ...acknowledgement.requirement,
            confirmationId: "   ",
          },
        }),
        code: "import.confirmation_identity_mismatch",
      },
      {
        patch: (acknowledgement) => ({
          ...acknowledgement,
          smuggled: true,
        }),
        code: "import.confirmation_identity_mismatch",
      },
    ];
    for (const { patch, code } of mutations) {
      const harness = createHarness({ disposition: "explicitly-unavailable" });
      const acknowledgement = harness.acknowledgement;
      if (acknowledgement === null) throw new Error("OWNER_TEST_ACK");
      const result =
        harness.composition.interchangeOwner.prepareImportReplacementPublication(
          Object.freeze({
            ...harness.request,
            nonUndoableConfirmation: patch(acknowledgement),
          }) as PrepareImportReplacementPublicationRequest,
        );
      expect(result).toEqual({ ok: false, code });
    }
  });

  test("a retained request carrying an acknowledgement is malformed presence", () => {
    const retained = createHarness();
    const unavailable = createHarness({
      disposition: "explicitly-unavailable",
    });
    const result =
      retained.composition.interchangeOwner.prepareImportReplacementPublication(
        Object.freeze({
          ...retained.request,
          nonUndoableConfirmation: unavailable.acknowledgement,
        }) as PrepareImportReplacementPublicationRequest,
      );
    expect(result).toEqual({
      ok: false,
      code: "import.confirmation_identity_mismatch",
    });
  });
});

describe("A0/E0 owner ports: discardImportReplacementPublication", () => {
  test("each closed reason is total and idempotent, and reports live zero", () => {
    for (const reason of [
      "preparation-protocol-invalid",
      "retirement-refused",
      "retirement-protocol-invalid",
      "publication-protocol-invalid",
    ] as const) {
      const harness = createHarness();
      const echo = preparedEcho(harness);
      const request = Object.freeze({ identity: echo.identity, reason });
      const expected = {
        outcome: "invalidated-by-request",
        identity: {
          requestId: REQUEST_ID,
          documentId: harness.state.document.id,
          baseRevision: 0,
        },
        liveForRequest: 0,
      } as const;
      expect(
        harness.composition.interchangeOwner.discardImportReplacementPublication(
          request,
        ),
      ).toEqual(expected);
      expect(
        harness.composition.interchangeOwner.discardImportReplacementPublication(
          request,
        ),
      ).toEqual(expected);
      // The discarded entry can never publish again.
      expect(
        harness.composition.interchangeOwner.publishImportReplacement(
          handoffFor(echo),
        ),
      ).toMatchObject({
        ok: false,
        code: "import.replacement_preparation_missing",
      });
      expect(harness.notifications()).toBe(0);
    }
  });

  test("a wrong-identity discard preserves the live entry", () => {
    const harness = createHarness();
    const echo = preparedEcho(harness);
    const wrong =
      harness.composition.interchangeOwner.discardImportReplacementPublication(
        Object.freeze({
          identity: Object.freeze({
            requestId: REQUEST_ID + 1,
            documentId: harness.state.document.id,
            baseRevision: 0,
          }),
          reason: "retirement-refused",
        }),
      );
    expect(wrong).toEqual({
      outcome: "invalidated-by-request",
      identity: {
        requestId: REQUEST_ID + 1,
        documentId: harness.state.document.id,
        baseRevision: 0,
      },
      liveForRequest: 0,
    });
    // The matching entry survived the wrong-identity discard and publishes.
    const published =
      harness.composition.interchangeOwner.publishImportReplacement(
        handoffFor(echo),
      );
    expect(published).toMatchObject({ ok: true, outcome: "committed" });
  });
});

describe("A0/E0 owner ports: publishImportReplacement", () => {
  test("a retained publication merges into the latest state and preserves session surfaces", () => {
    const harness = createHarness();
    const echo = preparedEcho(harness);
    // Same-revision session churn between prepare and publish: a collapsed
    // rail changes `panels`, which the merge preserves from the LATEST state
    // and the staleness recheck deliberately ignores.
    const railResult = harness.composition.controller.setRailCollapsed(
      "left",
      true,
    );
    expect(railResult.ok).toBe(true);
    // Same-value bookmark churn is not drift: deep equality governs.
    expect(harness.composition.controller.clearSelection().ok).toBe(true);
    const notificationsBeforePublish = harness.notifications();
    const result =
      harness.composition.interchangeOwner.publishImportReplacement(
        handoffFor(echo),
      );
    expect(result).toEqual({
      ok: true,
      outcome: "committed",
      identity: {
        requestId: REQUEST_ID,
        documentId: harness.state.document.id,
        baseRevision: 0,
      },
      documentId: harness.candidate.id,
      revision: 1,
      effects: [
        {
          kind: "queue-recovery",
          revision: 1,
          requestId: null,
          reasonCode: "command:replace-document",
        },
        {
          kind: "compile-playback-plan",
          revision: 1,
          requestId: null,
          reasonCode: "command:replace-document",
        },
        {
          kind: "restore-focus",
          revision: 1,
          requestId: null,
          reasonCode: "command:replace-document",
        },
        {
          kind: "announce",
          revision: 1,
          requestId: null,
          reasonCode: "command:replace-document",
        },
      ],
      counters: {
        sectionsVisited: 1,
        measuresVisited: 1,
        eventsVisited: 0,
        stableIdsIndexed: 2,
        historyEntriesVisited: 0,
        historyBytesEstimated: STUB_ESTIMATE,
        bookmarksRepaired: 0,
        requestsCompared: 0,
        transportNotificationsCompared: 0,
        validationCalls: 1,
      },
      liveForRequest: 0,
    });
    assertStateFree(result);
    expect(harness.notifications()).toBe(notificationsBeforePublish + 1);
    const view = harness.composition.controller.getSnapshot();
    expect(view.title).toBe("Owner Bridge Candidate");
    expect(view.revision).toBe(1);
    expect(view.panels.leftRailCollapsed).toBe(true);
    // The controller's own history machinery still works over the merge:
    // a retained replacement is undoable and restores the previous chart.
    const undone = harness.composition.controller.undo();
    expect(undone.ok).toBe(true);
    expect(harness.composition.controller.getSnapshot().title).toBe(
      "Untitled Chart",
    );
  });

  test("the latest identity reader sees the publication immediately", () => {
    const harness = createHarness();
    const owner = harness.composition.interchangeOwner;
    expect(owner.readCurrentApplicationDocumentIdentity()).toEqual({
      documentId: harness.state.document.id,
      revision: 0,
    });
    const echo = preparedEcho(harness);
    owner.publishImportReplacement(handoffFor(echo));
    expect(owner.readCurrentApplicationDocumentIdentity()).toEqual({
      documentId: harness.candidate.id,
      revision: 1,
    });
  });

  test("publish consumes before returning: an exact replay refuses missing", () => {
    const harness = createHarness();
    const echo = preparedEcho(harness);
    const first = harness.composition.interchangeOwner.publishImportReplacement(
      handoffFor(echo),
    );
    expect(first).toMatchObject({ ok: true, liveForRequest: 0 });
    const replay =
      harness.composition.interchangeOwner.publishImportReplacement(
        handoffFor(echo),
      );
    expect(replay).toMatchObject({
      ok: false,
      code: "import.replacement_preparation_missing",
      liveForRequest: 0,
    });
  });

  test("a structural lookalike is never authority and consumes the live entry", () => {
    const harness = createHarness();
    const echo = preparedEcho(harness);
    const lookalike = structuredClone(echo);
    expect(lookalike).toEqual(echo);
    const refused =
      harness.composition.interchangeOwner.publishImportReplacement(
        handoffFor(lookalike),
      );
    expect(refused).toMatchObject({
      ok: false,
      code: "import.replacement_preparation_missing",
    });
    // The lookalike consumed the matching live entry; the exact echo can
    // no longer publish either.
    expect(
      harness.composition.interchangeOwner.publishImportReplacement(
        handoffFor(echo),
      ),
    ).toMatchObject({
      ok: false,
      code: "import.replacement_preparation_missing",
    });
    expect(harness.notifications()).toBe(0);
  });

  test("same-revision bookmark drift consumes and refuses stale", () => {
    const harness = createHarness();
    const echo = preparedEcho(harness);
    expect(
      harness.composition.controller.setInsertionPoint({
        kind: "document-end",
      }).ok,
    ).toBe(true);
    const refused =
      harness.composition.interchangeOwner.publishImportReplacement(
        handoffFor(echo),
      );
    expect(refused).toMatchObject({
      ok: false,
      code: "import.replacement_preparation_stale",
      observedDocumentId: harness.state.document.id,
      observedRevision: 0,
      liveForRequest: 0,
    });
    // Consumed: a repeat is missing, not stale.
    expect(
      harness.composition.interchangeOwner.publishImportReplacement(
        handoffFor(echo),
      ),
    ).toMatchObject({
      ok: false,
      code: "import.replacement_preparation_missing",
    });
  });

  test("retirement evidence is checked exactly and covers the latest generation", () => {
    const receipts: readonly Readonly<{
      retirement: Partial<ImportReplacementHandoff["retirement"]>;
      generation?: number;
    }>[] = [
      { retirement: { requestId: REQUEST_ID + 1 } },
      { retirement: { noFutureAttack: false as never } },
      { retirement: { retiredTransportGeneration: -1 } },
      { retirement: { retiredTransportGeneration: 4 }, generation: 5 },
    ];
    for (const { retirement, generation } of receipts) {
      const harness = createHarness(
        generation === undefined ? {} : { transportGeneration: generation },
      );
      const echo = preparedEcho(harness);
      const refused =
        harness.composition.interchangeOwner.publishImportReplacement(
          handoffFor(echo, retirement),
        );
      expect(refused).toMatchObject({
        ok: false,
        code: "import.replacement_retirement_mismatch",
        liveForRequest: 0,
      });
    }
    // The exact covering generation publishes.
    const covered = createHarness({ transportGeneration: 5 });
    const echo = preparedEcho(covered);
    expect(
      covered.composition.interchangeOwner.publishImportReplacement(
        handoffFor(echo, { retiredTransportGeneration: 5 }),
      ),
    ).toMatchObject({ ok: true, outcome: "committed" });
  });

  test("an explicitly-unavailable publication resets history and warns once", () => {
    const harness = createHarness({ disposition: "explicitly-unavailable" });
    const echo = preparedEcho(harness);
    const result =
      harness.composition.interchangeOwner.publishImportReplacement(
        handoffFor(echo),
      );
    expect(result).toMatchObject({ ok: true, outcome: "committed" });
    if (!result.ok) throw new Error("OWNER_TEST_PUBLISH");
    expect(result.effects.map((effect) => effect.kind)).toEqual([
      "queue-recovery",
      "compile-playback-plan",
      "restore-focus",
      "announce",
      "recommend-export",
    ]);
    expect(result.effects[4]).toMatchObject({ requestId: REQUEST_ID });
    const view = harness.composition.controller.getSnapshot();
    expect(view.noticeCount).toBe(1);
    expect(view.latestNotice).toMatchObject({
      code: "history.replacement_not_undoable",
    });
    // History was explicitly made unavailable: undo refuses empty.
    expect(harness.composition.controller.undo()).toMatchObject({
      ok: false,
      refusal: { code: "history.undo_empty" },
    });
  });
});

describe("A0/E0 owner ports: readCurrentApplicationDocumentIdentity", () => {
  test("reads the controller closure at call time and returns a frozen locator", () => {
    const harness = createHarness({ idleTransition: true });
    const owner = harness.composition.interchangeOwner;
    const identity = owner.readCurrentApplicationDocumentIdentity();
    expect(identity).toEqual({
      documentId: harness.state.document.id,
      revision: 0,
    });
    expect(Object.isFrozen(identity)).toBe(true);
    // A document command is visible to the very next read.
    expect(harness.composition.controller.setTitle("Renamed").ok).toBe(true);
    expect(owner.readCurrentApplicationDocumentIdentity()).toEqual({
      documentId: harness.state.document.id,
      revision: 1,
    });
    // Ephemeral-only churn leaves the identity unchanged.
    expect(
      harness.composition.controller.setRailCollapsed("right", true).ok,
    ).toBe(true);
    expect(owner.readCurrentApplicationDocumentIdentity()).toEqual({
      documentId: harness.state.document.id,
      revision: 1,
    });
  });
});

describe("A0/E0 owner ports: publishCanonicalExportRevision", () => {
  test("the CAS publishes, the exact replay installs and notifies nothing", () => {
    const harness = createHarness({ idleTransition: true });
    const owner = harness.composition.interchangeOwner;
    const documentId = harness.state.document.id;
    const request = markerRequest(documentId, 0);
    const published = owner.publishCanonicalExportRevision(request);
    expect(published).toEqual({
      ok: true,
      outcome: "published",
      documentId,
      revision: 0,
    });
    assertStateFree(published);
    expect(harness.notifications()).toBe(1);
    const view = harness.composition.controller.getSnapshot();
    expect(view.dirty).toMatchObject({
      sinceExport: false,
      label: "Exported at revision 0",
    });
    // Exact replay: state-free success, no install, no notification.
    const snapshotBefore = harness.composition.controller.getSnapshot();
    const replay = owner.publishCanonicalExportRevision(request);
    expect(replay).toEqual(published);
    expect(harness.composition.controller.getSnapshot()).toBe(snapshotBefore);
    expect(harness.notifications()).toBe(1);
  });

  test("both identity fields participate in the compare", () => {
    const harness = createHarness({ idleTransition: true });
    const owner = harness.composition.interchangeOwner;
    const documentId = harness.state.document.id;
    for (const request of [
      markerRequest(documentId, 5),
      markerRequest("someone-else", 0),
    ]) {
      expect(owner.publishCanonicalExportRevision(request)).toEqual({
        ok: false,
        outcome: "refused",
        code: "export.marker_publication_stale",
        observedDocumentId: documentId,
        observedRevision: 0,
      });
    }
    expect(harness.notifications()).toBe(0);
  });

  test("a document edit makes the old marker stale; the new revision publishes", () => {
    const harness = createHarness({ idleTransition: true });
    const owner = harness.composition.interchangeOwner;
    const documentId = harness.state.document.id;
    expect(harness.composition.controller.setTitle("Edited").ok).toBe(true);
    expect(owner.publishCanonicalExportRevision(markerRequest(documentId, 0)))
      .toEqual({
        ok: false,
        outcome: "refused",
        code: "export.marker_publication_stale",
        observedDocumentId: documentId,
        observedRevision: 1,
      });
    expect(owner.publishCanonicalExportRevision(markerRequest(documentId, 1)))
      .toEqual({
        ok: true,
        outcome: "published",
        documentId,
        revision: 1,
      });
  });

  test("picker-time ephemeral changes are retained when the identity matches", () => {
    const harness = createHarness({ idleTransition: true });
    const owner = harness.composition.interchangeOwner;
    expect(
      harness.composition.controller.setRailCollapsed("left", true).ok,
    ).toBe(true);
    expect(
      owner.publishCanonicalExportRevision(
        markerRequest(harness.state.document.id, 0),
      ),
    ).toMatchObject({ ok: true, outcome: "published" });
    expect(
      harness.composition.controller.getSnapshot().panels.leftRailCollapsed,
    ).toBe(true);
  });

  test("a malformed publication envelope refuses failed without an install", () => {
    const harness = createHarness({ idleTransition: true });
    const owner = harness.composition.interchangeOwner;
    const documentId = harness.state.document.id;
    const malformed: readonly PublishCanonicalExportRevisionRequest[] = [
      markerRequest(documentId, 0, "changes.canonical-export-revision-publication.v2"),
      markerRequest(documentId, -1),
      markerRequest(documentId, Number.NaN),
      markerRequest("", 0),
      Object.freeze({
        publication: Object.freeze({
          schema: MARKER_SCHEMA,
          documentId,
          revision: 0,
          smuggled: true,
        }),
      }),
    ];
    const snapshotBefore = harness.composition.controller.getSnapshot();
    for (const request of malformed) {
      expect(owner.publishCanonicalExportRevision(request)).toEqual({
        ok: false,
        outcome: "refused",
        code: "export.marker_publication_failed",
        observedDocumentId: documentId,
        observedRevision: 0,
      });
    }
    expect(harness.composition.controller.getSnapshot()).toBe(snapshotBefore);
    expect(harness.notifications()).toBe(0);
  });
});
