import {expect,test} from "bun:test";
import {createStudioCompositionOverState} from "../../src/application/studio-controller";
import {loopArrangementFixture} from "../support/loop-arrangement-fixture";
function setup(deferred=false,printFailure=false){const f=loopArrangementFixture(),downloads:Uint8Array[]=[];let prints=0,finish:(()=>void)|undefined;
 const composition=createStudioCompositionOverState(f.state,f.dependencies,{printReadyFont:()=>deferred?new Promise<void>(resolve=>{finish=resolve;}):Promise.resolve(),nativePrint:()=>{if(printFailure)throw new Error("Native print unavailable");prints++;},prepareSvgDownload:bytes=>()=>{downloads.push(bytes);return{issued:true,created:1,revoked:1,outstanding:0};}});const service=composition.printCharts;if(service===null)throw new Error("Unwired print");return{composition,service,downloads,prints:()=>prints,finish:()=>{if(!finish)throw new Error("Missing pending font");finish();}};}
test("real composition prepares, prints and downloads without marking the document saved",async()=>{const f=setup(),before=f.composition.readApplicationState();await f.service.prepare();expect(f.service.read().state).toBe("ready");f.service.print();f.service.download();f.service.download();expect(f.prints()).toBe(1);expect(f.downloads.length).toBe(1);expect(f.composition.readApplicationState()).toBe(before);});
test("edit invalidates prepared print and SVG before adapter activation",async()=>{const f=setup();await f.service.prepare();expect(f.composition.controller.setTitle("Changed").ok).toBe(true);expect(f.service.read().state).toBe("stale");f.service.print();f.service.download();expect(f.prints()).toBe(0);expect(f.downloads).toEqual([]);});
for(const action of ["close","paper","edit"] as const)test(`${action} during font preparation cannot resurrect old pages`,async()=>{const f=setup(true),pending=f.service.prepare();if(action==="close")f.service.close();if(action==="paper")f.service.setPaper("letter");if(action==="edit")f.composition.controller.setTitle("New chart");f.finish();await pending;expect(f.service.read().pages).toEqual([]);f.service.print();f.service.download();expect(f.prints()).toBe(0);expect(f.downloads).toEqual([]);});

test("native printing failure preserves the prepared SVG fallback",async()=>{const f=setup(false,true);await f.service.prepare();f.service.print();expect(f.service.read().state).toBe("ready");expect(f.service.read().canDownload).toBe(true);f.service.download();expect(f.downloads.length).toBe(1);});

test("overlay subscriber remount preserves source-bound preparation for native printing",async()=>{const f=setup();let seen=0;const old=f.service.subscribe(()=>{seen++;});await f.service.prepare();old();const ready=f.service.read();const fresh=f.service.subscribe(()=>{seen++;});expect(f.service.read().pages).toBe(ready.pages);f.service.print();expect(f.prints()).toBe(1);expect(seen).toBeGreaterThan(0);f.service.close();expect(f.service.read().pages).toEqual([]);fresh();});
