// @generated by scripts/physical-foundry.ts; do not edit.
pub const PARAMETER_TABLE_SCHEMA: &str = "changes.physical.parameter-table.v1";
pub const PARAMETER_PACK_VERSION: &str = "changes.clarinet-v2.reduced-lattice.1";
pub const PARAMETER_PACK_SHA256: &str =
    "56c0f4ba9015e2f088070290bf9150edbf7368f16a799b9fbf9986af6505f42e";
pub const PARAMETER_FAMILY: &str = "clarinet";
pub const PARAMETERS: &[(&str, &str, f64, f64, f64)] = &[
    ("air.density", "kg/m3", 1.2f64, 1.1f64, 1.3f64),
    ("air.sound-speed", "m/s", 343f64, 330f64, 350f64),
    ("bore.radius", "m", 0.007f64, 0.0065f64, 0.0075f64),
    ("bore.reference-length", "m", 0.5839f64, 0.5f64, 0.68f64),
    ("hole.0.axial", "m", 0.355f64, 0.3f64, 0.58f64),
    ("hole.0.chimney", "m", 0.006f64, 0.003f64, 0.01f64),
    ("hole.0.radius", "m", 0.003f64, 0.001f64, 0.006f64),
    ("hole.1.axial", "m", 0.397f64, 0.3f64, 0.58f64),
    ("hole.1.chimney", "m", 0.0058f64, 0.003f64, 0.01f64),
    ("hole.1.radius", "m", 0.0032f64, 0.001f64, 0.006f64),
    ("hole.2.axial", "m", 0.438f64, 0.3f64, 0.58f64),
    ("hole.2.chimney", "m", 0.0056f64, 0.003f64, 0.01f64),
    ("hole.2.radius", "m", 0.00345f64, 0.001f64, 0.006f64),
    ("hole.3.axial", "m", 0.477f64, 0.3f64, 0.58f64),
    ("hole.3.chimney", "m", 0.0053f64, 0.003f64, 0.01f64),
    ("hole.3.radius", "m", 0.0037f64, 0.001f64, 0.006f64),
    ("hole.4.axial", "m", 0.515f64, 0.3f64, 0.58f64),
    ("hole.4.chimney", "m", 0.005f64, 0.003f64, 0.01f64),
    ("hole.4.radius", "m", 0.004f64, 0.001f64, 0.006f64),
    ("hole.5.axial", "m", 0.551f64, 0.3f64, 0.58f64),
    ("hole.5.chimney", "m", 0.0048f64, 0.003f64, 0.01f64),
    ("hole.5.radius", "m", 0.0043f64, 0.001f64, 0.006f64),
    (
        "radiation.aperture-end-correction",
        "1",
        0.8488263631567752f64,
        0.8f64,
        0.9f64,
    ),
    ("reed.channel-width", "m", 0.012f64, 0.008f64, 0.016f64),
    ("reed.damping", "N*s/m", 0.02f64, 0.005f64, 0.08f64),
    (
        "reed.effective-area",
        "m2",
        0.0001f64,
        0.00005f64,
        0.0002f64,
    ),
    (
        "reed.equilibrium-opening",
        "m",
        0.0004f64,
        0.0002f64,
        0.0006f64,
    ),
    ("reed.mass", "kg", 0.00003f64, 0.00001f64, 0.0001f64),
    ("reed.stiffness", "N/m", 1500f64, 800f64, 3000f64),
    ("register.axial", "m", 0.165f64, 0.1f64, 0.25f64),
    ("register.chimney", "m", 0.0055f64, 0.003f64, 0.01f64),
    ("register.radius", "m", 0.00145f64, 0.0008f64, 0.0025f64),
    (
        "shunt.register-admittance-cap",
        "1",
        0.002f64,
        0.0005f64,
        0.12f64,
    ),
    (
        "shunt.tone-hole-admittance-cap",
        "1",
        0.005f64,
        0.001f64,
        0.35f64,
    ),
];
pub const CERTIFIED_MODES: &[(f64, f64, f64, f64)] = &[
    (146.857f64, 146.83f64, 146.89f64, 0.000172f64),
    (440.571f64, 440.49f64, 440.67f64, 0.000172f64),
    (734.285f64, 734.15f64, 734.45f64, 0.000172f64),
];
pub const APPLICABILITY_BOUNDS_JSON: &str = "{\"maximumFrequencyHz\":5000,\"maximumKa\":0.64,\"midiMaximum\":84,\"midiMinimum\":50,\"sampleRatesHz\":[44100,48000,96000],\"toneHoles\":6,\"vocalTractImpedance\":\"deferred\"}";
