import Foundation

enum JazzLibrary {
    // The 27 canonical ids mirror studio-progression-library.ts. The two
    // native-only original studies remain as additive material; they never
    // stand in for an omitted reviewed web entry. One source line per entry
    // keeps the reviewed musical corpus auditable.
    // swiftlint:disable line_length
    static let entries: [LibraryEntry] = [
        LibraryEntry(id: "two-five-one", title: "ii–V–I in C", kicker: "THE FOUNDATION CADENCE", note: "The sentence every other progression is built from.", provenance: .device, chartText: "| Dm7 | G7 | Cmaj7 | Cmaj7 |", key: .c, tempo: 132, groove: .mediumSwing),
        LibraryEntry(id: "one-six-two-five", title: "I–vi–ii–V turnaround", kicker: "TURNAROUND TEMPLATE", note: "Four bars that loop forever—the standard practice vamp.", provenance: .device, chartText: "| Cmaj7 | Am7 | Dm7 | G7 |", key: .c, tempo: 144, groove: .mediumSwing),
        LibraryEntry(id: "minor-two-five-one", title: "Minor ii–V–i", kicker: "THE MINOR CADENCE", note: "Half-diminished into an altered dominant, landing minor.", provenance: .device, chartText: "| Dm7b5 | G7b9 | Cm9 | Cm9 |", key: .c, tempo: 120, groove: .ballad),
        LibraryEntry(id: "jazz-blues-f", title: "Jazz blues in F", kicker: "BLUES TEMPLATE", note: "Twelve bars with the quick IV and a ii–V turnaround.", provenance: .device, chartText: "| F7 | Bb7 | F7 | F7 | Bb7 | Bb7 | F7 | D7 | Gm7 | C7 | F7 D7 | Gm7 C7 |", key: .f, tempo: 152, groove: .mediumSwing),
        LibraryEntry(id: "dorian-vamp", title: "Modal vamp in D Dorian", kicker: "MODAL DEVICE", note: "Two chords, no cadence—room to hear a mode instead of a key.", provenance: .device, chartText: "| Dm9 | Dm9 | Em9 | Dm9 |", key: .d, tempo: 116, groove: .straightEighths),
        LibraryEntry(id: "major-third-cycle", title: "Major-third cycle", kicker: "COLTRANE MATRIX", note: "Three tonal centers a major third apart, each reached by its dominant.", provenance: .device, chartText: "| Bmaj7 D7 | Gmaj7 Bb7 | Ebmaj7 | Am7 D7 | Gmaj7 Bb7 | Ebmaj7 F#7 | Bmaj7 | Fm7 Bb7 |", key: .b, tempo: nil, groove: .mediumSwing),
        LibraryEntry(id: "rhythm-turnaround", title: "Rhythm-changes A section", kicker: "TURNAROUND LANGUAGE", note: "I–vi–ii–V, a diminished pivot, then home again.", provenance: .device, chartText: "| Bb G7 | Cm7 F7 | Dm7 G7 | Cm7 F7 | Bb Bb7 | Ebmaj7 Edim7 | Bb/F G7 | Cm7 F7 |", key: .bb, tempo: nil, groove: .mediumSwing),
        LibraryEntry(id: "bird-blues", title: "Bird blues", kicker: "BEBOP BLUES", note: "A blues rebuilt from descending ii–Vs before rejoining the form.", provenance: .device, chartText: "| Fmaj7 | Em7b5 A7 | Dm7 G7 | Cm7 F7 | Bbmaj7 | Bbm7 Eb7 | Am7 | Abm7 Db7 | Gm7 | C7 | Fmaj7 D7 | Gm7 C7 |", key: .f, tempo: nil, groove: .mediumSwing),
        LibraryEntry(id: "tritone-chain", title: "Tritone substitution chain", kicker: "SUBSTITUTION DEVICE", note: "Shared tritones let dominant roots descend chromatically.", provenance: .device, chartText: "| Dm7 Db7 | Cmaj7 B7 | Bbm7 A7 | Abmaj7 G7 | Gm7 Gb7 | Fmaj7 E7 | Ebm7 D7 | Cmaj7 |", key: .c, tempo: nil, groove: .bossaNova),
        LibraryEntry(id: "tristan", title: "Tristan Prelude opening", kicker: "WAGNER · 1859", note: "A half-diminished sonority resolves to a dominant that refuses to land.", provenance: .publicDomain, chartText: "| Fm7b5 | E7 | Fm7b5 | E7 | Abm7b5 | G7 | Bm7b5 | Bb7 |", key: .a, tempo: nil, groove: .ballad),
        LibraryEntry(id: "commendatore", title: "Don Giovanni, Commendatore", kicker: "MOZART · 1787", note: "D minor with diminished-seventh pivots—the chord Mozart uses to make the ground give way.", provenance: .publicDomain, chartText: "| Dm | C#dim7 | Dm | Gm6 | A7 | Dm | Bbmaj7 | A7 |", key: .d, tempo: nil, groove: .ballad),
        LibraryEntry(id: "lament-bass", title: "Lament bass", kicker: "BAROQUE GROUND", note: "One bass line walks down a fourth while the harmony re-reads each step.", provenance: .publicDomain, chartText: "| Cm | Cm/B | Cm/Bb | Ab | Fm7b5 | G7 | Cm | G7 |", key: .c, tempo: nil, groove: .ballad),
        LibraryEntry(id: "pachelbel", title: "Pachelbel cycle", kicker: "PACHELBEL · C. 1680", note: "The most borrowed eight-bar cycle in tonal music.", provenance: .publicDomain, chartText: "| D | A | Bm | F#m | G | D | G | A |", key: .d, tempo: nil, groove: .straightEighths),
        LibraryEntry(id: "gymnopedie", title: "Gymnopédie colors", kicker: "SATIE · 1888", note: "Two major sevenths breathe against each other without a cadence.", provenance: .publicDomain, chartText: "| Gmaj7 | Dmaj7 | Gmaj7 | Dmaj7 | Gmaj7 | Bm7 | Em7 | A7 |", key: .g, tempo: nil, groove: .ballad),
        LibraryEntry(id: "ragtime", title: "Ragtime dominants", kicker: "JOPLIN · 1899", note: "A chain of dominants, each tonicizing the next.", provenance: .publicDomain, chartText: "| E7 | A7 | D7 | G7 | C | A7 | D7 G7 | C |", key: .c, tempo: nil, groove: .mediumSwing),
        LibraryEntry(id: "chopin-chromatic", title: "Chromatic descent", kicker: "CHOPIN · 1839", note: "Romantic voice leading: the top line holds while inner voices slide by semitone beneath it.", provenance: .publicDomain, chartText: "| Em | B7 | Em | Am6 | Em/B | F#7 | B7 | Em |", key: .e, tempo: nil, groove: .ballad),
        LibraryEntry(id: "minor-blues", title: "Minor blues with backdoor", kicker: "BLUES TEMPLATE", note: "Minor blues closes through the backdoor cadence, avoiding the ordinary leading-tone arrival.", provenance: .device, chartText: "| Cm7 | Fm7 | Cm7 | Cm7 | Fm7 | Fm7 | Cm7 | Ebm7 Ab7 | Dm7b5 | G7b9 | Cm7 Bb7 | Cm7 |", key: .c, tempo: nil, groove: .mediumSwing),
        LibraryEntry(id: "modal-planing", title: "Modal planing", kicker: "MODAL DEVICE", note: "One voicing shape moves bodily up and down; the mode changes while the hand shape stays recognizable.", provenance: .device, chartText: "| Dm7 | Dm7 | Ebm7 | Ebm7 | Dm7 | Dm7 | Ebm7 Dm7 | Dm7 |", key: .d, tempo: nil, groove: .bossaNova),
        LibraryEntry(id: "chromatic-mediants", title: "Chromatic mediants", kicker: "LATE-ROMANTIC DEVICE", note: "Major sonorities a third apart share one tone—the harmonic hinge behind a great deal of film scoring.", provenance: .device, chartText: "| Cmaj7 | Abmaj7 | Emaj7 | Cmaj7 | Abmaj7 | Emaj7 | Fmaj7 | G7sus4 |", key: .c, tempo: nil, groove: .straightEighths),
        LibraryEntry(id: "mu-major-study", title: "Mu-major study", kicker: "ORIGINAL STUDY", note: "Add-nine major colors without the seventh create a bright, suspended studio sonority.", provenance: .study, chartText: "| Cadd9 | Aadd9 | Fadd9 | Gadd9 | Cadd9 Ebmaj7 | Dm9 | G13 | Cadd9 |", key: .c, tempo: nil, groove: .straightEighths),
        LibraryEntry(id: "lush-ballad-study", title: "Lush ballad study", kicker: "ORIGINAL STUDY", note: "Extended harmony keeps moving over a bass line that descends one careful step at a time.", provenance: .study, chartText: "| Fmaj7#11 | Em7 A7b9 | Dm9 | Db13 | Cmaj7 | Bm7b5 E7b9 | Am9 D13 | Gm7 C13 |", key: .f, tempo: nil, groove: .ballad),
        LibraryEntry(id: "gospel-blues-study", title: "Gospel-blues study", kicker: "ORIGINAL STUDY", note: "Plagal motion, a diminished pivot, and a walk-up to the turn connect church cadence language with blues harmony.", provenance: .study, chartText: "| Bbmaj7 | Ebmaj7 | Bbmaj7 | Bb7 | Ebmaj7 | Edim7 | Bb/F | Gm7 | Cm7 | F7b9 | Bbmaj7 G7b9 | Cm7 F7 |", key: .bb, tempo: nil, groove: .mediumSwing),
        LibraryEntry(id: "whole-tone-study", title: "Whole-tone approach", kicker: "ORIGINAL STUDY", note: "Augmented triads and altered dominants create a floating field before diatonic gravity returns.", provenance: .study, chartText: "| Caug | Daug | Caug | Fmaj7 | Bm7b5 E7b9 | Am7 | Dm7 G7 | Cmaj7 |", key: .c, tempo: nil, groove: .ballad),
        LibraryEntry(id: "what-a-fool-believes", title: "What a Fool Believes", kicker: "MCDONALD & LOGGINS · 1979", note: "The keyboard riff walks IVmaj7 through a first-inversion tonic to ii7 under slash-chord elevenths, then the parallel-minor iv pivots the chorus into E major without a seam.", provenance: .ownerDirected, chartText: "| Gb/Ab Gbmaj7 | Db/F Ebm7 | Gb/Ab Gbmaj7 | Db/F Ebm7 | Ebm7 Db/F | Bbm7 A7#5 | Bbm7 | Ab7sus4 | Ebm7 Gb/Ab | Dbmaj7 Gm7b5 | F#m7 A/B | Emaj7 C#m7 | F#m7 A/B | Emaj7 A7#5 |", key: .db, tempo: 120, groove: .syncopatedSixteenths),
        LibraryEntry(id: "giant-steps", title: "Giant Steps", kicker: "COLTRANE · 1960", note: "The full sixteen-bar head of the Coltrane-changes standard: a phrase in B answered in G and resolved in Eb, every tonic entered through its own dominant.", provenance: .ownerDirected, chartText: "| Bmaj7 | D7 Gmaj7 | Bb7 Ebmaj7 | Am7 D7 | Gmaj7 | Bb7 Ebmaj7 | F#7 Bmaj7 | Fm7 Bb7 | Ebmaj7 | Am7 D7 | Gmaj7 | C#m7 F#7 | Bmaj7 | Fm7 Bb7 | Ebmaj7 | C#m7 F#7 |", key: .b, tempo: 290, groove: .uptempoSwing),
        LibraryEntry(id: "peg", title: "Peg", kicker: "FAGEN & BECKER · 1977", note: "The intro descent in five chromatically falling colors—maj9, sharp-nine dominant, six-nine, sharp-nine dominant, six-nine again—the doorway into the Aja album's most famous solo vehicle.", provenance: .ownerDirected, chartText: "| Gmaj9 | F#7#9 | F6/9 | E7#9 | Eb6/9 |", key: .g, tempo: 119, groove: .syncopatedSixteenths),
        LibraryEntry(id: "hello-its-me", title: "Hello, It's Me", kicker: "RUNDGREN · 1972", note: "Written at eighteen and re-cut as the mid-tempo classic of Something/Anything?: a Gm7–Fmaj7 vamp that descends the whole diatonic ladder of Bb before it lets the tonic land.", provenance: .ownerDirected, chartText: "| Gm7 | Fmaj7 | Gm7 | Fmaj7 | Gm7 | Fmaj7 | Gm7 | Fmaj7 | Ebmaj7 | Dm7 | Cm7 | Gm7 | Bb | Bb | Bb | F |", key: .bb, tempo: 91, groove: .ballad),
        LibraryEntry(id: "glass-lab", title: "Glass elevator", kicker: "ORIGINAL STUDY", note: "Parallel major sevenths meet chromatic dominant gravity.", provenance: .study, chartText: "| Cmaj7 | Ebmaj7 | Abmaj7 | Db7 | Cmaj7 A7 | Dm9 G13 | Cmaj9 | Cmaj9 |", key: .c, tempo: 112, groove: .straightEighths),
        LibraryEntry(id: "backdoor", title: "Backdoor after midnight", kicker: "ORIGINAL STUDY", note: "A minor iv and ♭VII dominant avoid the ordinary leading-tone cadence.", provenance: .study, chartText: "| Cmaj7 | Fm9 | Bb13 | Cmaj9 | Am7 | D7#9 | Dm9 G13 | Cmaj9 |", key: .c, tempo: 92, groove: .ballad)
    ]
    // swiftlint:enable line_length

    static let starter = LibraryEntry(
        id: "starter",
        title: "Midnight laboratory",
        kicker: "WELCOME CHART",
        note: "A compact original progression with enough color to explore every surface.",
        provenance: .study,
        chartText: "| Cmaj9 | Bm7b5 E7b9 | Am9 | D13 | Dm9 G13 | Cmaj7 A7#5 | Dm9 G7b9 | C6 |",
        key: .c,
        tempo: 118,
        groove: .mediumSwing
    )
}
