/**
 * Host for the embedded Concert Grand DSP module.
 *
 * The wasm payload is checked-in source (`./wasm/concert-grand-wasm.ts`,
 * generated by `scripts/build-dsp.ts` from `dsp/concert-grand`). This module
 * decodes and instantiates it once, owns its linear memory layout, and turns
 * `(midiPitch, velocity, sampleRate)` into freshly copied stereo PCM. Renders
 * are bit-deterministic: the module imports nothing from the host — no clock,
 * no random device, no I/O — so the PCM goldens can pin exact hashes.
 *
 * Layer position: audio-internal. The engine caches the PCM in Web Audio
 * buffers; no other layer sees this module or the wasm instance.
 */
import {
  CONCERT_GRAND_WASM_BASE64,
  CONCERT_GRAND_WASM_BYTE_LENGTH,
  CONCERT_GRAND_WASM_SHA256,
} from "./wasm/concert-grand-wasm";

export const CONCERT_GRAND_RENDERER_ALGORITHM_ID =
  "changes.dsp.concert-grand@1";

export type RenderedNotePcm = Readonly<{
  sampleRateHz: number;
  frameCount: number;
  left: Float32Array<ArrayBuffer>;
  right: Float32Array<ArrayBuffer>;
}>;

export type DetectedNote = Readonly<{
  midiPitch: number;
  centsDeviation: number;
  strength: number;
}>;

export type AnalysisFrame = Readonly<{
  sampleRateHz: number;
  fftSize: number;
  /** Hann-windowed magnitude spectrum, fftSize/2 bins. */
  magnitudes: Float32Array<ArrayBuffer>;
  /** Harmonically grouped fundamentals, strongest first. */
  notes: readonly DetectedNote[];
  /** Pitch-class energy fold (C first), unit-maximum normalized. */
  chroma: Float32Array<ArrayBuffer>;
}>;

export type ConcertGrandRenderer = Readonly<{
  algorithmId: typeof CONCERT_GRAND_RENDERER_ALGORITHM_ID;
  wasmSha256: string;
  /**
   * Render one note. Synchronous and pure after instantiation; returns null
   * only for an out-of-contract request (pitch outside 21..108, velocity
   * outside 1..127, unsupported sample rate).
   */
  renderNote: (
    midiPitch: number,
    velocity: number,
    sampleRateHz: number,
  ) => RenderedNotePcm | null;
  /**
   * Analyze one time-domain window: windowed FFT, spectral-peak note
   * detection with harmonic grouping, and a chroma fold. `samples.length`
   * must be a power of two in 64..8192. Null on an out-of-contract request.
   */
  analyzeWindow: (
    samples: Float32Array,
    sampleRateHz: number,
  ) => AnalysisFrame | null;
}>;

type ConcertGrandExports = Readonly<{
  memory: WebAssembly.Memory;
  __heap_base?: WebAssembly.Global;
  cg_note_frames: (midi: number, sampleRate: number) => number;
  cg_render: (
    midi: number,
    velocity: number,
    sampleRate: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  an_spectrum: (input: number, frames: number, magnitudes: number) => number;
  an_notes: (
    magnitudes: number,
    bins: number,
    sampleRate: number,
    fftSize: number,
    out: number,
    maxNotes: number,
  ) => number;
  an_chroma: (
    magnitudes: number,
    bins: number,
    sampleRate: number,
    fftSize: number,
    out: number,
  ) => number;
}>;

function decodeWasmBytes(): Uint8Array<ArrayBuffer> {
  const decoded = atob(CONCERT_GRAND_WASM_BASE64);
  if (decoded.length !== CONCERT_GRAND_WASM_BYTE_LENGTH) {
    throw new Error("DSP_WASM_PAYLOAD_LENGTH_MISMATCH");
  }
  const bytes = new Uint8Array(decoded.length);
  for (let index = 0; index < decoded.length; index += 1) {
    bytes[index] = decoded.charCodeAt(index);
  }
  return bytes;
}

const PAGE_BYTES = 65_536;

/**
 * Grow the module memory so `[offset, offset + bytes)` is addressable.
 * Growth detaches previous buffer views, so callers re-read `memory.buffer`
 * after every call.
 */
function ensureCapacity(
  memory: WebAssembly.Memory,
  offset: number,
  bytes: number,
): void {
  const needed = offset + bytes - memory.buffer.byteLength;
  if (needed > 0) {
    memory.grow(Math.ceil(needed / PAGE_BYTES));
  }
}

let rendererPromise: Promise<ConcertGrandRenderer> | null = null;

function requireExportedFunction(
  exports: WebAssembly.Exports,
  name: string,
): CallableFunction {
  const candidate = exports[name];
  if (typeof candidate !== "function") {
    throw new Error(`DSP_WASM_EXPORT_MISSING:${name}`);
  }
  return candidate;
}

async function instantiate(): Promise<ConcertGrandRenderer> {
  const bytes = decodeWasmBytes();
  const { instance } = await WebAssembly.instantiate(bytes, {});
  const rawExports = instance.exports;
  const memoryCandidate = rawExports["memory"];
  if (!(memoryCandidate instanceof WebAssembly.Memory)) {
    throw new Error("DSP_WASM_EXPORT_MISSING:memory");
  }
  const heapBaseCandidate = rawExports["__heap_base"];
  const exports: ConcertGrandExports = {
    memory: memoryCandidate,
    ...(heapBaseCandidate instanceof WebAssembly.Global
      ? { __heap_base: heapBaseCandidate }
      : {}),
    /*
     * Wasm export signatures are not statically typed; each callable is
     * runtime-verified above and asserted to its concrete numeric signature.
     */
    cg_note_frames: requireExportedFunction(
      rawExports,
      "cg_note_frames",
    ) as ConcertGrandExports["cg_note_frames"],
    cg_render: requireExportedFunction(
      rawExports,
      "cg_render",
    ) as ConcertGrandExports["cg_render"],
    an_spectrum: requireExportedFunction(
      rawExports,
      "an_spectrum",
    ) as ConcertGrandExports["an_spectrum"],
    an_notes: requireExportedFunction(
      rawExports,
      "an_notes",
    ) as ConcertGrandExports["an_notes"],
    an_chroma: requireExportedFunction(
      rawExports,
      "an_chroma",
    ) as ConcertGrandExports["an_chroma"],
  };
  const memory = exports.memory;
  /* Scratch region starts past the module's own data and shadow stack. */
  const heapBase =
    typeof exports.__heap_base?.value === "number"
      ? exports.__heap_base.value
      : memory.buffer.byteLength;
  const scratchBase = Math.ceil((heapBase + 1_024) / 16) * 16;

  const renderNote = (
    midiPitch: number,
    velocity: number,
    sampleRateHz: number,
  ): RenderedNotePcm | null => {
    const capacity = exports.cg_note_frames(midiPitch, sampleRateHz);
    if (capacity <= 0) return null;
    const channelBytes = capacity * 4;
    const leftPointer = scratchBase;
    const rightPointer = scratchBase + channelBytes;
    ensureCapacity(memory, scratchBase, channelBytes * 2);
    const written = exports.cg_render(
      midiPitch,
      velocity,
      sampleRateHz,
      leftPointer,
      rightPointer,
      capacity,
    );
    if (written <= 0) return null;
    /* Copy out: the scratch region is reused by the next render. */
    const left = new Float32Array(written);
    const right = new Float32Array(written);
    left.set(new Float32Array(memory.buffer, leftPointer, written));
    right.set(new Float32Array(memory.buffer, rightPointer, written));
    return Object.freeze({
      sampleRateHz,
      frameCount: written,
      left,
      right,
    });
  };

  const MAX_DETECTED_NOTES = 12;

  const analyzeWindow = (
    samples: Float32Array,
    sampleRateHz: number,
  ): AnalysisFrame | null => {
    const fftSize = samples.length;
    if (
      fftSize < 64 ||
      fftSize > 8_192 ||
      (fftSize & (fftSize - 1)) !== 0 ||
      !Number.isFinite(sampleRateHz) ||
      sampleRateHz <= 0
    ) {
      return null;
    }
    const binCount = fftSize / 2;
    /*
     * Scratch layout: input window, magnitude bins, note triples, chroma —
     * all in the same reusable region past the render scratch.
     */
    const inputPointer = scratchBase;
    const magnitudesPointer = inputPointer + fftSize * 4;
    const notesPointer = magnitudesPointer + binCount * 4;
    const chromaPointer = notesPointer + MAX_DETECTED_NOTES * 3 * 4;
    ensureCapacity(memory, scratchBase, chromaPointer + 12 * 4 - scratchBase);
    new Float32Array(memory.buffer, inputPointer, fftSize).set(samples);
    const bins = exports.an_spectrum(inputPointer, fftSize, magnitudesPointer);
    if (bins !== binCount) return null;
    const noteCount = exports.an_notes(
      magnitudesPointer,
      bins,
      sampleRateHz,
      fftSize,
      notesPointer,
      MAX_DETECTED_NOTES,
    );
    const chromaCount = exports.an_chroma(
      magnitudesPointer,
      bins,
      sampleRateHz,
      fftSize,
      chromaPointer,
    );
    if (chromaCount !== 12 || noteCount < 0) return null;
    const magnitudes = new Float32Array(binCount);
    magnitudes.set(new Float32Array(memory.buffer, magnitudesPointer, binCount));
    const chroma = new Float32Array(12);
    chroma.set(new Float32Array(memory.buffer, chromaPointer, 12));
    const triples = new Float32Array(memory.buffer, notesPointer, noteCount * 3);
    const notes: DetectedNote[] = [];
    for (let index = 0; index < noteCount; index += 1) {
      notes.push(
        Object.freeze({
          midiPitch: triples[index * 3] ?? 0,
          centsDeviation: triples[index * 3 + 1] ?? 0,
          strength: triples[index * 3 + 2] ?? 0,
        }),
      );
    }
    return Object.freeze({
      sampleRateHz,
      fftSize,
      magnitudes,
      notes: Object.freeze(notes),
      chroma,
    });
  };

  return Object.freeze({
    algorithmId: CONCERT_GRAND_RENDERER_ALGORITHM_ID,
    wasmSha256: CONCERT_GRAND_WASM_SHA256,
    renderNote,
    analyzeWindow,
  });
}

/**
 * Instantiate the module once per page. A rejected instantiation is not
 * cached: a later caller may retry, and the engine surfaces the stable
 * refusal `audio.renderer_unavailable` in the meantime.
 */
export function loadConcertGrandRenderer(): Promise<ConcertGrandRenderer> {
  rendererPromise ??= instantiate().catch((error: unknown) => {
    rendererPromise = null;
    throw error instanceof Error ? error : new Error(String(error));
  });
  return rendererPromise;
}
