/**
 * Host for the embedded Concert Grand DSP module.
 *
 * The wasm payload is checked-in source (`./wasm/concert-grand-wasm.ts`,
 * generated by `scripts/build-dsp.ts` from `dsp/concert-grand`). This module
 * decodes and instantiates it once, owns its linear memory layout, and turns
 * `(midiPitch, velocity, sampleRate)` into freshly copied stereo PCM. Renders
 * are bit-deterministic: the module imports nothing from the host — no clock,
 * no random device, no I/O — so the PCM goldens can pin exact hashes.
 *
 * The rendered note is a HYBRID. Synthesis alone cannot produce the hammer
 * strike of a real instrument, so the first third of a second comes from a
 * recorded Yamaha C5 (`./wasm/piano-attack-samples.ts`) and is crossfaded
 * into the synthesized sustain. The sampled layer is transposed from the
 * nearest recorded key, level- and balance-matched to the synth layer over
 * the crossfade window, and peak-limited; a pitch or velocity outside the
 * recorded set simply renders as pure synthesis. Everything here is a pure
 * function of `(midiPitch, velocity, sampleRateHz)`.
 *
 * Layer position: audio-internal. The engine caches the PCM in Web Audio
 * buffers; no other layer sees this module or the wasm instance.
 */
import {
  CONCERT_GRAND_WASM_BASE64,
  CONCERT_GRAND_WASM_BYTE_LENGTH,
  CONCERT_GRAND_WASM_SHA256,
} from "./wasm/concert-grand-wasm";
import {
  PIANO_ATTACK_SAMPLE_RATE_HZ,
  PIANO_ATTACK_SAMPLES_ATTRIBUTION,
  PIANO_ATTACK_SAMPLES_BASE64,
  PIANO_ATTACK_SAMPLES_BYTE_LENGTH,
  PIANO_ATTACK_SAMPLES_LICENSE,
  PIANO_ATTACK_SAMPLES_SHA256,
  PIANO_ATTACK_SLICE_INDEX,
  type PianoAttackSlice,
} from "./wasm/piano-attack-samples";

export const CONCERT_GRAND_RENDERER_ALGORITHM_ID =
  "changes.dsp.concert-grand@1";

/**
 * The reviewed crossfade design. The sampled attack owns the note outright
 * until `sampleOnlySeconds`; a cosine/sine crossfade then hands the note to
 * the synthesized sustain by `crossfadeEndSeconds`.
 *
 * Equal power alone would be the wrong law. It assumes the two layers are
 * uncorrelated, and these two are not: they are the same note, they both
 * begin at the onset, and the build-time stretch correction deliberately
 * puts their fundamentals on one frequency, so their relative phase is fixed
 * for the whole handover. Measured across the keyboard that correlation runs
 * from -0.97 to +0.99, and where it is negative the two layers cancel — a
 * hole up to 14.4 dB deep in the middle of the crossfade. The weights are
 * therefore corrected for the coherence the note actually has; see
 * `applyAttackLayer`.
 */
export const PIANO_ATTACK_LAYER_POLICY = Object.freeze({
  id: "changes.dsp.piano-attack-layer.v1",
  attribution: PIANO_ATTACK_SAMPLES_ATTRIBUTION,
  license: PIANO_ATTACK_SAMPLES_LICENSE,
  payloadSha256: PIANO_ATTACK_SAMPLES_SHA256,
  sampleOnlySeconds: 0.18,
  crossfadeEndSeconds: 0.32,
  /**
   * Level is matched twice: once over the attack the sampled layer owns, and
   * once over the crossfade window it hands off in. A recorded string and a
   * modelled one do not decay at quite the same rate, so a single match would
   * either misstate the attack's loudness or step at the seam. The correction
   * interpolates log-linearly in time between the two — the exact shape that
   * turns one exponential decay into another — and is clamped so a badly
   * mismatched pair degrades instead of exploding.
   */
  attackWindowStartSeconds: 0.02,
  attackWindowEndSeconds: 0.18,
  matchWindowStartSeconds: 0.18,
  matchWindowEndSeconds: 0.32,
  maximumDecayCorrectionRatio: 4,
  /** A recorded key is never stretched further than this. */
  maximumTranspositionSemitones: 3,
  /** The sampled layer is ducked before the hybrid can exceed this. */
  peakCeiling: 0.945,
  /** How fast that duck may move, so it can never be heard as a step. */
  peakGuardSlewDecibelsPerSecond: 60,
  interpolation: "catmull-rom",
} as const);

export type RenderedNotePcm = Readonly<{
  sampleRateHz: number;
  frameCount: number;
  left: Float32Array<ArrayBuffer>;
  right: Float32Array<ArrayBuffer>;
}>;

export type DetectedNote = Readonly<{
  midiPitch: number;
  centsDeviation: number;
  strength: number;
}>;

export type AnalysisFrame = Readonly<{
  sampleRateHz: number;
  fftSize: number;
  /** Hann-windowed magnitude spectrum, fftSize/2 bins. */
  magnitudes: Float32Array<ArrayBuffer>;
  /** Harmonically grouped fundamentals, strongest first. */
  notes: readonly DetectedNote[];
  /** Pitch-class energy fold (C first), unit-maximum normalized. */
  chroma: Float32Array<ArrayBuffer>;
}>;

export type ConcertGrandRenderer = Readonly<{
  algorithmId: typeof CONCERT_GRAND_RENDERER_ALGORITHM_ID;
  wasmSha256: string;
  attackSamplesSha256: string;
  /**
   * Render one note: the recorded attack crossfaded into the synthesized
   * sustain. Synchronous and pure after instantiation; returns null only for
   * an out-of-contract request (pitch outside 21..108, velocity outside
   * 1..127, unsupported sample rate). A note the sample corpus cannot serve
   * still renders — as pure synthesis.
   */
  renderNote: (
    midiPitch: number,
    velocity: number,
    sampleRateHz: number,
    /**
     * Optional ceiling on the rendered length, seconds. A performance holds
     * most notes for a fraction of their natural decay, and rendering the
     * full eight-second bass tail only to gate it off after half a second
     * costs more than an order of magnitude of the work. The tail is trimmed
     * with a short fade so a truncated render cannot click.
     */
    maxSeconds?: number,
  ) => RenderedNotePcm | null;
  /**
   * The same note with the sampled attack layer withheld. Evidence surface
   * only: it exists so a test can prove the layer changes the tone, and the
   * engine never calls it.
   */
  renderSynthesizedNote: (
    midiPitch: number,
    velocity: number,
    sampleRateHz: number,
  ) => RenderedNotePcm | null;
  /**
   * The recorded slice `renderNote` would use, or null when the request
   * falls outside the sampled set. Evidence surface only.
   */
  attackSliceFor: (
    midiPitch: number,
    velocity: number,
  ) => PianoAttackSlice | null;
  /**
   * Analyze one time-domain window: windowed FFT, spectral-peak note
   * detection with harmonic grouping, and a chroma fold. `samples.length`
   * must be a power of two in 64..8192. Null on an out-of-contract request.
   */
  analyzeWindow: (
    samples: Float32Array,
    sampleRateHz: number,
  ) => AnalysisFrame | null;
}>;

type ConcertGrandExports = Readonly<{
  memory: WebAssembly.Memory;
  __heap_base?: WebAssembly.Global;
  cg_note_frames: (midi: number, sampleRate: number) => number;
  cg_render: (
    midi: number,
    velocity: number,
    sampleRate: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  an_spectrum: (input: number, frames: number, magnitudes: number) => number;
  an_notes: (
    magnitudes: number,
    bins: number,
    sampleRate: number,
    fftSize: number,
    out: number,
    maxNotes: number,
  ) => number;
  an_chroma: (
    magnitudes: number,
    bins: number,
    sampleRate: number,
    fftSize: number,
    out: number,
  ) => number;
}>;

function decodeWasmBytes(): Uint8Array<ArrayBuffer> {
  const decoded = atob(CONCERT_GRAND_WASM_BASE64);
  if (decoded.length !== CONCERT_GRAND_WASM_BYTE_LENGTH) {
    throw new Error("DSP_WASM_PAYLOAD_LENGTH_MISMATCH");
  }
  const bytes = new Uint8Array(decoded.length);
  for (let index = 0; index < decoded.length; index += 1) {
    bytes[index] = decoded.charCodeAt(index);
  }
  return bytes;
}

/* ------------------------------------------------------------------ *
 * Recorded attack layer                                               *
 * ------------------------------------------------------------------ */

let attackSampleStore: Int16Array<ArrayBuffer> | null = null;
let attackSampleStoreRefused = false;

/**
 * Decode the embedded PCM once, on the first note that needs it. The payload
 * is raw single-channel 16-bit little-endian PCM, and each pair of bytes is
 * recombined explicitly rather than aliased through a typed-array view: the
 * result is identical on a big-endian host, and the decode never depends on
 * a browser media API.
 */
function attackSamples(): Int16Array<ArrayBuffer> | null {
  if (attackSampleStore !== null) return attackSampleStore;
  if (attackSampleStoreRefused) return null;
  try {
    const decoded = atob(PIANO_ATTACK_SAMPLES_BASE64);
    if (
      decoded.length !== PIANO_ATTACK_SAMPLES_BYTE_LENGTH ||
      decoded.length % 2 !== 0
    ) {
      throw new Error("DSP_ATTACK_PAYLOAD_LENGTH_MISMATCH");
    }
    const samples = new Int16Array(decoded.length / 2);
    for (let index = 0; index < samples.length; index += 1) {
      const low = decoded.charCodeAt(index * 2) & 0xff;
      const high = decoded.charCodeAt(index * 2 + 1) & 0xff;
      samples[index] = (((high << 8) | low) << 16) >> 16;
    }
    attackSampleStore = samples;
    return samples;
  } catch {
    /* A corrupt payload demotes the instrument to pure synthesis, never a
     * failed note. */
    attackSampleStoreRefused = true;
    return null;
  }
}

/**
 * The recorded slice that serves this request: the velocity bucket that
 * contains the velocity, and within it the recorded key nearest the target.
 * Ties resolve to the higher key so the transposition runs downward, which
 * consumes less of the stored slice.
 */
function selectAttackSlice(
  midiPitch: number,
  velocity: number,
): PianoAttackSlice | null {
  let best: PianoAttackSlice | null = null;
  let bestDistance = Number.POSITIVE_INFINITY;
  for (const slice of PIANO_ATTACK_SLICE_INDEX) {
    if (velocity < slice.lowVelocity || velocity > slice.highVelocity) continue;
    const distance = Math.abs(slice.midiPitch - midiPitch);
    if (distance <= bestDistance) {
      bestDistance = distance;
      best = slice;
    }
  }
  if (
    best === null ||
    bestDistance > PIANO_ATTACK_LAYER_POLICY.maximumTranspositionSemitones
  ) {
    return null;
  }
  return best;
}

/**
 * Whether a slice's whole PCM range is addressable inside the decoded
 * payload. The generator guarantees this, but that guarantee lives in a
 * generated file, and reading outside the range is not a benign failure: a
 * partial overrun truncates the layer to silence mid-crossfade and a
 * negative offset plays a neighbouring recording, both audible. Checking it
 * here means a malformed entry degrades to pure synthesis instead.
 */
function attackSliceIsAddressable(
  store: Int16Array,
  slice: PianoAttackSlice,
): boolean {
  const base = slice.byteOffset / 2;
  return (
    Number.isSafeInteger(base) &&
    base >= 0 &&
    Number.isSafeInteger(slice.frameCount) &&
    slice.frameCount >= 2 &&
    base + slice.frameCount <= store.length
  );
}

/**
 * Transpose one slice onto the requested pitch and output rate with a
 * Catmull-Rom kernel. The kernel is a fixed cubic over four neighbours: no
 * table, no filter state, no branch on data, so the same request yields the
 * same floats on every host.
 */
function transposeAttackSlice(
  store: Int16Array,
  slice: PianoAttackSlice,
  midiPitch: number,
  sampleRateHz: number,
  frames: number,
): Float32Array<ArrayBuffer> {
  const out = new Float32Array(frames);
  const base = slice.byteOffset / 2;
  const last = slice.frameCount - 1;
  /*
   * The recorded key is stretch-tuned; `tuningCents` is how far it sits from
   * 12-TET, so subtracting it lands the transposed attack on the same pitch
   * the synthesized sustain holds and the two layers do not beat.
   */
  const semitones =
    midiPitch - slice.midiPitch - slice.tuningCents / 100;
  const step =
    2 ** (semitones / 12) * (PIANO_ATTACK_SAMPLE_RATE_HZ / sampleRateHz);
  const at = (offset: number): number => {
    const clamped = offset < 0 ? 0 : offset > last ? last : offset;
    return (store[base + clamped] ?? 0) / 32_768;
  };
  for (let frame = 0; frame < frames; frame += 1) {
    const position = frame * step;
    const index = Math.floor(position);
    if (index >= last) break;
    const t = position - index;
    const p0 = at(index - 1);
    const p1 = at(index);
    const p2 = at(index + 1);
    const p3 = at(index + 2);
    out[frame] =
      0.5 *
      (2 * p1 +
        (p2 - p0) * t +
        (2 * p0 - 5 * p1 + 4 * p2 - p3) * t * t +
        (3 * p1 - p0 - 3 * p2 + p3) * t * t * t);
  }
  return out;
}

function windowRms(
  channel: Float32Array,
  start: number,
  end: number,
): number {
  if (end <= start) return 0;
  let total = 0;
  for (let frame = start; frame < end; frame += 1) {
    const value = channel[frame] ?? 0;
    total += value * value;
  }
  return Math.sqrt(total / (end - start));
}

/**
 * Fold the recorded attack into an already-rendered synthesized note, in
 * place. Returns false when the corpus cannot serve the request, in which
 * case the synthesized note is left exactly as it was.
 */
function applyAttackLayer(
  left: Float32Array,
  right: Float32Array,
  frameCount: number,
  midiPitch: number,
  velocity: number,
  sampleRateHz: number,
): boolean {
  const slice = selectAttackSlice(midiPitch, velocity);
  if (slice === null) return false;
  const store = attackSamples();
  if (store === null) return false;
  if (!attackSliceIsAddressable(store, slice)) return false;

  const policy = PIANO_ATTACK_LAYER_POLICY;
  const layerFrames = Math.min(
    Math.round(policy.crossfadeEndSeconds * sampleRateHz),
    frameCount,
  );
  const soloFrames = Math.min(
    Math.round(policy.sampleOnlySeconds * sampleRateHz),
    layerFrames,
  );
  const crossfadeFrames = layerFrames - soloFrames;
  if (crossfadeFrames <= 0) return false;

  const attack = transposeAttackSlice(
    store,
    slice,
    midiPitch,
    sampleRateHz,
    layerFrames,
  );

  /*
   * Two matching windows. The seam window fixes the handover level exactly;
   * the attack window fixes how loud the recorded hammer strike sits inside
   * the note, which is what carries the instrument's velocity law.
   */
  const attackStart = Math.min(
    Math.round(policy.attackWindowStartSeconds * sampleRateHz),
    layerFrames,
  );
  const attackEnd = Math.min(
    Math.round(policy.attackWindowEndSeconds * sampleRateHz),
    layerFrames,
  );
  const matchStart = Math.min(
    Math.round(policy.matchWindowStartSeconds * sampleRateHz),
    layerFrames,
  );
  const matchEnd = Math.min(
    Math.round(policy.matchWindowEndSeconds * sampleRateHz),
    layerFrames,
  );
  const sampleSeamRms = windowRms(attack, matchStart, matchEnd);
  const sampleAttackRms = windowRms(attack, attackStart, attackEnd);
  if (!(sampleSeamRms > 1e-9) || !(sampleAttackRms > 1e-9)) return false;

  const synthSeamLeft = windowRms(left, matchStart, matchEnd);
  const synthSeamRight = windowRms(right, matchStart, matchEnd);
  const synthSeamRms = Math.sqrt(
    (synthSeamLeft * synthSeamLeft + synthSeamRight * synthSeamRight) / 2,
  );
  const synthAttackRms = Math.sqrt(
    (windowRms(left, attackStart, attackEnd) ** 2 +
      windowRms(right, attackStart, attackEnd) ** 2) /
      2,
  );
  if (!(synthSeamRms > 1e-9) || !(synthAttackRms > 1e-9)) return false;

  /* Stereo placement comes from the synth layer, measured at the seam. */
  const balanceLeft = synthSeamLeft / synthSeamRms;
  const balanceRight = synthSeamRight / synthSeamRms;

  /*
   * The handover window: the middle half of the seam window, which is where
   * the two layers actually overlap — the product of the crossfade weights
   * peaks at the centre and vanishes at both ends. Both the level the note
   * hands over at and the coherence correction below are measured here
   * rather than over the whole seam. A recorded string and a modelled one
   * do not decay at the same rate, so an RMS averaged over the full seam is
   * dominated by whichever layer is loudest at its start and can leave the
   * two mismatched by several decibels at the instant they cross.
   */
  const handoverRadius = Math.max(1, Math.round((matchEnd - matchStart) / 4));
  const handoverCentre = Math.round((matchStart + matchEnd) / 2);
  const handoverStart = Math.max(0, handoverCentre - handoverRadius);
  const handoverEnd = Math.min(layerFrames, handoverCentre + handoverRadius);
  const sampleHandoverRms = windowRms(attack, handoverStart, handoverEnd);
  const synthHandoverRms = Math.sqrt(
    (windowRms(left, handoverStart, handoverEnd) ** 2 +
      windowRms(right, handoverStart, handoverEnd) ** 2) /
      2,
  );
  if (!(sampleHandoverRms > 1e-9) || !(synthHandoverRms > 1e-9)) return false;

  const seamGain = synthHandoverRms / sampleHandoverRms;
  const rawAttackGain = synthAttackRms / sampleAttackRms;
  const maximum = policy.maximumDecayCorrectionRatio;
  const correction = Math.min(
    maximum,
    Math.max(1 / maximum, rawAttackGain / seamGain),
  );

  /*
   * How much of the two layers is literally the same waveform. A
   * cosine/sine pair only holds the level constant when this is zero; at -1
   * the layers annihilate at the midpoint, and half the keyboard measures
   * past -0.5.
   */
  const balanceEnergy = balanceLeft * balanceLeft + balanceRight * balanceRight;
  let crossEnergy = 0;
  let sampleEnergy = 0;
  let synthEnergy = 0;
  for (let frame = handoverStart; frame < handoverEnd; frame += 1) {
    const source = attack[frame] ?? 0;
    const carriedLeft = left[frame] ?? 0;
    const carriedRight = right[frame] ?? 0;
    crossEnergy +=
      source * (balanceLeft * carriedLeft + balanceRight * carriedRight);
    sampleEnergy += source * source * balanceEnergy;
    synthEnergy += carriedLeft * carriedLeft + carriedRight * carriedRight;
  }
  const coherence =
    sampleEnergy > 0 && synthEnergy > 0
      ? crossEnergy / Math.sqrt(sampleEnergy * synthEnergy)
      : 0;
  /*
   * Two deterministic corrections make the handover level-flat anyway.
   *
   * A recording's polarity is arbitrary — a note and its inverse are the
   * same sound — so the sampled layer is inverted whenever it would cancel,
   * which turns every handover constructive. What remains is then a
   * predictable bump of at most 3 dB, and dividing both weights by the
   * factor the measured coherence implies removes it exactly. That factor
   * is 1 at both ends of the crossfade, so neither boundary can step, and
   * it never exceeds 1, so it can only attenuate: it cannot lift the note
   * into the limiter or amplify the sustain.
   */
  const polarity = coherence < 0 ? -1 : 1;
  const alignedCoherence = Math.min(Math.abs(coherence), 1);

  /*
   * Crossfade weights and the decay correction, computed once per note.
   * `correction` is applied in full across the attack window and unwound
   * log-linearly to unity by the centre of the seam window — which is
   * exactly the crossfade midpoint — so the handover level is exactly
   * `seamGain` however the two decays differ.
   */
  const correctionStart = (attackStart + attackEnd) / 2;
  const correctionEnd = (matchStart + matchEnd) / 2;
  const correctionSpan = Math.max(1, correctionEnd - correctionStart);
  const synthGain = new Float64Array(layerFrames);
  const sampleGain = new Float64Array(layerFrames);
  for (let frame = 0; frame < layerFrames; frame += 1) {
    const unwind =
      frame <= correctionStart
        ? 1
        : frame >= correctionEnd
          ? 0
          : 1 - (frame - correctionStart) / correctionSpan;
    const level = seamGain * correction ** unwind;
    if (frame < soloFrames) {
      synthGain[frame] = 0;
      sampleGain[frame] = level * polarity;
      continue;
    }
    const phase = ((frame - soloFrames) / crossfadeFrames) * (Math.PI / 2);
    const coherent =
      1 / Math.sqrt(1 + alignedCoherence * Math.sin(2 * phase));
    synthGain[frame] = Math.sin(phase) * coherent;
    sampleGain[frame] = Math.cos(phase) * level * polarity * coherent;
  }

  /*
   * Peak limit. The ceiling never falls below the synthesized note's own
   * peak, so the guard can only scale the added layer — it never attenuates
   * the sustain the rest of the note depends on.
   *
   * The guard is an envelope, not a scalar. A recorded fortissimo bass
   * strike has a far higher crest factor than the model does, and scaling
   * the whole layer to tame one sample would leave the handover several
   * decibels below the sustain it hands to — an audible swell at the seam.
   * The envelope instead ducks only around the offending sample and slews
   * back at a fixed decibels-per-second rate, so the seam stays matched and
   * the gain never moves fast enough to click.
   */
  let synthPeak = 0;
  for (let frame = 0; frame < frameCount; frame += 1) {
    const magnitude = Math.max(
      Math.abs(left[frame] ?? 0),
      Math.abs(right[frame] ?? 0),
    );
    if (magnitude > synthPeak) synthPeak = magnitude;
  }
  const ceiling = Math.max(policy.peakCeiling, synthPeak);
  const guard = new Float64Array(layerFrames);
  for (let frame = 0; frame < layerFrames; frame += 1) {
    let allowed = 1;
    const weight = sampleGain[frame] ?? 0;
    const faded = synthGain[frame] ?? 0;
    const source = attack[frame] ?? 0;
    for (const [channel, balance] of [
      [left, balanceLeft],
      [right, balanceRight],
    ] as const) {
      const added = weight * source * balance;
      if (added === 0) continue;
      const carried = faded * (channel[frame] ?? 0);
      const bound =
        added > 0 ? (ceiling - carried) / added : (-ceiling - carried) / added;
      if (bound < allowed) allowed = bound;
    }
    guard[frame] = allowed > 0 ? allowed : 0;
  }
  /*
   * Two slew passes, each of which can only lower a value, so the per-frame
   * bound above still holds everywhere: backwards so the duck arrives before
   * the sample it protects against, forwards so the recovery is just as
   * gradual.
   */
  const slew = 10 ** (policy.peakGuardSlewDecibelsPerSecond / (20 * sampleRateHz));
  for (let frame = layerFrames - 2; frame >= 0; frame -= 1) {
    const next = (guard[frame + 1] ?? 1) * slew;
    if (next < (guard[frame] ?? 1)) guard[frame] = next;
  }
  for (let frame = 1; frame < layerFrames; frame += 1) {
    const previous = (guard[frame - 1] ?? 1) * slew;
    if (previous < (guard[frame] ?? 1)) guard[frame] = previous;
  }

  for (let frame = 0; frame < layerFrames; frame += 1) {
    const weight = (sampleGain[frame] ?? 0) * (guard[frame] ?? 0);
    const faded = synthGain[frame] ?? 0;
    const source = attack[frame] ?? 0;
    left[frame] = faded * (left[frame] ?? 0) + weight * source * balanceLeft;
    right[frame] = faded * (right[frame] ?? 0) + weight * source * balanceRight;
  }
  return true;
}

const PAGE_BYTES = 65_536;

/**
 * Grow the module memory so `[offset, offset + bytes)` is addressable.
 * Growth detaches previous buffer views, so callers re-read `memory.buffer`
 * after every call.
 */
function ensureCapacity(
  memory: WebAssembly.Memory,
  offset: number,
  bytes: number,
): void {
  const needed = offset + bytes - memory.buffer.byteLength;
  if (needed > 0) {
    memory.grow(Math.ceil(needed / PAGE_BYTES));
  }
}

let rendererPromise: Promise<ConcertGrandRenderer> | null = null;

function requireExportedFunction(
  exports: Readonly<Record<string, unknown>>,
  name: string,
): CallableFunction {
  const candidate = exports[name];
  if (typeof candidate !== "function") {
    throw new Error(`DSP_WASM_EXPORT_MISSING:${name}`);
  }
  return candidate;
}

async function instantiate(): Promise<ConcertGrandRenderer> {
  const bytes = decodeWasmBytes();
  const { instance } = await WebAssembly.instantiate(bytes, {});
  const rawExports: Readonly<Record<string, unknown>> = instance.exports;
  const memoryCandidate = rawExports["memory"];
  if (!(memoryCandidate instanceof WebAssembly.Memory)) {
    throw new Error("DSP_WASM_EXPORT_MISSING:memory");
  }
  const heapBaseCandidate = rawExports["__heap_base"];
  const exports: ConcertGrandExports = {
    memory: memoryCandidate,
    ...(heapBaseCandidate instanceof WebAssembly.Global
      ? { __heap_base: heapBaseCandidate }
      : {}),
    /*
     * Wasm export signatures are not statically typed; each callable is
     * runtime-verified above and asserted to its concrete numeric signature.
     */
    cg_note_frames: requireExportedFunction(
      rawExports,
      "cg_note_frames",
    ) as ConcertGrandExports["cg_note_frames"],
    cg_render: requireExportedFunction(
      rawExports,
      "cg_render",
    ) as ConcertGrandExports["cg_render"],
    an_spectrum: requireExportedFunction(
      rawExports,
      "an_spectrum",
    ) as ConcertGrandExports["an_spectrum"],
    an_notes: requireExportedFunction(
      rawExports,
      "an_notes",
    ) as ConcertGrandExports["an_notes"],
    an_chroma: requireExportedFunction(
      rawExports,
      "an_chroma",
    ) as ConcertGrandExports["an_chroma"],
  };
  const memory = exports.memory;
  /* Scratch region starts past the module's own data and shadow stack. */
  const heapBase =
    typeof exports.__heap_base?.value === "number"
      ? exports.__heap_base.value
      : memory.buffer.byteLength;
  const scratchBase = Math.ceil((heapBase + 1_024) / 16) * 16;

  const renderSynthesizedNote = (
    midiPitch: number,
    velocity: number,
    sampleRateHz: number,
    maxSeconds?: number,
  ): RenderedNotePcm | null => {
    const natural = exports.cg_note_frames(midiPitch, sampleRateHz);
    if (natural <= 0) return null;
    const capacity =
      maxSeconds === undefined || !Number.isFinite(maxSeconds)
        ? natural
        : Math.min(natural, Math.max(1, Math.round(maxSeconds * sampleRateHz)));
    const channelBytes = capacity * 4;
    const leftPointer = scratchBase;
    const rightPointer = scratchBase + channelBytes;
    ensureCapacity(memory, scratchBase, channelBytes * 2);
    const written = exports.cg_render(
      midiPitch,
      velocity,
      sampleRateHz,
      leftPointer,
      rightPointer,
      capacity,
    );
    if (written <= 0) return null;
    /* Copy out: the scratch region is reused by the next render. */
    const left = new Float32Array(written);
    const right = new Float32Array(written);
    left.set(new Float32Array(memory.buffer, leftPointer, written));
    right.set(new Float32Array(memory.buffer, rightPointer, written));
    return Object.freeze({
      sampleRateHz,
      frameCount: written,
      left,
      right,
    });
  };

  const renderNote = (
    midiPitch: number,
    velocity: number,
    sampleRateHz: number,
    maxSeconds?: number,
  ): RenderedNotePcm | null => {
    const synthesized = renderSynthesizedNote(
      midiPitch,
      velocity,
      sampleRateHz,
      maxSeconds,
    );
    if (synthesized === null) return null;
    applyAttackLayer(
      synthesized.left,
      synthesized.right,
      synthesized.frameCount,
      midiPitch,
      velocity,
      sampleRateHz,
    );
    if (maxSeconds === undefined || !Number.isFinite(maxSeconds)) {
      return synthesized;
    }
    const wanted = Math.max(1, Math.round(maxSeconds * sampleRateHz));
    if (wanted >= synthesized.frameCount) return synthesized;
    /* Fade the truncation over ~15 ms so the cut cannot click. */
    const fade = Math.min(Math.round(0.015 * sampleRateHz), wanted);
    const left = synthesized.left.slice(0, wanted);
    const right = synthesized.right.slice(0, wanted);
    for (let index = 0; index < fade; index += 1) {
      const gain = (fade - index) / fade;
      const at = wanted - fade + index;
      left[at] = (left[at] ?? 0) * gain;
      right[at] = (right[at] ?? 0) * gain;
    }
    return Object.freeze({
      sampleRateHz: synthesized.sampleRateHz,
      frameCount: wanted,
      left,
      right,
    });
  };

  const MAX_DETECTED_NOTES = 12;

  const analyzeWindow = (
    samples: Float32Array,
    sampleRateHz: number,
  ): AnalysisFrame | null => {
    const fftSize = samples.length;
    if (
      fftSize < 64 ||
      fftSize > 8_192 ||
      (fftSize & (fftSize - 1)) !== 0 ||
      !Number.isFinite(sampleRateHz) ||
      sampleRateHz <= 0
    ) {
      return null;
    }
    const binCount = fftSize / 2;
    /*
     * Scratch layout: input window, magnitude bins, note triples, chroma —
     * all in the same reusable region past the render scratch.
     */
    const inputPointer = scratchBase;
    const magnitudesPointer = inputPointer + fftSize * 4;
    const notesPointer = magnitudesPointer + binCount * 4;
    const chromaPointer = notesPointer + MAX_DETECTED_NOTES * 3 * 4;
    ensureCapacity(memory, scratchBase, chromaPointer + 12 * 4 - scratchBase);
    new Float32Array(memory.buffer, inputPointer, fftSize).set(samples);
    const bins = exports.an_spectrum(inputPointer, fftSize, magnitudesPointer);
    if (bins !== binCount) return null;
    const noteCount = exports.an_notes(
      magnitudesPointer,
      bins,
      sampleRateHz,
      fftSize,
      notesPointer,
      MAX_DETECTED_NOTES,
    );
    const chromaCount = exports.an_chroma(
      magnitudesPointer,
      bins,
      sampleRateHz,
      fftSize,
      chromaPointer,
    );
    if (chromaCount !== 12 || noteCount < 0) return null;
    const magnitudes = new Float32Array(binCount);
    magnitudes.set(new Float32Array(memory.buffer, magnitudesPointer, binCount));
    const chroma = new Float32Array(12);
    chroma.set(new Float32Array(memory.buffer, chromaPointer, 12));
    const triples = new Float32Array(memory.buffer, notesPointer, noteCount * 3);
    const notes: DetectedNote[] = [];
    for (let index = 0; index < noteCount; index += 1) {
      notes.push(
        Object.freeze({
          midiPitch: triples[index * 3] ?? 0,
          centsDeviation: triples[index * 3 + 1] ?? 0,
          strength: triples[index * 3 + 2] ?? 0,
        }),
      );
    }
    return Object.freeze({
      sampleRateHz,
      fftSize,
      magnitudes,
      notes: Object.freeze(notes),
      chroma,
    });
  };

  return Object.freeze({
    algorithmId: CONCERT_GRAND_RENDERER_ALGORITHM_ID,
    wasmSha256: CONCERT_GRAND_WASM_SHA256,
    attackSamplesSha256: PIANO_ATTACK_SAMPLES_SHA256,
    renderNote,
    renderSynthesizedNote,
    attackSliceFor: selectAttackSlice,
    analyzeWindow,
  });
}

/**
 * Instantiate the module once per page. A rejected instantiation is not
 * cached: a later caller may retry, and the engine surfaces the stable
 * refusal `audio.renderer_unavailable` in the meantime.
 */
export function loadConcertGrandRenderer(): Promise<ConcertGrandRenderer> {
  rendererPromise ??= instantiate().catch((error: unknown) => {
    rendererPromise = null;
    throw error instanceof Error ? error : new Error(String(error));
  });
  return rendererPromise;
}
