/**
 * Host for the embedded Concert Grand DSP module.
 *
 * The wasm payload is checked-in source (`./wasm/concert-grand-wasm.ts`,
 * generated by `scripts/build-dsp.ts` from `dsp/concert-grand`). This module
 * decodes and instantiates it once, owns its linear memory layout, and turns
 * `(midiPitch, velocity, sampleRate)` into freshly copied stereo PCM. Renders
 * are bit-deterministic: the module imports nothing from the host — no clock,
 * no random device, no I/O — so the PCM goldens can pin exact hashes.
 *
 * The rendered note is a HYBRID. Synthesis alone cannot produce the hammer
 * strike of a real instrument, so the first third of a second comes from a
 * recorded Yamaha C5 (`./wasm/piano-attack-samples.ts`) and is crossfaded
 * into the synthesized sustain. The sampled layer is transposed from the
 * nearest recorded key, level- and balance-matched to the synth layer over
 * the crossfade window, and peak-limited; a pitch or velocity outside the
 * recorded set simply renders as pure synthesis. Everything here is a pure
 * function of `(midiPitch, velocity, sampleRateHz)`.
 *
 * Layer position: audio-internal. The engine caches the PCM in Web Audio
 * buffers; no other layer sees this module or the wasm instance.
 */
import {
  CONCERT_GRAND_WASM_BASE64,
  CONCERT_GRAND_WASM_BYTE_LENGTH,
  CONCERT_GRAND_WASM_SHA256,
} from "./wasm/concert-grand-wasm";
import {
  PIANO_ATTACK_SAMPLE_RATE_HZ,
  PIANO_ATTACK_SAMPLES_ATTRIBUTION,
  PIANO_ATTACK_SAMPLES_BASE64,
  PIANO_ATTACK_SAMPLES_BYTE_LENGTH,
  PIANO_ATTACK_SAMPLES_LICENSE,
  PIANO_ATTACK_SAMPLES_SHA256,
  PIANO_ATTACK_SLICE_INDEX,
  type PianoAttackSlice,
} from "./wasm/piano-attack-samples";
import type {
  PhysicalRenderAbiRequestV2,
  PhysicalRenderRefusalCode,
} from "./physical-renderer-contract";

export const CONCERT_GRAND_RENDERER_ALGORITHM_ID =
  "changes.dsp.concert-grand@1";

/*
 * Physically modeled waveguide instruments (jcpe-1miv follow-up, owner
 * direction 2026-08-06): the same embedded wasm module carries an extended
 * Karplus-Strong guitar (dual-polarization strings, dispersion, archtop
 * body modes) behind two amp voicings, and a jet-drive waveguide flute.
 */
export const WAVEGUIDE_GUITAR_CLEAN_ALGORITHM_ID =
  "changes.dsp.waveguide-guitar-clean@1";
export const WAVEGUIDE_GUITAR_DRIVE_ALGORITHM_ID =
  "changes.dsp.waveguide-guitar-drive@1";
export const WAVEGUIDE_FLUTE_ALGORITHM_ID = "changes.dsp.waveguide-flute@1";
export const WAVEGUIDE_FLUTE_V2_ALGORITHM_ID =
  "changes.dsp.waveguide-flute@2";
export const WAVEGUIDE_CLARINET_ALGORITHM_ID =
  "changes.dsp.waveguide-clarinet@1";
export const WAVEGUIDE_CLARINET_V2_ALGORITHM_ID =
  "changes.dsp.waveguide-clarinet@2";
export const PLUCKED_ARCHTOP_V2_ALGORITHM_ID =
  "changes.dsp.plucked-archtop@2";
export const PLUCKED_ELECTRIC_V2_ALGORITHM_ID =
  "changes.dsp.plucked-electric@2";
export const PLUCKED_DREADNOUGHT_ALGORITHM_ID =
  "changes.dsp.plucked-dreadnought@1";
export const PLUCKED_UKULELE_ALGORITHM_ID =
  "changes.dsp.plucked-ukulele@1";
export const PLUCKED_UPRIGHT_BASS_ALGORITHM_ID =
  "changes.dsp.plucked-upright-bass@1";
const PLK2_UPRIGHT_BASS_PACK_INDEX = 4;

export type WindAttackArticulation = "legato" | "tongued";

export type PhysicalPluckedStemRenderResult = Readonly<{
  sampleRateHz: number;
  frameCount: number;
  left: Float32Array;
  right: Float32Array;
  stateOutput: Uint8Array;
}>;

export type WaveguideRenderer = Readonly<{
  algorithmId: string;
  wasmSha256: string;
  /**
   * Render one note; same contract shape as the Concert Grand's
   * `renderNote`. Null only for an out-of-contract request.
   */
  renderNote: (
    midiPitch: number,
    velocity: number,
    sampleRateHz: number,
    maxSeconds?: number,
    variationSlot?: number,
    windArticulation?: WindAttackArticulation,
  ) => RenderedNotePcm | null;
  /**
   * One simultaneous plucked-instrument chord through one shared body and
   * amplifier. Present only when the embedded WASM carries the chord ABI.
   */
  renderChord?: (
    midiPitches: readonly number[],
    velocities: readonly number[],
    sampleRateHz: number,
    maxSeconds?: number,
  ) => RenderedNotePcm | null;
  /**
   * Bit-identical chord preparation through bounded WASM chunks. Each
   * incomplete chunk yields one browser macrotask; physical state remains in
   * a checksummed caller-owned linear-memory image rather than a singleton.
   */
  renderChordCooperatively?: (
    midiPitches: readonly number[],
    velocities: readonly number[],
    sampleRateHz: number,
    maxSeconds?: number,
  ) => Promise<RenderedNotePcm | null>;
  /** Stateful physical phrase path, present only on clarinet v2. */
  renderPhraseSegment?: (
    midiPitch: number,
    velocity: number,
    sampleRateHz: number,
    frameCount: number,
    stateInput: Uint8Array | null,
    variationSlot: number,
    windArticulation: WindAttackArticulation,
  ) => PhysicalClarinetPhraseRenderResult | null;
  /**
   * Explicit retained plucked-instrument stem. Unlike `renderNote`, this path
   * carries all strings, body modes, contact, amp, and radiation history
   * between bounded segments; `reset` is the deterministic Stop operation.
   */
  renderPluckedStemSegment?: (
    midiPitch: number | null,
    velocity: number,
    sampleRateHz: number,
    frameCount: number,
    stateInput: Uint8Array | null,
    reset: boolean,
  ) => PhysicalPluckedStemRenderResult | null;
}>;

/**
 * The reviewed crossfade design. The sampled attack owns the note outright
 * until `sampleOnlySeconds`; a cosine/sine crossfade then hands the note to
 * the synthesized sustain by `crossfadeEndSeconds`.
 *
 * Equal power alone would be the wrong law. It assumes the two layers are
 * uncorrelated, and these two are not: they are the same note, they both
 * begin at the onset, and the build-time stretch correction deliberately
 * puts their fundamentals on one frequency, so their relative phase is fixed
 * for the whole handover. Measured across the keyboard that correlation runs
 * from -0.97 to +0.99, and where it is negative the two layers cancel — a
 * hole up to 14.4 dB deep in the middle of the crossfade. The weights are
 * therefore corrected for the coherence the note actually has; see
 * `applyAttackLayer`.
 */
export const PIANO_ATTACK_LAYER_POLICY = Object.freeze({
  id: "changes.dsp.piano-attack-layer.v1",
  attribution: PIANO_ATTACK_SAMPLES_ATTRIBUTION,
  license: PIANO_ATTACK_SAMPLES_LICENSE,
  payloadSha256: PIANO_ATTACK_SAMPLES_SHA256,
  sampleOnlySeconds: 0.18,
  crossfadeEndSeconds: 0.32,
  /**
   * Level is matched twice: once over the attack the sampled layer owns, and
   * once over the crossfade window it hands off in. A recorded string and a
   * modelled one do not decay at quite the same rate, so a single match would
   * either misstate the attack's loudness or step at the seam. The correction
   * interpolates log-linearly in time between the two — the exact shape that
   * turns one exponential decay into another — and is clamped so a badly
   * mismatched pair degrades instead of exploding.
   */
  attackWindowStartSeconds: 0.02,
  attackWindowEndSeconds: 0.18,
  matchWindowStartSeconds: 0.18,
  matchWindowEndSeconds: 0.32,
  maximumDecayCorrectionRatio: 4,
  /** A recorded key is never stretched further than this. */
  maximumTranspositionSemitones: 3,
  /** The sampled layer is ducked before the hybrid can exceed this. */
  peakCeiling: 0.945,
  /** How fast that duck may move, so it can never be heard as a step. */
  peakGuardSlewDecibelsPerSecond: 60,
  interpolation: "catmull-rom",
} as const);

export type RenderedNotePcm = Readonly<{
  sampleRateHz: number;
  frameCount: number;
  left: Float32Array<ArrayBuffer>;
  right: Float32Array<ArrayBuffer>;
}>;

export type DetectedNote = Readonly<{
  midiPitch: number;
  centsDeviation: number;
  strength: number;
}>;

export type AnalysisFrame = Readonly<{
  sampleRateHz: number;
  fftSize: number;
  /** Hann-windowed magnitude spectrum, fftSize/2 bins. */
  magnitudes: Float32Array<ArrayBuffer>;
  /** Harmonically grouped fundamentals, strongest first. */
  notes: readonly DetectedNote[];
  /** Pitch-class energy fold (C first), unit-maximum normalized. */
  chroma: Float32Array<ArrayBuffer>;
}>;

export type PhysicalModalState = Readonly<{ x: number; y: number }>;
export type PhysicalEnergyLedger = Readonly<{
  initialEnergy: number;
  excitationWork: number;
  finalEnergy: number;
  /** Independently accumulated per-sample loss-coefficient absorption. */
  dampingLoss: number;
  /** initial + work - final - dampingLoss; a genuine closure check. */
  residual: number;
}>;
export type PhysicalModalRenderResult = RenderedNotePcm & Readonly<{
  state: PhysicalModalState;
  energy: PhysicalEnergyLedger;
  limiterEngagements: number;
}>;
export type PhysicalReedSolveResult = Readonly<{
  junctionPressure: number;
  volumeFlow: number;
  nonlinearIterations: number;
  fallbackBisections: number;
}>;
export type PhysicalClarinetReedState = Readonly<{
  displacementM: number;
  velocityMPerS: number;
}>;
export type PhysicalClarinetReedStepResult = Readonly<{
  state: PhysicalClarinetReedState;
  signedVolumeFlowM3PerS: number;
  collisionLossJ: number;
  mechanicalEnergyBeforeJ: number;
  mechanicalEnergyAfterJ: number;
  tongueForceN: number;
  contact: boolean;
}>;
export type PhysicalClarinetPhraseRenderResult = RenderedNotePcm & Readonly<{
  stateOutput: Uint8Array<ArrayBuffer>;
}>;

export type ConcertGrandRenderer = Readonly<{
  algorithmId: typeof CONCERT_GRAND_RENDERER_ALGORITHM_ID;
  wasmSha256: string;
  attackSamplesSha256: string;
  /**
   * Render one note: the recorded attack crossfaded into the synthesized
   * sustain. Synchronous and pure after instantiation; returns null only for
   * an out-of-contract request (pitch outside 21..108, velocity outside
   * 1..127, unsupported sample rate). A note the sample corpus cannot serve
   * still renders — as pure synthesis.
   */
  renderNote: (
    midiPitch: number,
    velocity: number,
    sampleRateHz: number,
    /**
     * Optional ceiling on the rendered length, seconds. A performance holds
     * most notes for a fraction of their natural decay, and rendering the
     * full eight-second bass tail only to gate it off after half a second
     * costs more than an order of magnitude of the work. The tail is trimmed
     * with a short fade so a truncated render cannot click.
     */
    maxSeconds?: number,
  ) => RenderedNotePcm | null;
  /**
   * The same note with the sampled attack layer withheld. Evidence surface
   * only: it exists so a test can prove the layer changes the tone, and the
   * engine never calls it.
   */
  renderSynthesizedNote: (
    midiPitch: number,
    velocity: number,
    sampleRateHz: number,
  ) => RenderedNotePcm | null;
  /**
   * The recorded slice `renderNote` would use, or null when the request
   * falls outside the sampled set. Evidence surface only.
   */
  attackSliceFor: (
    midiPitch: number,
    velocity: number,
  ) => PianoAttackSlice | null;
  /**
   * Analyze one time-domain window: windowed FFT, spectral-peak note
   * detection with harmonic grouping, and a chroma fold. `samples.length`
   * must be a power of two in 64..8192. Null on an out-of-contract request.
   */
  analyzeWindow: (
    samples: Float32Array,
    sampleRateHz: number,
  ) => AnalysisFrame | null;
  /** Validate an ABI-v2 layout inside the Rust/WASM safety boundary. */
  validatePhysicalAbiV2: (
    request: PhysicalRenderAbiRequestV2,
    linearMemoryBytes: number,
  ) => PhysicalRenderRefusalCode | null;
  /** Render a passive shared mode with explicit state handoff and energy. */
  renderPhysicalModalV2: (request: Readonly<{
    sampleRateHz: 44_100 | 48_000 | 96_000;
    frequencyHz: number;
    dampingPerSecond: number;
    excitation: number;
    initialState: PhysicalModalState;
    frameCount: number;
  }>) => PhysicalModalRenderResult | null;
  solvePhysicalReedV2: (request: Readonly<{
    mouthPressure: number;
    borePressure: number;
    opening: number;
    stiffness: number;
    boreImpedance: number;
  }>) => PhysicalReedSolveResult | null;
  stepPhysicalClarinetReedV2: (request: Readonly<{
    dtSeconds: number;
    state: PhysicalClarinetReedState;
    mouthPressurePa: number;
    mouthpiecePressurePa: number;
    massKg: number;
    dampingNsPerM: number;
    stiffnessNPerM: number;
    equilibriumOpeningM: number;
    effectiveAreaM2: number;
    channelWidthM: number;
    airDensityKgPerM3: number;
    tongueContact: number;
  }>) => PhysicalClarinetReedStepResult | null;
}>;

type ConcertGrandExports = Readonly<{
  memory: WebAssembly.Memory;
  __heap_base?: WebAssembly.Global;
  cg_note_frames: (midi: number, sampleRate: number) => number;
  cg_render: (
    midi: number,
    velocity: number,
    sampleRate: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  an_spectrum: (input: number, frames: number, magnitudes: number) => number;
  an_notes: (
    magnitudes: number,
    bins: number,
    sampleRate: number,
    fftSize: number,
    out: number,
    maxNotes: number,
  ) => number;
  an_chroma: (
    magnitudes: number,
    bins: number,
    sampleRate: number,
    fftSize: number,
    out: number,
  ) => number;
  gtr_note_frames: (midi: number, sampleRate: number) => number;
  gtr_render: (
    midi: number,
    velocity: number,
    sampleRate: number,
    profile: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  plk2_note_frames: (pack: number, midi: number, sampleRate: number) => number;
  plk2_render: (
    pack: number,
    midi: number,
    velocity: number,
    sampleRate: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  plk2_render_chord?: (
    pack: number,
    midis: number,
    velocities: number,
    noteCount: number,
    sampleRate: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  plk2_chord_session_state_max_bytes?: () => number;
  plk2_chord_session_max_steps?: (outputCapacity: number) => number;
  plk2_chord_session_init?: (
    pack: number,
    midis: number,
    velocities: number,
    noteCount: number,
    sampleRate: number,
    maxFrames: number,
    state: number,
    stateCapacity: number,
  ) => number;
  plk2_chord_session_step?: (
    state: number,
    stateBytes: number,
    left: number,
    right: number,
    outputCapacity: number,
  ) => number;
  plk2_chord_runtime_init?: (
    pack: number,
    midis: number,
    velocities: number,
    noteCount: number,
    sampleRate: number,
    maxFrames: number,
  ) => number;
  plk2_chord_runtime_max_steps?: (outputCapacity: number) => number;
  plk2_chord_runtime_step?: (
    handle: number,
    left: number,
    right: number,
    outputCapacity: number,
  ) => number;
  plk2_chord_runtime_reset?: (handle: number) => number;
  plk2_stem_state_max_bytes?: () => number;
  plk2_stem_render_max_frames?: () => number;
  plk2_stem_init?: (
    pack: number,
    sampleRate: number,
    state: number,
    stateCapacity: number,
  ) => number;
  plk2_stem_render?: (
    state: number,
    stateBytes: number,
    midi: number,
    velocity: number,
    eventFlags: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  flt_note_frames: (midi: number, sampleRate: number) => number;
  flt_render: (
    midi: number,
    velocity: number,
    sampleRate: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  flt_render_seeded: (
    midi: number,
    velocity: number,
    sampleRate: number,
    variationSlot: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  flt_render_expressive: (
    midi: number,
    velocity: number,
    sampleRate: number,
    variationSlot: number,
    articulation: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  flt2_note_frames: (midi: number, sampleRate: number) => number;
  flt2_render: (
    midi: number,
    velocity: number,
    sampleRate: number,
    variationSlot: number,
    articulation: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  clr_note_frames: (midi: number, sampleRate: number) => number;
  clr_render: (
    midi: number,
    velocity: number,
    sampleRate: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  clr_render_seeded: (
    midi: number,
    velocity: number,
    sampleRate: number,
    variationSlot: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  clr_render_expressive: (
    midi: number,
    velocity: number,
    sampleRate: number,
    variationSlot: number,
    articulation: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  clr_render_v2: (
    midi: number, velocity: number, sampleRate: number, variationSlot: number,
    articulation: number, left: number, right: number, maxFrames: number,
  ) => number;
  clr_state_max_bytes_v2: () => number;
  clr_state_fixed_bytes_v2: () => number;
  clr_render_phrase_v2: (
    midi: number, velocity: number, sampleRate: number, variationSlot: number,
    articulation: number, left: number, right: number, maxFrames: number,
    stateInput: number, stateInputBytes: number, stateOutput: number,
    stateOutputCapacity: number,
  ) => number;
  phs_validate_v2: (
    abiVersion: number,
    requestByteLength: number,
    descriptorOffset: number,
    descriptorCount: number,
    controlPointOffset: number,
    controlPointCount: number,
    outputLeftOffset: number,
    outputRightOffset: number,
    outputCapacityFrames: number,
    stateInputOffset: number,
    stateInputByteLength: number,
    stateOutputOffset: number,
    stateOutputCapacityBytes: number,
    linearMemoryBytes: number,
  ) => number;
  phs_modal_render_v2: (
    sampleRate: number,
    frequencyHz: number,
    dampingPerSecond: number,
    excitation: number,
    initialX: number,
    initialY: number,
    left: number,
    right: number,
    frames: number,
    stateOutput: number,
    energyOutput: number,
  ) => number;
  phs_reed_solve_v2: (
    mouthPressure: number,
    borePressure: number,
    opening: number,
    stiffness: number,
    boreImpedance: number,
    output: number,
  ) => number;
  phs_clarinet_reed_step_v2: (
    dtSeconds: number, displacementM: number, velocityMPerS: number,
    mouthPressurePa: number, mouthpiecePressurePa: number, massKg: number,
    dampingNsPerM: number, stiffnessNPerM: number, equilibriumOpeningM: number,
    effectiveAreaM2: number, channelWidthM: number, airDensityKgPerM3: number,
    tongueContact: number, output: number,
  ) => number;
}>;

function decodeWasmBytes(): Uint8Array<ArrayBuffer> {
  const decoded = atob(CONCERT_GRAND_WASM_BASE64);
  if (decoded.length !== CONCERT_GRAND_WASM_BYTE_LENGTH) {
    throw new Error("DSP_WASM_PAYLOAD_LENGTH_MISMATCH");
  }
  const bytes = new Uint8Array(decoded.length);
  for (let index = 0; index < decoded.length; index += 1) {
    bytes[index] = decoded.charCodeAt(index);
  }
  return bytes;
}

/* ------------------------------------------------------------------ *
 * Recorded attack layer                                               *
 * ------------------------------------------------------------------ */

let attackSampleStore: Int16Array<ArrayBuffer> | null = null;
let attackSampleStoreRefused = false;

/**
 * Decode the embedded PCM once, on the first note that needs it. The payload
 * is raw single-channel 16-bit little-endian PCM, and each pair of bytes is
 * recombined explicitly rather than aliased through a typed-array view: the
 * result is identical on a big-endian host, and the decode never depends on
 * a browser media API.
 */
function attackSamples(): Int16Array<ArrayBuffer> | null {
  if (attackSampleStore !== null) return attackSampleStore;
  if (attackSampleStoreRefused) return null;
  try {
    const decoded = atob(PIANO_ATTACK_SAMPLES_BASE64);
    if (
      decoded.length !== PIANO_ATTACK_SAMPLES_BYTE_LENGTH ||
      decoded.length % 2 !== 0
    ) {
      throw new Error("DSP_ATTACK_PAYLOAD_LENGTH_MISMATCH");
    }
    const samples = new Int16Array(decoded.length / 2);
    for (let index = 0; index < samples.length; index += 1) {
      const low = decoded.charCodeAt(index * 2) & 0xff;
      const high = decoded.charCodeAt(index * 2 + 1) & 0xff;
      samples[index] = (((high << 8) | low) << 16) >> 16;
    }
    attackSampleStore = samples;
    return samples;
  } catch {
    /* A corrupt payload demotes the instrument to pure synthesis, never a
     * failed note. */
    attackSampleStoreRefused = true;
    return null;
  }
}

/**
 * The recorded slice that serves this request: the velocity bucket that
 * contains the velocity, and within it the recorded key nearest the target.
 * Ties resolve to the higher key so the transposition runs downward, which
 * consumes less of the stored slice.
 */
function selectAttackSlice(
  midiPitch: number,
  velocity: number,
): PianoAttackSlice | null {
  let best: PianoAttackSlice | null = null;
  let bestDistance = Number.POSITIVE_INFINITY;
  for (const slice of PIANO_ATTACK_SLICE_INDEX) {
    if (velocity < slice.lowVelocity || velocity > slice.highVelocity) continue;
    const distance = Math.abs(slice.midiPitch - midiPitch);
    if (distance <= bestDistance) {
      bestDistance = distance;
      best = slice;
    }
  }
  if (
    best === null ||
    bestDistance > PIANO_ATTACK_LAYER_POLICY.maximumTranspositionSemitones
  ) {
    return null;
  }
  return best;
}

/**
 * Whether a slice's whole PCM range is addressable inside the decoded
 * payload. The generator guarantees this, but that guarantee lives in a
 * generated file, and reading outside the range is not a benign failure: a
 * partial overrun truncates the layer to silence mid-crossfade and a
 * negative offset plays a neighbouring recording, both audible. Checking it
 * here means a malformed entry degrades to pure synthesis instead.
 */
function attackSliceIsAddressable(
  store: Int16Array,
  slice: PianoAttackSlice,
): boolean {
  const base = slice.byteOffset / 2;
  return (
    Number.isSafeInteger(base) &&
    base >= 0 &&
    Number.isSafeInteger(slice.frameCount) &&
    slice.frameCount >= 2 &&
    base + slice.frameCount <= store.length
  );
}

/**
 * Transpose one slice onto the requested pitch and output rate with a
 * Catmull-Rom kernel. The kernel is a fixed cubic over four neighbours: no
 * table, no filter state, no branch on data, so the same request yields the
 * same floats on every host.
 */
function transposeAttackSlice(
  store: Int16Array,
  slice: PianoAttackSlice,
  midiPitch: number,
  sampleRateHz: number,
  frames: number,
): Float32Array<ArrayBuffer> {
  const out = new Float32Array(frames);
  const base = slice.byteOffset / 2;
  const last = slice.frameCount - 1;
  /*
   * The recorded key is stretch-tuned; `tuningCents` is how far it sits from
   * 12-TET, so subtracting it lands the transposed attack on the same pitch
   * the synthesized sustain holds and the two layers do not beat.
   */
  const semitones =
    midiPitch - slice.midiPitch - slice.tuningCents / 100;
  const step =
    2 ** (semitones / 12) * (PIANO_ATTACK_SAMPLE_RATE_HZ / sampleRateHz);
  const at = (offset: number): number => {
    const clamped = offset < 0 ? 0 : offset > last ? last : offset;
    return (store[base + clamped] ?? 0) / 32_768;
  };
  for (let frame = 0; frame < frames; frame += 1) {
    const position = frame * step;
    const index = Math.floor(position);
    if (index >= last) break;
    const t = position - index;
    const p0 = at(index - 1);
    const p1 = at(index);
    const p2 = at(index + 1);
    const p3 = at(index + 2);
    out[frame] =
      0.5 *
      (2 * p1 +
        (p2 - p0) * t +
        (2 * p0 - 5 * p1 + 4 * p2 - p3) * t * t +
        (3 * p1 - p0 - 3 * p2 + p3) * t * t * t);
  }
  return out;
}

function windowRms(
  channel: Float32Array,
  start: number,
  end: number,
): number {
  if (end <= start) return 0;
  let total = 0;
  for (let frame = start; frame < end; frame += 1) {
    const value = channel[frame] ?? 0;
    total += value * value;
  }
  return Math.sqrt(total / (end - start));
}

/**
 * Fold the recorded attack into an already-rendered synthesized note, in
 * place. Returns false when the corpus cannot serve the request, in which
 * case the synthesized note is left exactly as it was.
 */
function applyAttackLayer(
  left: Float32Array,
  right: Float32Array,
  frameCount: number,
  midiPitch: number,
  velocity: number,
  sampleRateHz: number,
): boolean {
  const slice = selectAttackSlice(midiPitch, velocity);
  if (slice === null) return false;
  const store = attackSamples();
  if (store === null) return false;
  if (!attackSliceIsAddressable(store, slice)) return false;

  const policy = PIANO_ATTACK_LAYER_POLICY;
  const layerFrames = Math.min(
    Math.round(policy.crossfadeEndSeconds * sampleRateHz),
    frameCount,
  );
  const soloFrames = Math.min(
    Math.round(policy.sampleOnlySeconds * sampleRateHz),
    layerFrames,
  );
  const crossfadeFrames = layerFrames - soloFrames;
  if (crossfadeFrames <= 0) return false;

  const attack = transposeAttackSlice(
    store,
    slice,
    midiPitch,
    sampleRateHz,
    layerFrames,
  );

  /*
   * Two matching windows. The seam window fixes the handover level exactly;
   * the attack window fixes how loud the recorded hammer strike sits inside
   * the note, which is what carries the instrument's velocity law.
   */
  const attackStart = Math.min(
    Math.round(policy.attackWindowStartSeconds * sampleRateHz),
    layerFrames,
  );
  const attackEnd = Math.min(
    Math.round(policy.attackWindowEndSeconds * sampleRateHz),
    layerFrames,
  );
  const matchStart = Math.min(
    Math.round(policy.matchWindowStartSeconds * sampleRateHz),
    layerFrames,
  );
  const matchEnd = Math.min(
    Math.round(policy.matchWindowEndSeconds * sampleRateHz),
    layerFrames,
  );
  const sampleSeamRms = windowRms(attack, matchStart, matchEnd);
  const sampleAttackRms = windowRms(attack, attackStart, attackEnd);
  if (!(sampleSeamRms > 1e-9) || !(sampleAttackRms > 1e-9)) return false;

  const synthSeamLeft = windowRms(left, matchStart, matchEnd);
  const synthSeamRight = windowRms(right, matchStart, matchEnd);
  const synthSeamRms = Math.sqrt(
    (synthSeamLeft * synthSeamLeft + synthSeamRight * synthSeamRight) / 2,
  );
  const synthAttackRms = Math.sqrt(
    (windowRms(left, attackStart, attackEnd) ** 2 +
      windowRms(right, attackStart, attackEnd) ** 2) /
      2,
  );
  if (!(synthSeamRms > 1e-9) || !(synthAttackRms > 1e-9)) return false;

  /* Stereo placement comes from the synth layer, measured at the seam. */
  const balanceLeft = synthSeamLeft / synthSeamRms;
  const balanceRight = synthSeamRight / synthSeamRms;

  /*
   * The handover window: the middle half of the seam window, which is where
   * the two layers actually overlap — the product of the crossfade weights
   * peaks at the centre and vanishes at both ends. Both the level the note
   * hands over at and the coherence correction below are measured here
   * rather than over the whole seam. A recorded string and a modelled one
   * do not decay at the same rate, so an RMS averaged over the full seam is
   * dominated by whichever layer is loudest at its start and can leave the
   * two mismatched by several decibels at the instant they cross.
   */
  const handoverRadius = Math.max(1, Math.round((matchEnd - matchStart) / 4));
  const handoverCentre = Math.round((matchStart + matchEnd) / 2);
  const handoverStart = Math.max(0, handoverCentre - handoverRadius);
  const handoverEnd = Math.min(layerFrames, handoverCentre + handoverRadius);
  const sampleHandoverRms = windowRms(attack, handoverStart, handoverEnd);
  const synthHandoverRms = Math.sqrt(
    (windowRms(left, handoverStart, handoverEnd) ** 2 +
      windowRms(right, handoverStart, handoverEnd) ** 2) /
      2,
  );
  if (!(sampleHandoverRms > 1e-9) || !(synthHandoverRms > 1e-9)) return false;

  const seamGain = synthHandoverRms / sampleHandoverRms;
  const rawAttackGain = synthAttackRms / sampleAttackRms;
  const maximum = policy.maximumDecayCorrectionRatio;
  const correction = Math.min(
    maximum,
    Math.max(1 / maximum, rawAttackGain / seamGain),
  );

  /*
   * How much of the two layers is literally the same waveform. A
   * cosine/sine pair only holds the level constant when this is zero; at -1
   * the layers annihilate at the midpoint, and half the keyboard measures
   * past -0.5.
   */
  const balanceEnergy = balanceLeft * balanceLeft + balanceRight * balanceRight;
  let crossEnergy = 0;
  let sampleEnergy = 0;
  let synthEnergy = 0;
  for (let frame = handoverStart; frame < handoverEnd; frame += 1) {
    const source = attack[frame] ?? 0;
    const carriedLeft = left[frame] ?? 0;
    const carriedRight = right[frame] ?? 0;
    crossEnergy +=
      source * (balanceLeft * carriedLeft + balanceRight * carriedRight);
    sampleEnergy += source * source * balanceEnergy;
    synthEnergy += carriedLeft * carriedLeft + carriedRight * carriedRight;
  }
  const coherence =
    sampleEnergy > 0 && synthEnergy > 0
      ? crossEnergy / Math.sqrt(sampleEnergy * synthEnergy)
      : 0;
  /*
   * Two deterministic corrections make the handover level-flat anyway.
   *
   * A recording's polarity is arbitrary — a note and its inverse are the
   * same sound — so the sampled layer is inverted whenever it would cancel,
   * which turns every handover constructive. What remains is then a
   * predictable bump of at most 3 dB, and dividing both weights by the
   * factor the measured coherence implies removes it exactly. That factor
   * is 1 at both ends of the crossfade, so neither boundary can step, and
   * it never exceeds 1, so it can only attenuate: it cannot lift the note
   * into the limiter or amplify the sustain.
   */
  const polarity = coherence < 0 ? -1 : 1;
  const alignedCoherence = Math.min(Math.abs(coherence), 1);

  /*
   * Crossfade weights and the decay correction, computed once per note.
   * `correction` is applied in full across the attack window and unwound
   * log-linearly to unity by the centre of the seam window — which is
   * exactly the crossfade midpoint — so the handover level is exactly
   * `seamGain` however the two decays differ.
   */
  const correctionStart = (attackStart + attackEnd) / 2;
  const correctionEnd = (matchStart + matchEnd) / 2;
  const correctionSpan = Math.max(1, correctionEnd - correctionStart);
  const synthGain = new Float64Array(layerFrames);
  const sampleGain = new Float64Array(layerFrames);
  for (let frame = 0; frame < layerFrames; frame += 1) {
    const unwind =
      frame <= correctionStart
        ? 1
        : frame >= correctionEnd
          ? 0
          : 1 - (frame - correctionStart) / correctionSpan;
    const level = seamGain * correction ** unwind;
    if (frame < soloFrames) {
      synthGain[frame] = 0;
      sampleGain[frame] = level * polarity;
      continue;
    }
    const phase = ((frame - soloFrames) / crossfadeFrames) * (Math.PI / 2);
    const coherent =
      1 / Math.sqrt(1 + alignedCoherence * Math.sin(2 * phase));
    synthGain[frame] = Math.sin(phase) * coherent;
    sampleGain[frame] = Math.cos(phase) * level * polarity * coherent;
  }

  /*
   * Peak limit. The ceiling never falls below the synthesized note's own
   * peak, so the guard can only scale the added layer — it never attenuates
   * the sustain the rest of the note depends on.
   *
   * The guard is an envelope, not a scalar. A recorded fortissimo bass
   * strike has a far higher crest factor than the model does, and scaling
   * the whole layer to tame one sample would leave the handover several
   * decibels below the sustain it hands to — an audible swell at the seam.
   * The envelope instead ducks only around the offending sample and slews
   * back at a fixed decibels-per-second rate, so the seam stays matched and
   * the gain never moves fast enough to click.
   */
  let synthPeak = 0;
  for (let frame = 0; frame < frameCount; frame += 1) {
    const magnitude = Math.max(
      Math.abs(left[frame] ?? 0),
      Math.abs(right[frame] ?? 0),
    );
    if (magnitude > synthPeak) synthPeak = magnitude;
  }
  const ceiling = Math.max(policy.peakCeiling, synthPeak);
  const guard = new Float64Array(layerFrames);
  for (let frame = 0; frame < layerFrames; frame += 1) {
    let allowed = 1;
    const weight = sampleGain[frame] ?? 0;
    const faded = synthGain[frame] ?? 0;
    const source = attack[frame] ?? 0;
    for (const [channel, balance] of [
      [left, balanceLeft],
      [right, balanceRight],
    ] as const) {
      const added = weight * source * balance;
      if (added === 0) continue;
      const carried = faded * (channel[frame] ?? 0);
      const bound =
        added > 0 ? (ceiling - carried) / added : (-ceiling - carried) / added;
      if (bound < allowed) allowed = bound;
    }
    guard[frame] = allowed > 0 ? allowed : 0;
  }
  /*
   * Two slew passes, each of which can only lower a value, so the per-frame
   * bound above still holds everywhere: backwards so the duck arrives before
   * the sample it protects against, forwards so the recovery is just as
   * gradual.
   */
  const slew = 10 ** (policy.peakGuardSlewDecibelsPerSecond / (20 * sampleRateHz));
  for (let frame = layerFrames - 2; frame >= 0; frame -= 1) {
    const next = (guard[frame + 1] ?? 1) * slew;
    if (next < (guard[frame] ?? 1)) guard[frame] = next;
  }
  for (let frame = 1; frame < layerFrames; frame += 1) {
    const previous = (guard[frame - 1] ?? 1) * slew;
    if (previous < (guard[frame] ?? 1)) guard[frame] = previous;
  }

  for (let frame = 0; frame < layerFrames; frame += 1) {
    const weight = (sampleGain[frame] ?? 0) * (guard[frame] ?? 0);
    const faded = synthGain[frame] ?? 0;
    const source = attack[frame] ?? 0;
    left[frame] = faded * (left[frame] ?? 0) + weight * source * balanceLeft;
    right[frame] = faded * (right[frame] ?? 0) + weight * source * balanceRight;
  }
  return true;
}

const PAGE_BYTES = 65_536;

/**
 * Grow the module memory so `[offset, offset + bytes)` is addressable.
 * Growth detaches previous buffer views, so callers re-read `memory.buffer`
 * after every call.
 */
function ensureCapacity(
  memory: WebAssembly.Memory,
  offset: number,
  bytes: number,
): void {
  const needed = offset + bytes - memory.buffer.byteLength;
  if (needed > 0) {
    memory.grow(Math.ceil(needed / PAGE_BYTES));
  }
}

const COOPERATIVE_CHORD_SCRATCH_OFFSET_BYTES = 16 * 1_024 * 1_024;
const PLK2_CHORD_STEP_PROGRESS = 1;
const PLK2_CHORD_STEP_COMPLETE = 2;
const MAX_COOPERATIVE_CHORD_STATE_BYTES = 1_048_576;
const MAX_COOPERATIVE_CHORD_STEPS = 1_000_000;

type PluckedChordRenderAbi = Readonly<{
  noteFrames: (pack: number, midi: number, sampleRate: number) => number;
  renderChordInto?: (
    pack: number,
    midis: number,
    velocities: number,
    noteCount: number,
    sampleRate: number,
    left: number,
    right: number,
    maxFrames: number,
  ) => number;
  sessionStateMaxBytes?: () => number;
  sessionMaxSteps?: (outputCapacity: number) => number;
  sessionInit?: (
    pack: number,
    midis: number,
    velocities: number,
    noteCount: number,
    sampleRate: number,
    maxFrames: number,
    state: number,
    stateCapacity: number,
  ) => number;
  sessionStep?: (
    state: number,
    stateBytes: number,
    left: number,
    right: number,
    outputCapacity: number,
  ) => number;
  runtimeInit?: (
    pack: number,
    midis: number,
    velocities: number,
    noteCount: number,
    sampleRate: number,
    maxFrames: number,
  ) => number;
  runtimeMaxSteps?: (outputCapacity: number) => number;
  runtimeStep?: (
    handle: number,
    left: number,
    right: number,
    outputCapacity: number,
  ) => number;
  runtimeReset?: (handle: number) => number;
}>;

type PluckedChordRenderFunctions = Pick<
  WaveguideRenderer,
  "renderChord" | "renderChordCooperatively"
>;

type PluckedChordRenderFactoryOptions = Readonly<{
  packIndex: number;
  memory: WebAssembly.Memory;
  scratchBase: number;
  cooperativeScratchBase: number;
  abi: PluckedChordRenderAbi;
  yieldToMacrotask?: () => Promise<void>;
  runExclusive?: <T>(task: () => Promise<T>) => Promise<T>;
}>;

/*
 * PLK2's reviewed physical chord core is band-limited and admitted at 8 kHz.
 * WebAudio buffer sources already resample a buffer whose sample rate differs
 * from the AudioContext, using the browser's native audio thread. Returning
 * that physical-rate buffer avoids reconstructing and copying six redundant
 * 48 kHz frames for every simulated frame on the browser's main thread.
 */
const PLK2_PHYSICAL_BUFFER_SAMPLE_RATE_HZ = 8_000;

function pluckedChordPhysicalSampleRate(
  outputSampleRateHz: number,
): number | null {
  return Number.isFinite(outputSampleRateHz) &&
      outputSampleRateHz >= 8_000 && outputSampleRateHz <= 96_000
    ? PLK2_PHYSICAL_BUFFER_SAMPLE_RATE_HZ
    : null;
}

function validatePluckedChordRequest(
  abi: PluckedChordRenderAbi,
  packIndex: number,
  midiPitches: readonly number[],
  velocities: readonly number[],
  sampleRateHz: number,
  maxSeconds: number | undefined,
): Readonly<{ natural: number; capacity: number }> | null {
  if (
    midiPitches.length === 0 || midiPitches.length > 6 ||
    midiPitches.length !== velocities.length ||
    midiPitches.some((midi) => !Number.isSafeInteger(midi)) ||
    velocities.some((velocity) =>
      !Number.isSafeInteger(velocity) || velocity < 1 || velocity > 127
    )
  ) return null;
  const firstMidi = midiPitches[0];
  if (firstMidi === undefined) return null;
  const natural = abi.noteFrames(packIndex, firstMidi, sampleRateHz);
  if (natural <= 0) return null;
  const capacity =
    maxSeconds === undefined || !Number.isFinite(maxSeconds)
      ? natural
      : Math.min(
          natural,
          Math.max(1, Math.round(maxSeconds * sampleRateHz)),
        );
  return Object.freeze({ natural, capacity });
}

function finishPluckedChordPcm(
  memory: WebAssembly.Memory,
  leftPointer: number,
  rightPointer: number,
  written: number,
  capacity: number,
  natural: number,
  sampleRateHz: number,
): RenderedNotePcm | null {
  if (written <= 0 || written > capacity) return null;
  const left = new Float32Array(written);
  const right = new Float32Array(written);
  left.set(new Float32Array(memory.buffer, leftPointer, written));
  right.set(new Float32Array(memory.buffer, rightPointer, written));
  if (written === capacity && capacity < natural) {
    const fade = Math.min(Math.round(0.015 * sampleRateHz), written);
    for (let index = 0; index < fade; index += 1) {
      const gain = (fade - index) / fade;
      const at = written - fade + index;
      left[at] = (left[at] ?? 0) * gain;
      right[at] = (right[at] ?? 0) * gain;
    }
  }
  return Object.freeze({ sampleRateHz, frameCount: written, left, right });
}

let chordYieldChannel: MessageChannel | null = null;
const chordYieldQueue: Array<() => void> = [];
let chordYieldCount = 0;

function browserMacrotask(): Promise<void> {
  if (typeof MessageChannel === "undefined") {
    return new Promise((resolve) => setTimeout(resolve, 0));
  }
  chordYieldCount += 1;
  /* MessageChannel avoids Firefox's per-step timer clamp, but an unbroken
   * stream from one task source can outrun the transport's timer queue. Give
   * timers an explicit turn every four bounded physical quanta. */
  if (chordYieldCount % 4 === 0) {
    return new Promise((resolve) => setTimeout(resolve, 0));
  }
  chordYieldChannel ??= new MessageChannel();
  chordYieldChannel.port1.onmessage ??= () => {
    chordYieldQueue.shift()?.();
  };
  return new Promise((resolve) => {
    chordYieldQueue.push(resolve);
    chordYieldChannel?.port2.postMessage(0);
  });
}

/** Production/test seam for the sync and cooperative views of one PLK2 ABI. */
export function createPluckedChordRenderFunctions(
  options: PluckedChordRenderFactoryOptions,
): PluckedChordRenderFunctions {
  const { packIndex, memory, scratchBase, cooperativeScratchBase, abi } = options;
  let renderChord: WaveguideRenderer["renderChord"];
  if (abi.renderChordInto !== undefined) {
    renderChord = (midiPitches, velocities, sampleRateHz, maxSeconds) => {
      const physicalSampleRateHz = pluckedChordPhysicalSampleRate(sampleRateHz);
      if (physicalSampleRateHz === null) return null;
      const request = validatePluckedChordRequest(
        abi,
        packIndex,
        midiPitches,
        velocities,
        physicalSampleRateHz,
        maxSeconds,
      );
      if (request === null) return null;
      const channelBytes = request.capacity * 4;
      const leftPointer = scratchBase;
      const rightPointer = leftPointer + channelBytes;
      const midiPointer = rightPointer + channelBytes;
      const velocityPointer = midiPointer + midiPitches.length * 4;
      const totalBytes = velocityPointer + velocities.length * 4 - scratchBase;
      ensureCapacity(memory, scratchBase, totalBytes);
      new Int32Array(memory.buffer, midiPointer, midiPitches.length).set(midiPitches);
      new Int32Array(memory.buffer, velocityPointer, velocities.length).set(velocities);
      const written = abi.renderChordInto?.(
        packIndex,
        midiPointer,
        velocityPointer,
        midiPitches.length,
        physicalSampleRateHz,
        leftPointer,
        rightPointer,
        request.capacity,
      ) ?? 0;
      return finishPluckedChordPcm(
        memory,
        leftPointer,
        rightPointer,
        written,
        request.capacity,
        request.natural,
        physicalSampleRateHz,
      );
    };
  }

  const serializedCooperative = [
    abi.sessionStateMaxBytes,
    abi.sessionMaxSteps,
    abi.sessionInit,
    abi.sessionStep,
  ];
  const runtimeCooperative = [
    abi.runtimeInit,
    abi.runtimeMaxSteps,
    abi.runtimeStep,
    abi.runtimeReset,
  ];
  const useRuntime = runtimeCooperative.every((entry) => entry !== undefined);
  const useSerialized = serializedCooperative.every((entry) => entry !== undefined);
  let renderChordCooperatively: WaveguideRenderer["renderChordCooperatively"];
  if (useRuntime || useSerialized) {
    const yieldToMacrotask = options.yieldToMacrotask ?? browserMacrotask;
    renderChordCooperatively = async (
      midiPitches,
      velocities,
      sampleRateHz,
      maxSeconds,
    ) => {
      const task = async (): Promise<RenderedNotePcm | null> => {
      const physicalSampleRateHz = pluckedChordPhysicalSampleRate(sampleRateHz);
      if (physicalSampleRateHz === null) return null;
      const request = validatePluckedChordRequest(
        abi,
        packIndex,
        midiPitches,
        velocities,
        physicalSampleRateHz,
        maxSeconds,
      );
      if (request === null) return null;
      const maxSteps = useRuntime
        ? abi.runtimeMaxSteps?.(request.capacity) ?? 0
        : abi.sessionMaxSteps?.(request.capacity) ?? 0;
      if (
        !Number.isSafeInteger(maxSteps) || maxSteps <= 0 ||
        maxSteps > MAX_COOPERATIVE_CHORD_STEPS
      ) return null;
      const stateCapacity = useRuntime ? 0 : abi.sessionStateMaxBytes?.() ?? 0;
      if (
        !useRuntime && (
          !Number.isSafeInteger(stateCapacity) || stateCapacity <= 0 ||
          stateCapacity > MAX_COOPERATIVE_CHORD_STATE_BYTES
        )
      ) return null;
      const channelBytes = request.capacity * 4;
      const leftPointer = cooperativeScratchBase;
      const rightPointer = leftPointer + channelBytes;
      const midiPointer = rightPointer + channelBytes;
      const velocityPointer = midiPointer + midiPitches.length * 4;
      const statePointer = velocityPointer + velocities.length * 4;
      const totalBytes = statePointer + stateCapacity - cooperativeScratchBase;
      ensureCapacity(memory, cooperativeScratchBase, totalBytes);
      new Int32Array(memory.buffer, midiPointer, midiPitches.length).set(midiPitches);
      new Int32Array(memory.buffer, velocityPointer, velocities.length).set(velocities);
      if (useRuntime) {
        const handle = abi.runtimeInit?.(
          packIndex,
          midiPointer,
          velocityPointer,
          midiPitches.length,
          physicalSampleRateHz,
          request.capacity,
        ) ?? 0;
        if (!Number.isSafeInteger(handle) || handle <= 0) return null;
        let completed = false;
        try {
          for (let step = 0; step < maxSteps; step += 1) {
            const status = abi.runtimeStep?.(
              handle,
              leftPointer,
              rightPointer,
              request.capacity,
            ) ?? 0;
            if (status === PLK2_CHORD_STEP_COMPLETE) {
              completed = true;
              return finishPluckedChordPcm(
                memory,
                leftPointer,
                rightPointer,
                request.capacity,
                request.capacity,
                request.natural,
                physicalSampleRateHz,
              );
            }
            if (status !== PLK2_CHORD_STEP_PROGRESS) return null;
            await yieldToMacrotask();
          }
          return null;
        } finally {
          if (!completed) abi.runtimeReset?.(handle);
        }
      }
      const stateBytes = abi.sessionInit?.(
        packIndex,
        midiPointer,
        velocityPointer,
        midiPitches.length,
        physicalSampleRateHz,
        request.capacity,
        statePointer,
        stateCapacity,
      ) ?? 0;
      if (stateBytes <= 0 || stateBytes > stateCapacity) return null;
      for (let step = 0; step < maxSteps; step += 1) {
        const status = abi.sessionStep?.(
          statePointer,
          stateBytes,
          leftPointer,
          rightPointer,
          request.capacity,
        ) ?? 0;
        if (status === PLK2_CHORD_STEP_COMPLETE) {
          return finishPluckedChordPcm(
            memory,
            leftPointer,
            rightPointer,
            request.capacity,
            request.capacity,
            request.natural,
            physicalSampleRateHz,
          );
        }
        if (status !== PLK2_CHORD_STEP_PROGRESS) return null;
        await yieldToMacrotask();
      }
      return null;
      };
      return options.runExclusive === undefined
        ? await task()
        : await options.runExclusive(task);
    };
  }
  return Object.freeze({
    ...(renderChord === undefined ? {} : { renderChord }),
    ...(renderChordCooperatively === undefined
      ? {}
      : { renderChordCooperatively }),
  });
}

type DspCore = Readonly<{
  concertGrand: ConcertGrandRenderer;
  waveguide: ReadonlyMap<string, WaveguideRenderer>;
}>;

let rendererPromise: Promise<DspCore> | null = null;

function requireExportedFunction(
  exports: Readonly<Record<string, unknown>>,
  name: string,
): CallableFunction {
  const candidate = exports[name];
  if (typeof candidate !== "function") {
    throw new Error(`DSP_WASM_EXPORT_MISSING:${name}`);
  }
  return candidate;
}

function optionalPluckedStemExports(
  rawExports: Readonly<Record<string, unknown>>,
): Pick<
  ConcertGrandExports,
  | "plk2_stem_state_max_bytes"
  | "plk2_stem_render_max_frames"
  | "plk2_stem_init"
  | "plk2_stem_render"
> {
  const names = [
    "plk2_stem_state_max_bytes",
    "plk2_stem_render_max_frames",
    "plk2_stem_init",
    "plk2_stem_render",
  ] as const;
  const present = names.filter((name) => rawExports[name] !== undefined);
  if (present.length === 0) return Object.freeze({});
  if (present.length !== names.length) {
    const missing = names.find((name) => rawExports[name] === undefined);
    throw new Error(`DSP_WASM_EXPORT_MISSING:${missing ?? "plk2_stem"}`);
  }
  return Object.freeze({
    plk2_stem_state_max_bytes: requireExportedFunction(
      rawExports,
      "plk2_stem_state_max_bytes",
    ) as NonNullable<ConcertGrandExports["plk2_stem_state_max_bytes"]>,
    plk2_stem_render_max_frames: requireExportedFunction(
      rawExports,
      "plk2_stem_render_max_frames",
    ) as NonNullable<ConcertGrandExports["plk2_stem_render_max_frames"]>,
    plk2_stem_init: requireExportedFunction(
      rawExports,
      "plk2_stem_init",
    ) as NonNullable<ConcertGrandExports["plk2_stem_init"]>,
    plk2_stem_render: requireExportedFunction(
      rawExports,
      "plk2_stem_render",
    ) as NonNullable<ConcertGrandExports["plk2_stem_render"]>,
  });
}

function optionalPluckedChordExports(
  rawExports: Readonly<Record<string, unknown>>,
): Pick<
  ConcertGrandExports,
  | "plk2_render_chord"
  | "plk2_chord_session_state_max_bytes"
  | "plk2_chord_session_max_steps"
  | "plk2_chord_session_init"
  | "plk2_chord_session_step"
  | "plk2_chord_runtime_init"
  | "plk2_chord_runtime_max_steps"
  | "plk2_chord_runtime_step"
  | "plk2_chord_runtime_reset"
> {
  const renderChord = rawExports["plk2_render_chord"] === undefined
    ? undefined
    : requireExportedFunction(
      rawExports,
      "plk2_render_chord",
    ) as NonNullable<ConcertGrandExports["plk2_render_chord"]>;
  const cooperativeNames = [
    "plk2_chord_session_state_max_bytes",
    "plk2_chord_session_max_steps",
    "plk2_chord_session_init",
    "plk2_chord_session_step",
  ] as const;
  const present = cooperativeNames.filter((name) => rawExports[name] !== undefined);
  if (present.length !== 0 && present.length !== cooperativeNames.length) {
    const missing = cooperativeNames.find((name) => rawExports[name] === undefined);
    throw new Error(`DSP_WASM_EXPORT_MISSING:${missing ?? "plk2_chord_session"}`);
  }
  const cooperative = present.length === cooperativeNames.length
    ? {
      plk2_chord_session_state_max_bytes: requireExportedFunction(
        rawExports,
        "plk2_chord_session_state_max_bytes",
      ) as NonNullable<ConcertGrandExports["plk2_chord_session_state_max_bytes"]>,
      plk2_chord_session_max_steps: requireExportedFunction(
        rawExports,
        "plk2_chord_session_max_steps",
      ) as NonNullable<ConcertGrandExports["plk2_chord_session_max_steps"]>,
      plk2_chord_session_init: requireExportedFunction(
        rawExports,
        "plk2_chord_session_init",
      ) as NonNullable<ConcertGrandExports["plk2_chord_session_init"]>,
      plk2_chord_session_step: requireExportedFunction(
        rawExports,
        "plk2_chord_session_step",
      ) as NonNullable<ConcertGrandExports["plk2_chord_session_step"]>,
    }
    : {};
  const runtimeNames = [
    "plk2_chord_runtime_init",
    "plk2_chord_runtime_max_steps",
    "plk2_chord_runtime_step",
    "plk2_chord_runtime_reset",
  ] as const;
  const runtimePresent = runtimeNames.filter((name) => rawExports[name] !== undefined);
  if (runtimePresent.length !== 0 && runtimePresent.length !== runtimeNames.length) {
    const missing = runtimeNames.find((name) => rawExports[name] === undefined);
    throw new Error(`DSP_WASM_EXPORT_MISSING:${missing ?? "plk2_chord_runtime"}`);
  }
  const runtime = runtimePresent.length === runtimeNames.length
    ? {
      plk2_chord_runtime_init: requireExportedFunction(
        rawExports,
        "plk2_chord_runtime_init",
      ) as NonNullable<ConcertGrandExports["plk2_chord_runtime_init"]>,
      plk2_chord_runtime_max_steps: requireExportedFunction(
        rawExports,
        "plk2_chord_runtime_max_steps",
      ) as NonNullable<ConcertGrandExports["plk2_chord_runtime_max_steps"]>,
      plk2_chord_runtime_step: requireExportedFunction(
        rawExports,
        "plk2_chord_runtime_step",
      ) as NonNullable<ConcertGrandExports["plk2_chord_runtime_step"]>,
      plk2_chord_runtime_reset: requireExportedFunction(
        rawExports,
        "plk2_chord_runtime_reset",
      ) as NonNullable<ConcertGrandExports["plk2_chord_runtime_reset"]>,
    }
    : {};
  return Object.freeze({
    ...(renderChord === undefined ? {} : { plk2_render_chord: renderChord }),
    ...cooperative,
    ...runtime,
  });
}

async function instantiate(): Promise<DspCore> {
  const bytes = decodeWasmBytes();
  const { instance } = await WebAssembly.instantiate(bytes, {});
  const rawExports: Readonly<Record<string, unknown>> = instance.exports;
  const memoryCandidate = rawExports["memory"];
  if (!(memoryCandidate instanceof WebAssembly.Memory)) {
    throw new Error("DSP_WASM_EXPORT_MISSING:memory");
  }
  const heapBaseCandidate = rawExports["__heap_base"];
  const exports: ConcertGrandExports = {
    memory: memoryCandidate,
    ...(heapBaseCandidate instanceof WebAssembly.Global
      ? { __heap_base: heapBaseCandidate }
      : {}),
    /*
     * Wasm export signatures are not statically typed; each callable is
     * runtime-verified above and asserted to its concrete numeric signature.
     */
    cg_note_frames: requireExportedFunction(
      rawExports,
      "cg_note_frames",
    ) as ConcertGrandExports["cg_note_frames"],
    cg_render: requireExportedFunction(
      rawExports,
      "cg_render",
    ) as ConcertGrandExports["cg_render"],
    an_spectrum: requireExportedFunction(
      rawExports,
      "an_spectrum",
    ) as ConcertGrandExports["an_spectrum"],
    an_notes: requireExportedFunction(
      rawExports,
      "an_notes",
    ) as ConcertGrandExports["an_notes"],
    an_chroma: requireExportedFunction(
      rawExports,
      "an_chroma",
    ) as ConcertGrandExports["an_chroma"],
    gtr_note_frames: requireExportedFunction(
      rawExports,
      "gtr_note_frames",
    ) as ConcertGrandExports["gtr_note_frames"],
    gtr_render: requireExportedFunction(
      rawExports,
      "gtr_render",
    ) as ConcertGrandExports["gtr_render"],
    plk2_note_frames: requireExportedFunction(
      rawExports,
      "plk2_note_frames",
    ) as ConcertGrandExports["plk2_note_frames"],
    plk2_render: requireExportedFunction(
      rawExports,
      "plk2_render",
    ) as ConcertGrandExports["plk2_render"],
    ...optionalPluckedChordExports(rawExports),
    ...optionalPluckedStemExports(rawExports),
    flt_note_frames: requireExportedFunction(
      rawExports,
      "flt_note_frames",
    ) as ConcertGrandExports["flt_note_frames"],
    flt_render: requireExportedFunction(
      rawExports,
      "flt_render",
    ) as ConcertGrandExports["flt_render"],
    flt_render_seeded: requireExportedFunction(
      rawExports,
      "flt_render_seeded",
    ) as ConcertGrandExports["flt_render_seeded"],
    flt_render_expressive: requireExportedFunction(
      rawExports,
      "flt_render_expressive",
    ) as ConcertGrandExports["flt_render_expressive"],
    flt2_note_frames: requireExportedFunction(
      rawExports,
      "flt2_note_frames",
    ) as ConcertGrandExports["flt2_note_frames"],
    flt2_render: requireExportedFunction(
      rawExports,
      "flt2_render",
    ) as ConcertGrandExports["flt2_render"],
    clr_note_frames: requireExportedFunction(
      rawExports,
      "clr_note_frames",
    ) as ConcertGrandExports["clr_note_frames"],
    clr_render: requireExportedFunction(
      rawExports,
      "clr_render",
    ) as ConcertGrandExports["clr_render"],
    clr_render_seeded: requireExportedFunction(
      rawExports,
      "clr_render_seeded",
    ) as ConcertGrandExports["clr_render_seeded"],
    clr_render_expressive: requireExportedFunction(
      rawExports,
      "clr_render_expressive",
    ) as ConcertGrandExports["clr_render_expressive"],
    clr_render_v2: requireExportedFunction(
      rawExports,
      "clr_render_v2",
    ) as ConcertGrandExports["clr_render_v2"],
    clr_state_max_bytes_v2: requireExportedFunction(
      rawExports,
      "clr_state_max_bytes_v2",
    ) as ConcertGrandExports["clr_state_max_bytes_v2"],
    clr_state_fixed_bytes_v2: requireExportedFunction(
      rawExports,
      "clr_state_fixed_bytes_v2",
    ) as ConcertGrandExports["clr_state_fixed_bytes_v2"],
    clr_render_phrase_v2: requireExportedFunction(
      rawExports,
      "clr_render_phrase_v2",
    ) as ConcertGrandExports["clr_render_phrase_v2"],
    phs_validate_v2: requireExportedFunction(
      instance.exports,
      "phs_validate_v2",
    ) as ConcertGrandExports["phs_validate_v2"],
    phs_modal_render_v2: requireExportedFunction(
      instance.exports,
      "phs_modal_render_v2",
    ) as ConcertGrandExports["phs_modal_render_v2"],
    phs_reed_solve_v2: requireExportedFunction(
      instance.exports,
      "phs_reed_solve_v2",
    ) as ConcertGrandExports["phs_reed_solve_v2"],
    phs_clarinet_reed_step_v2: requireExportedFunction(
      instance.exports,
      "phs_clarinet_reed_step_v2",
    ) as ConcertGrandExports["phs_clarinet_reed_step_v2"],
  };
  const memory = exports.memory;
  /* Scratch region starts past the module's own data and shadow stack. */
  const heapBase =
    typeof exports.__heap_base?.value === "number"
      ? exports.__heap_base.value
      : memory.buffer.byteLength;
  const scratchBase = Math.ceil((heapBase + 1_024) / 16) * 16;
  let cooperativeChordTail: Promise<void> = Promise.resolve();
  const runCooperativeChordExclusive = <T>(
    task: () => Promise<T>,
  ): Promise<T> => {
    const result = cooperativeChordTail.then(task, task);
    cooperativeChordTail = result.then(
      () => undefined,
      () => undefined,
    );
    return result;
  };

  const renderSynthesizedNote = (
    midiPitch: number,
    velocity: number,
    sampleRateHz: number,
    maxSeconds?: number,
  ): RenderedNotePcm | null => {
    const natural = exports.cg_note_frames(midiPitch, sampleRateHz);
    if (natural <= 0) return null;
    const capacity =
      maxSeconds === undefined || !Number.isFinite(maxSeconds)
        ? natural
        : Math.min(natural, Math.max(1, Math.round(maxSeconds * sampleRateHz)));
    const channelBytes = capacity * 4;
    const leftPointer = scratchBase;
    const rightPointer = scratchBase + channelBytes;
    ensureCapacity(memory, scratchBase, channelBytes * 2);
    const written = exports.cg_render(
      midiPitch,
      velocity,
      sampleRateHz,
      leftPointer,
      rightPointer,
      capacity,
    );
    if (written <= 0) return null;
    /* Copy out: the scratch region is reused by the next render. */
    const left = new Float32Array(written);
    const right = new Float32Array(written);
    left.set(new Float32Array(memory.buffer, leftPointer, written));
    right.set(new Float32Array(memory.buffer, rightPointer, written));
    return Object.freeze({
      sampleRateHz,
      frameCount: written,
      left,
      right,
    });
  };

  const renderNote = (
    midiPitch: number,
    velocity: number,
    sampleRateHz: number,
    maxSeconds?: number,
  ): RenderedNotePcm | null => {
    const synthesized = renderSynthesizedNote(
      midiPitch,
      velocity,
      sampleRateHz,
      maxSeconds,
    );
    if (synthesized === null) return null;
    applyAttackLayer(
      synthesized.left,
      synthesized.right,
      synthesized.frameCount,
      midiPitch,
      velocity,
      sampleRateHz,
    );
    if (maxSeconds === undefined || !Number.isFinite(maxSeconds)) {
      return synthesized;
    }
    const wanted = Math.max(1, Math.round(maxSeconds * sampleRateHz));
    if (wanted >= synthesized.frameCount) return synthesized;
    /* Fade the truncation over ~15 ms so the cut cannot click. */
    const fade = Math.min(Math.round(0.015 * sampleRateHz), wanted);
    const left = synthesized.left.slice(0, wanted);
    const right = synthesized.right.slice(0, wanted);
    for (let index = 0; index < fade; index += 1) {
      const gain = (fade - index) / fade;
      const at = wanted - fade + index;
      left[at] = (left[at] ?? 0) * gain;
      right[at] = (right[at] ?? 0) * gain;
    }
    return Object.freeze({
      sampleRateHz: synthesized.sampleRateHz,
      frameCount: wanted,
      left,
      right,
    });
  };

  const MAX_DETECTED_NOTES = 12;

  const validatePhysicalAbiV2 = (
    request: PhysicalRenderAbiRequestV2,
    linearMemoryBytes: number,
  ): PhysicalRenderRefusalCode | null => {
    const outcome = exports.phs_validate_v2(
      request.abiVersion,
      request.requestByteLength,
      request.descriptorOffset,
      request.descriptorCount,
      request.controlPointOffset,
      request.controlPointCount,
      request.outputLeftOffset,
      request.outputRightOffset,
      request.outputCapacityFrames,
      request.stateInputOffset,
      request.stateInputByteLength,
      request.stateOutputOffset,
      request.stateOutputCapacityBytes,
      linearMemoryBytes,
    );
    if (outcome === 0) return null;
    if (outcome === 1) return "physical.schema_unsupported";
    if (outcome === 3) return "limit.physical_frames_exceeded";
    if (outcome === 4) return "limit.physical_control_points_exceeded";
    if (outcome === 5) return "physical.state_handoff_invalid";
    return "physical.abi_bounds_invalid";
  };

  const renderPhysicalModalV2: ConcertGrandRenderer["renderPhysicalModalV2"] =
    (request) => {
      if (
        !Number.isSafeInteger(request.frameCount) ||
        request.frameCount <= 0 ||
        request.frameCount > 2_880_000
      ) {
        return null;
      }
      const channelBytes = request.frameCount * 4;
      const leftPointer = scratchBase;
      const rightPointer = leftPointer + channelBytes;
      // The f64 state view requires 8-byte alignment; an odd frame count
      // leaves rightPointer + channelBytes at 4 mod 8, which the wasm-side
      // validator now refuses and a Float64Array view would throw on.
      const statePointer = Math.ceil((rightPointer + channelBytes) / 8) * 8;
      const energyPointer = Math.ceil((statePointer + 16) / 8) * 8;
      ensureCapacity(memory, scratchBase, energyPointer + 48 - scratchBase);
      const written = exports.phs_modal_render_v2(
        request.sampleRateHz,
        request.frequencyHz,
        request.dampingPerSecond,
        request.excitation,
        request.initialState.x,
        request.initialState.y,
        leftPointer,
        rightPointer,
        request.frameCount,
        statePointer,
        energyPointer,
      );
      if (written !== request.frameCount) return null;
      const left = new Float32Array(written);
      const right = new Float32Array(written);
      left.set(new Float32Array(memory.buffer, leftPointer, written));
      right.set(new Float32Array(memory.buffer, rightPointer, written));
      const state = new Float64Array(memory.buffer, statePointer, 2);
      const energy = new Float64Array(memory.buffer, energyPointer, 6);
      return Object.freeze({
        sampleRateHz: request.sampleRateHz,
        frameCount: written,
        left,
        right,
        state: Object.freeze({ x: state[0] ?? 0, y: state[1] ?? 0 }),
        energy: Object.freeze({
          initialEnergy: energy[0] ?? 0,
          excitationWork: energy[1] ?? 0,
          finalEnergy: energy[2] ?? 0,
          dampingLoss: energy[3] ?? 0,
          residual: energy[4] ?? 0,
        }),
        limiterEngagements: energy[5] ?? 0,
      });
    };

  const solvePhysicalReedV2: ConcertGrandRenderer["solvePhysicalReedV2"] =
    (request) => {
      const outputPointer = Math.ceil(scratchBase / 8) * 8;
      ensureCapacity(memory, scratchBase, outputPointer + 32 - scratchBase);
      const outcome = exports.phs_reed_solve_v2(
        request.mouthPressure,
        request.borePressure,
        request.opening,
        request.stiffness,
        request.boreImpedance,
        outputPointer,
      );
      if (outcome !== 1) return null;
      const values = new Float64Array(memory.buffer, outputPointer, 4);
      return Object.freeze({
        junctionPressure: values[0] ?? 0,
        volumeFlow: values[1] ?? 0,
        nonlinearIterations: values[2] ?? 0,
        fallbackBisections: values[3] ?? 0,
      });
    };

  const stepPhysicalClarinetReedV2: ConcertGrandRenderer["stepPhysicalClarinetReedV2"] =
    (request) => {
      const outputPointer = Math.ceil(scratchBase / 8) * 8;
      ensureCapacity(memory, scratchBase, outputPointer + 64 - scratchBase);
      const outcome = exports.phs_clarinet_reed_step_v2(
        request.dtSeconds, request.state.displacementM, request.state.velocityMPerS,
        request.mouthPressurePa, request.mouthpiecePressurePa, request.massKg,
        request.dampingNsPerM, request.stiffnessNPerM, request.equilibriumOpeningM,
        request.effectiveAreaM2, request.channelWidthM, request.airDensityKgPerM3,
        request.tongueContact, outputPointer,
      );
      if (outcome !== 1) return null;
      const value = new Float64Array(memory.buffer, outputPointer, 8);
      return Object.freeze({
        state: Object.freeze({ displacementM: value[0] ?? 0, velocityMPerS: value[1] ?? 0 }),
        signedVolumeFlowM3PerS: value[2] ?? 0,
        collisionLossJ: value[3] ?? 0,
        mechanicalEnergyBeforeJ: value[4] ?? 0,
        mechanicalEnergyAfterJ: value[5] ?? 0,
        tongueForceN: value[6] ?? 0,
        contact: value[7] === 1,
      });
    };

  const analyzeWindow = (
    samples: Float32Array,
    sampleRateHz: number,
  ): AnalysisFrame | null => {
    const fftSize = samples.length;
    if (
      fftSize < 64 ||
      fftSize > 8_192 ||
      (fftSize & (fftSize - 1)) !== 0 ||
      !Number.isFinite(sampleRateHz) ||
      sampleRateHz <= 0
    ) {
      return null;
    }
    const binCount = fftSize / 2;
    /*
     * Scratch layout: input window, magnitude bins, note triples, chroma —
     * all in the same reusable region past the render scratch.
     */
    const inputPointer = scratchBase;
    const magnitudesPointer = inputPointer + fftSize * 4;
    const notesPointer = magnitudesPointer + binCount * 4;
    const chromaPointer = notesPointer + MAX_DETECTED_NOTES * 3 * 4;
    ensureCapacity(memory, scratchBase, chromaPointer + 12 * 4 - scratchBase);
    new Float32Array(memory.buffer, inputPointer, fftSize).set(samples);
    const bins = exports.an_spectrum(inputPointer, fftSize, magnitudesPointer);
    if (bins !== binCount) return null;
    const noteCount = exports.an_notes(
      magnitudesPointer,
      bins,
      sampleRateHz,
      fftSize,
      notesPointer,
      MAX_DETECTED_NOTES,
    );
    const chromaCount = exports.an_chroma(
      magnitudesPointer,
      bins,
      sampleRateHz,
      fftSize,
      chromaPointer,
    );
    if (chromaCount !== 12 || noteCount < 0) return null;
    const magnitudes = new Float32Array(binCount);
    magnitudes.set(new Float32Array(memory.buffer, magnitudesPointer, binCount));
    const chroma = new Float32Array(12);
    chroma.set(new Float32Array(memory.buffer, chromaPointer, 12));
    const triples = new Float32Array(memory.buffer, notesPointer, noteCount * 3);
    const notes: DetectedNote[] = [];
    for (let index = 0; index < noteCount; index += 1) {
      notes.push(
        Object.freeze({
          midiPitch: triples[index * 3] ?? 0,
          centsDeviation: triples[index * 3 + 1] ?? 0,
          strength: triples[index * 3 + 2] ?? 0,
        }),
      );
    }
    return Object.freeze({
      sampleRateHz,
      fftSize,
      magnitudes,
      notes: Object.freeze(notes),
      chroma,
    });
  };

  /*
   * Waveguide renderers (physically modeled guitar and flute) live in the
   * same wasm instance and share the scratch region. Each is the same
   * render-copy-truncate shape as the piano's synthesized path; the models
   * bake their own musical envelopes, so the only post-processing is the
   * click-guard fade on an explicit truncation.
   */
  const makeWaveguideRenderNote = (
    noteFrames: (midi: number, rate: number) => number,
    renderInto: (
      midi: number,
      velocity: number,
      rate: number,
      left: number,
      right: number,
      maxFrames: number,
    ) => number,
    renderSeededInto?: (
      midi: number,
      velocity: number,
      rate: number,
      variationSlot: number,
      left: number,
      right: number,
      maxFrames: number,
    ) => number,
    renderExpressiveInto?: (
      midi: number,
      velocity: number,
      rate: number,
      variationSlot: number,
      articulation: number,
      left: number,
      right: number,
      maxFrames: number,
    ) => number,
  ): WaveguideRenderer["renderNote"] => {
    return (
      midiPitch,
      velocity,
      sampleRateHz,
      maxSeconds,
      variationSlot,
      windArticulation,
    ) => {
      const runtimeWindArticulation: unknown = windArticulation;
      if (
        runtimeWindArticulation !== undefined &&
        runtimeWindArticulation !== "legato" &&
        runtimeWindArticulation !== "tongued"
      ) return null;
      const natural = noteFrames(midiPitch, sampleRateHz);
      if (natural <= 0) return null;
      const capacity =
        maxSeconds === undefined || !Number.isFinite(maxSeconds)
          ? natural
          : Math.min(
              natural,
              Math.max(1, Math.round(maxSeconds * sampleRateHz)),
            );
      const channelBytes = capacity * 4;
      const leftPointer = scratchBase;
      const rightPointer = scratchBase + channelBytes;
      ensureCapacity(memory, scratchBase, channelBytes * 2);
      const articulationCode = windArticulation === "legato" ? 0 : 1;
      const written = variationSlot !== undefined &&
          windArticulation !== undefined &&
          renderExpressiveInto !== undefined
        ? renderExpressiveInto(
            midiPitch,
            velocity,
            sampleRateHz,
            variationSlot,
            articulationCode,
            leftPointer,
            rightPointer,
            capacity,
          )
        : variationSlot !== undefined && renderSeededInto !== undefined
        ? renderSeededInto(
            midiPitch,
            velocity,
            sampleRateHz,
            variationSlot,
            leftPointer,
            rightPointer,
            capacity,
          )
        : renderInto(
            midiPitch,
            velocity,
            sampleRateHz,
            leftPointer,
            rightPointer,
            capacity,
          );
      if (written <= 0) return null;
      const left = new Float32Array(written);
      const right = new Float32Array(written);
      left.set(new Float32Array(memory.buffer, leftPointer, written));
      right.set(new Float32Array(memory.buffer, rightPointer, written));
      if (written === capacity && capacity < natural) {
        /* Truncated by the caller: fade ~15 ms so the cut cannot click. */
        const fade = Math.min(Math.round(0.015 * sampleRateHz), written);
        for (let index = 0; index < fade; index += 1) {
          const gain = (fade - index) / fade;
          const at = written - fade + index;
          left[at] = (left[at] ?? 0) * gain;
          right[at] = (right[at] ?? 0) * gain;
        }
      }
      return Object.freeze({
        sampleRateHz,
        frameCount: written,
        left,
        right,
      });
    };
  };

  const makePluckedChordRenders = (
    packIndex: number,
  ): PluckedChordRenderFunctions => createPluckedChordRenderFunctions({
    packIndex,
    memory,
    scratchBase,
    /*
     * The cooperative session remains live across macrotask yields. Keep it
     * above every synchronous scratch allocation, then serialize all packs
     * because they deliberately share this bounded region.
     */
    cooperativeScratchBase: scratchBase + COOPERATIVE_CHORD_SCRATCH_OFFSET_BYTES,
    abi: Object.freeze({
      noteFrames: exports.plk2_note_frames,
      ...(exports.plk2_render_chord === undefined
        ? {}
        : { renderChordInto: exports.plk2_render_chord }),
      ...(exports.plk2_chord_session_state_max_bytes === undefined
        ? {}
        : { sessionStateMaxBytes: exports.plk2_chord_session_state_max_bytes }),
      ...(exports.plk2_chord_session_max_steps === undefined
        ? {}
        : { sessionMaxSteps: exports.plk2_chord_session_max_steps }),
      ...(exports.plk2_chord_session_init === undefined
        ? {}
        : { sessionInit: exports.plk2_chord_session_init }),
      ...(exports.plk2_chord_session_step === undefined
        ? {}
        : { sessionStep: exports.plk2_chord_session_step }),
      ...(exports.plk2_chord_runtime_init === undefined
        ? {}
        : { runtimeInit: exports.plk2_chord_runtime_init }),
      ...(exports.plk2_chord_runtime_max_steps === undefined
        ? {}
        : { runtimeMaxSteps: exports.plk2_chord_runtime_max_steps }),
      ...(exports.plk2_chord_runtime_step === undefined
        ? {}
        : { runtimeStep: exports.plk2_chord_runtime_step }),
      ...(exports.plk2_chord_runtime_reset === undefined
        ? {}
        : { runtimeReset: exports.plk2_chord_runtime_reset }),
    }),
    runExclusive: runCooperativeChordExclusive,
  });

  const renderClarinetPhraseSegment: NonNullable<
    WaveguideRenderer["renderPhraseSegment"]
  > = (
    midiPitch,
    velocity,
    sampleRateHz,
    frameCount,
    stateInput,
    variationSlot,
    windArticulation,
  ) => {
    const runtimeWindArticulation: unknown = windArticulation;
    if (
      !Number.isSafeInteger(frameCount) || frameCount <= 0 ||
      !Number.isSafeInteger(variationSlot) || variationSlot < 0 ||
      (runtimeWindArticulation !== "legato" &&
        runtimeWindArticulation !== "tongued")
    ) return null;
    const natural = exports.clr_note_frames(midiPitch, sampleRateHz);
    const stateCapacity = exports.clr_state_max_bytes_v2();
    const stateFixedBytes = exports.clr_state_fixed_bytes_v2();
    if (
      natural <= 0 || frameCount > natural || stateCapacity <= 0 ||
      stateFixedBytes <= 0 || stateFixedBytes > stateCapacity ||
      (stateInput !== null && stateInput.byteLength > stateCapacity)
    ) return null;
    const channelBytes = frameCount * 4;
    const leftPointer = scratchBase;
    const rightPointer = leftPointer + channelBytes;
    const stateInputPointer = Math.ceil((rightPointer + channelBytes) / 8) * 8;
    const stateInputBytes = stateInput?.byteLength ?? 0;
    const stateOutputPointer = Math.ceil(
      (stateInputPointer + stateInputBytes) / 8,
    ) * 8;
    ensureCapacity(
      memory,
      scratchBase,
      stateOutputPointer + stateCapacity - scratchBase,
    );
    if (stateInput !== null) {
      new Uint8Array(memory.buffer, stateInputPointer, stateInputBytes).set(stateInput);
    }
    const written = exports.clr_render_phrase_v2(
      midiPitch,
      velocity,
      sampleRateHz,
      variationSlot,
      windArticulation === "legato" ? 0 : 1,
      leftPointer,
      rightPointer,
      frameCount,
      stateInputBytes === 0 ? 0 : stateInputPointer,
      stateInputBytes,
      stateOutputPointer,
      stateCapacity,
    );
    if (written <= 0 || written > frameCount) return null;
    const stateView = new DataView(memory.buffer, stateOutputPointer, stateCapacity);
    const boreLength = stateView.getUint32(16, true);
    const stateBytes = stateFixedBytes + boreLength * 8;
    if (boreLength < 3 || stateBytes > stateCapacity) return null;
    const left = new Float32Array(written);
    const right = new Float32Array(written);
    left.set(new Float32Array(memory.buffer, leftPointer, written));
    right.set(new Float32Array(memory.buffer, rightPointer, written));
    const stateOutput = new Uint8Array(stateBytes);
    stateOutput.set(new Uint8Array(memory.buffer, stateOutputPointer, stateBytes));
    return Object.freeze({
      sampleRateHz,
      frameCount: written,
      left,
      right,
      stateOutput,
    });
  };

  const makePluckedStemSegment = (
    packIndex: number,
  ): NonNullable<WaveguideRenderer["renderPluckedStemSegment"]> | undefined => {
    const stateMaxBytesFor = exports.plk2_stem_state_max_bytes;
    const renderMaxFramesFor = exports.plk2_stem_render_max_frames;
    const initialize = exports.plk2_stem_init;
    const render = exports.plk2_stem_render;
    if (
      stateMaxBytesFor === undefined || renderMaxFramesFor === undefined ||
      initialize === undefined || render === undefined
    ) return undefined;
    return (
      midiPitch,
      velocity,
      sampleRateHz,
      frameCount,
      stateInput,
      reset,
    ) => {
      if (
        !Number.isSafeInteger(packIndex) || packIndex < 0 ||
        !Number.isSafeInteger(frameCount) || frameCount <= 0 ||
        !Number.isFinite(sampleRateHz) ||
        (midiPitch === null
          ? velocity !== 0
          : !Number.isSafeInteger(midiPitch) ||
            !Number.isSafeInteger(velocity) || velocity < 1 || velocity > 127)
      ) return null;
      const stateCapacity = stateMaxBytesFor();
      const maximumFrames = renderMaxFramesFor();
      if (
        !Number.isSafeInteger(stateCapacity) || stateCapacity <= 0 ||
        stateCapacity > 64 * 1_024 ||
        !Number.isSafeInteger(maximumFrames) || maximumFrames <= 0 ||
        frameCount > maximumFrames ||
        (stateInput !== null &&
          (stateInput.byteLength <= 0 || stateInput.byteLength > stateCapacity))
      ) return null;
      const statePointer = scratchBase;
      const leftPointer = Math.ceil((statePointer + stateCapacity) / 4) * 4;
      const channelBytes = frameCount * 4;
      const rightPointer = leftPointer + channelBytes;
      ensureCapacity(
        memory,
        scratchBase,
        rightPointer + channelBytes - scratchBase,
      );
      let stateBytes: number;
      if (stateInput === null) {
        stateBytes = initialize(
          packIndex,
          sampleRateHz,
          statePointer,
          stateCapacity,
        );
      } else {
        stateBytes = stateInput.byteLength;
        new Uint8Array(memory.buffer, statePointer, stateBytes).set(stateInput);
      }
      if (stateBytes <= 0 || stateBytes > stateCapacity) return null;
      const eventFlags = (midiPitch === null ? 0 : 1) | (reset ? 2 : 0);
      const written = render(
        statePointer,
        stateBytes,
        midiPitch ?? -1,
        midiPitch === null ? 0 : velocity,
        eventFlags,
        leftPointer,
        rightPointer,
        frameCount,
      );
      if (written !== frameCount) return null;
      const left = new Float32Array(written);
      const right = new Float32Array(written);
      left.set(new Float32Array(memory.buffer, leftPointer, written));
      right.set(new Float32Array(memory.buffer, rightPointer, written));
      const stateOutput = new Uint8Array(stateBytes);
      stateOutput.set(new Uint8Array(memory.buffer, statePointer, stateBytes));
      return Object.freeze({
        sampleRateHz,
        frameCount: written,
        left,
        right,
        stateOutput,
      });
    };
  };

  const renderUprightBassStemSegment = makePluckedStemSegment(
    PLK2_UPRIGHT_BASS_PACK_INDEX,
  );

  const waveguide = new Map<string, WaveguideRenderer>();
  for (const [algorithmId, renderNoteFor] of [
    [
      PLUCKED_ARCHTOP_V2_ALGORITHM_ID,
      makeWaveguideRenderNote(
        (m, r) => exports.plk2_note_frames(0, m, r),
        (m, v, r, l, rt, mx) => exports.plk2_render(0, m, v, r, l, rt, mx),
      ),
    ],
    [
      PLUCKED_ELECTRIC_V2_ALGORITHM_ID,
      makeWaveguideRenderNote(
        (m, r) => exports.plk2_note_frames(1, m, r),
        (m, v, r, l, rt, mx) => exports.plk2_render(1, m, v, r, l, rt, mx),
      ),
    ],
    [
      PLUCKED_DREADNOUGHT_ALGORITHM_ID,
      makeWaveguideRenderNote(
        (m, r) => exports.plk2_note_frames(2, m, r),
        (m, v, r, l, rt, mx) => exports.plk2_render(2, m, v, r, l, rt, mx),
      ),
    ],
    [
      PLUCKED_UKULELE_ALGORITHM_ID,
      makeWaveguideRenderNote(
        (m, r) => exports.plk2_note_frames(3, m, r),
        (m, v, r, l, rt, mx) => exports.plk2_render(3, m, v, r, l, rt, mx),
      ),
    ],
    [
      PLUCKED_UPRIGHT_BASS_ALGORITHM_ID,
      makeWaveguideRenderNote(
        (m, r) => exports.plk2_note_frames(4, m, r),
        (m, v, r, l, rt, mx) => exports.plk2_render(4, m, v, r, l, rt, mx),
      ),
    ],
    [
      WAVEGUIDE_GUITAR_CLEAN_ALGORITHM_ID,
      makeWaveguideRenderNote(exports.gtr_note_frames, (m, v, r, l, rt, mx) =>
        exports.gtr_render(m, v, r, 0, l, rt, mx),
      ),
    ],
    [
      WAVEGUIDE_GUITAR_DRIVE_ALGORITHM_ID,
      makeWaveguideRenderNote(exports.gtr_note_frames, (m, v, r, l, rt, mx) =>
        exports.gtr_render(m, v, r, 1, l, rt, mx),
      ),
    ],
    [
      WAVEGUIDE_FLUTE_ALGORITHM_ID,
      makeWaveguideRenderNote(
        exports.flt_note_frames,
        (m, v, r, l, rt, mx) => exports.flt_render(m, v, r, l, rt, mx),
        (m, v, r, slot, l, rt, mx) =>
          exports.flt_render_seeded(m, v, r, slot, l, rt, mx),
        (m, v, r, slot, articulation, l, rt, mx) =>
          exports.flt_render_expressive(
            m,
            v,
            r,
            slot,
            articulation,
            l,
            rt,
            mx,
          ),
      ),
    ],
    [
      WAVEGUIDE_FLUTE_V2_ALGORITHM_ID,
      makeWaveguideRenderNote(
        exports.flt2_note_frames,
        (m, v, r, l, rt, mx) => exports.flt2_render(m, v, r, 0, 1, l, rt, mx),
      ),
    ],
    [
      WAVEGUIDE_CLARINET_ALGORITHM_ID,
      makeWaveguideRenderNote(
        exports.clr_note_frames,
        (m, v, r, l, rt, mx) => exports.clr_render(m, v, r, l, rt, mx),
        (m, v, r, slot, l, rt, mx) =>
          exports.clr_render_seeded(m, v, r, slot, l, rt, mx),
        (m, v, r, slot, articulation, l, rt, mx) =>
          exports.clr_render_expressive(
            m,
            v,
            r,
            slot,
            articulation,
            l,
            rt,
            mx,
          ),
      ),
    ],
    [
      WAVEGUIDE_CLARINET_V2_ALGORITHM_ID,
      makeWaveguideRenderNote(
        exports.clr_note_frames,
        (m, v, r, l, rt, mx) => exports.clr_render_v2(m, v, r, 0, 1, l, rt, mx),
        (m, v, r, slot, l, rt, mx) => exports.clr_render_v2(m, v, r, slot, 1, l, rt, mx),
        (m, v, r, slot, articulation, l, rt, mx) =>
          exports.clr_render_v2(m, v, r, slot, articulation, l, rt, mx),
      ),
    ],
  ] as const) {
    waveguide.set(
      algorithmId,
      Object.freeze({
        algorithmId,
        wasmSha256: CONCERT_GRAND_WASM_SHA256,
        renderNote: renderNoteFor,
      }),
    );
  }
  for (const [algorithmId, packIndex] of [
    [PLUCKED_ARCHTOP_V2_ALGORITHM_ID, 0],
    [PLUCKED_ELECTRIC_V2_ALGORITHM_ID, 1],
    [PLUCKED_DREADNOUGHT_ALGORITHM_ID, 2],
    [PLUCKED_UKULELE_ALGORITHM_ID, 3],
    [PLUCKED_UPRIGHT_BASS_ALGORITHM_ID, PLK2_UPRIGHT_BASS_PACK_INDEX],
  ] as const) {
    const subject = waveguide.get(algorithmId);
    if (subject === undefined) throw new Error(`DSP_PLUCKED_RENDERER_MISSING:${algorithmId}`);
    const chordRenders = makePluckedChordRenders(packIndex);
    if (Object.keys(chordRenders).length !== 0) {
      waveguide.set(
        algorithmId,
        Object.freeze({ ...subject, ...chordRenders }),
      );
    }
  }
  const uprightBass = waveguide.get(PLUCKED_UPRIGHT_BASS_ALGORITHM_ID);
  if (uprightBass === undefined) throw new Error("DSP_UPRIGHT_BASS_MISSING");
  if (renderUprightBassStemSegment !== undefined) {
    waveguide.set(
      PLUCKED_UPRIGHT_BASS_ALGORITHM_ID,
      Object.freeze({
        ...uprightBass,
        renderPluckedStemSegment: renderUprightBassStemSegment,
      }),
    );
  }
  const clarinetV2 = waveguide.get(WAVEGUIDE_CLARINET_V2_ALGORITHM_ID);
  if (clarinetV2 === undefined) throw new Error("DSP_CLARINET_V2_MISSING");
  waveguide.set(
    WAVEGUIDE_CLARINET_V2_ALGORITHM_ID,
    Object.freeze({ ...clarinetV2, renderPhraseSegment: renderClarinetPhraseSegment }),
  );

  return Object.freeze({
    concertGrand: Object.freeze({
      algorithmId: CONCERT_GRAND_RENDERER_ALGORITHM_ID,
      wasmSha256: CONCERT_GRAND_WASM_SHA256,
      attackSamplesSha256: PIANO_ATTACK_SAMPLES_SHA256,
      renderNote,
      renderSynthesizedNote,
      attackSliceFor: selectAttackSlice,
      analyzeWindow,
      validatePhysicalAbiV2,
      renderPhysicalModalV2,
      solvePhysicalReedV2,
      stepPhysicalClarinetReedV2,
    }),
    waveguide,
  });
}

/**
 * Instantiate the module once per page. A rejected instantiation is not
 * cached: a later caller may retry, and the engine surfaces the stable
 * refusal `audio.renderer_unavailable` in the meantime.
 */
export function loadConcertGrandRenderer(): Promise<ConcertGrandRenderer> {
  return loadDspCore().then((core) => core.concertGrand);
}

/**
 * The waveguide renderer map, keyed by algorithm id — same instantiation,
 * same retry semantics.
 */
export function loadWaveguideRenderers(): Promise<
  ReadonlyMap<string, WaveguideRenderer>
> {
  return loadDspCore().then((core) => core.waveguide);
}

function loadDspCore(): Promise<DspCore> {
  rendererPromise ??= instantiate().catch((error: unknown) => {
    rendererPromise = null;
    throw error instanceof Error ? error : new Error(String(error));
  });
  return rendererPromise;
}
