export {
  MAX_PLAYBACK_PLAN_BINDING_LOOKUPS,
  MAX_PLAYBACK_PLAN_EVENTS,
  MAX_PLAYBACK_PLAN_EXACT_BEAT_OPERATIONS,
  MAX_PLAYBACK_PLAN_GATE_CALCULATIONS,
  MAX_PLAYBACK_PLAN_LOOP_INTERSECTION_CHECKS,
  MAX_PLAYBACK_PLAN_MEASURES_VISITED,
  MAX_PLAYBACK_PLAN_OUTPUT_PITCHES,
  MAX_PLAYBACK_PLAN_PITCHES_PER_EVENT,
  MAX_PLAYBACK_PLAN_REALIZATION_BINDINGS,
  MAX_PLAYBACK_PLAN_SOURCE_EVENT_IDENTITY_RECORDS,
  MAX_PLAYBACK_PLAN_TICK_PROJECTIONS,
  MAX_PLAYBACK_PLAN_TOTAL_QUARTER_NOTE_BEATS,
  MAX_PLAYBACK_PLAN_TRACKED_RECORDS,
  PLAYBACK_ARTICULATION_KINDS,
  PLAYBACK_ARTICULATION_POLICY,
  PLAYBACK_ARTICULATION_POLICY_ID,
  PLAYBACK_ARTICULATION_POLICY_VERSION,
  PLAYBACK_EVENT_OWN_KEY_ORDER,
  PLAYBACK_EVENT_SCHEMA,
  PLAYBACK_GENERATED_CANDIDATE_INVALID_REASONS,
  PLAYBACK_LOOP_POLICY,
  PLAYBACK_LOOP_POLICY_ID,
  PLAYBACK_LOOP_POLICY_VERSION,
  PLAYBACK_PLAN_COMPILER_ID,
  PLAYBACK_PLAN_COMPILER_VERSION,
  PLAYBACK_PLAN_COMPILER_VERSION_TAG,
  PLAYBACK_PLAN_CONTRACT_SCHEMA,
  PLAYBACK_PLAN_FIXED_VELOCITY,
  PLAYBACK_PLAN_MEMORY_LIMITS,
  PLAYBACK_PLAN_MIDI_PPQ,
  PLAYBACK_PLAN_MINIMUM_GATE_TICKS,
  PLAYBACK_PLAN_OPERATION_NAMES,
  PLAYBACK_PLAN_OUTPUT_POLICY,
  PLAYBACK_PLAN_OWN_KEY_ORDER,
  PLAYBACK_PLAN_REALIZATION_SCHEMA,
  PLAYBACK_PLAN_REFUSAL_CODES,
  PLAYBACK_PLAN_REFUSAL_PRECEDENCE,
  PLAYBACK_PLAN_RELEASE_GAP_TICKS,
  PLAYBACK_PLAN_REQUEST_SCHEMA,
  PLAYBACK_PLAN_RESULT_SCHEMA,
  PLAYBACK_PLAN_SCHEMA,
  PLAYBACK_PLAN_TERMINATIONS,
  PLAYBACK_PLAN_VALIDATION_PRECEDENCE,
  PLAYBACK_PLAN_WORK_COUNTER_NAMES,
  PLAYBACK_PLAN_WORK_INCREMENT_POLICY,
  PLAYBACK_PLAN_WORK_LIMITS,
  PLAYBACK_REALIZATION_BINDING_POLICY,
  PLAYBACK_REALIZATION_BINDING_POLICY_ID,
  PLAYBACK_REALIZATION_BINDING_POLICY_VERSION,
  PLAYBACK_TIMELINE_POLICY,
  PLAYBACK_VELOCITY_POLICY,
  PLAYBACK_VELOCITY_POLICY_ID,
  PLAYBACK_VELOCITY_POLICY_VERSION,
} from "./playback-plan-contract";
export type {
  AvailableGeneratedPlaybackRealization,
  CompilePlaybackPlan,
  CompilePlaybackPlanFailure,
  CompilePlaybackPlanRequest,
  CompilePlaybackPlanResult,
  CompilePlaybackPlanSuccess,
  GeneratedPlaybackRealizationBinding,
  NonEmptyMidiPitches,
  PlaybackArticulationKind,
  PlaybackEvent,
  PlaybackGeneratedCandidateInvalidReason,
  PlaybackPlan,
  PlaybackPlanGateRefusal,
  PlaybackPlanLoopRefusal,
  PlaybackPlanOperationName,
  PlaybackPlanOperations,
  PlaybackPlanRealizationRefusal,
  PlaybackPlanRefusal,
  PlaybackPlanRefusalCode,
  PlaybackPlanRequestRefusal,
  PlaybackPlanTermination,
  PlaybackPlanTimelineRefusal,
  PlaybackPlanWorkCounterName,
  PlaybackPlanWorkEvidence,
  PlaybackPlanWorkLimitRefusal,
  PlaybackRealizationBinding,
  PlaybackRealizationMap,
  StoredPlaybackRealizationBinding,
} from "./playback-plan-contract";
export {
  compilePlaybackPlan,
  playbackPlanOperations,
} from "./compile-playback-plan";
/*
 * The band-sketch performance layer (jcpe-1gao). It consumes a compiled P0
 * plan and returns another P0-shaped plan, so it is published here rather
 * than as a package of its own; its sources live under `./performance/` so
 * P0's pinned three-file production inventory stays exactly what its accepted
 * evidence says it is.
 */
export {
  MAX_PERFORMANCE_PLAN_BARS_VISITED,
  MAX_PERFORMANCE_PLAN_EVENTS,
  MAX_PERFORMANCE_PLAN_SLOTS_CONSIDERED,
  MAX_PERFORMANCE_PLAN_SOURCE_EVENTS,
  PERFORMANCE_BASS_REGISTER,
  PERFORMANCE_BASS_TONES,
  PERFORMANCE_COMP_BASS_SEPARATION_SEMITONES,
  PERFORMANCE_COMP_MAX_SPAN_SEMITONES,
  PERFORMANCE_COMP_MIN_WIDTH_VOICES,
  PERFORMANCE_COMP_REGISTER_POLICY_VERSION,
  PERFORMANCE_COMP_VOICINGS,
  PERFORMANCE_PLAN_COMPILER_ID,
  PERFORMANCE_PLAN_COMPILER_VERSION,
  PERFORMANCE_PLAN_CONTRACT_SCHEMA,
  PERFORMANCE_PLAN_MIDI_PPQ,
  PERFORMANCE_PLAN_REFUSAL_CODES,
  PERFORMANCE_PLAN_TERMINATIONS,
  PERFORMANCE_PLAN_WORK_LIMITS,
  PERFORMANCE_ROLES,
  PERFORMANCE_ROLE_ID_SUFFIXES,
  PERFORMANCE_STRAIGHT_EIGHTHS,
  PERFORMANCE_STYLES,
  PERFORMANCE_STYLE_IDS,
} from "./performance/performance-plan-contract";
export type {
  CompilePerformancePlan,
  CompilePerformancePlanFailure,
  CompilePerformancePlanRequest,
  CompilePerformancePlanResult,
  CompilePerformancePlanSuccess,
  ExactBeats,
  PerformanceBassSlot,
  PerformanceBassTone,
  PerformanceCompRegister,
  PerformanceCompSlot,
  PerformanceCompVoicing,
  PerformanceCyclePhases,
  PerformancePlanRefusal,
  PerformancePlanRefusalCode,
  PerformancePlanTermination,
  PerformancePlanWorkCounterName,
  PerformancePlanWorkEvidence,
  PerformanceRole,
  PerformanceStyle,
  PerformanceStyleId,
  PerformanceStyleKind,
  PerformanceSwingRatio,
} from "./performance/performance-plan-contract";
export { compilePerformancePlan } from "./performance/performance-plan";
