import { resolve } from "node:path";
import { atomicWrite, sha256Hex } from "./foundation-io";

/**
 * Regenerates `src/styles/fonts.css` from the checked-in font binaries under
 * `assets/fonts/`. The artifact contract forbids external fonts, so the two
 * typefaces of the v2 ink-on-paper identity travel as `data:font/woff2`
 * payloads inside a generated stylesheet. Like the wasm and piano payloads,
 * the generated file is committed; `--check` proves it matches its inputs.
 *
 * Both faces are variable fonts subset to the latin range by upstream Google
 * Fonts static serving; the checked-in bytes are the single source of truth.
 */
export type EmbeddedFontFace = {
  /** Stable asset id recorded in dist/licenses.json. */
  id: string;
  family: "Archivo" | "Literata";
  style: "normal" | "italic";
  /** CSS font-weight range served by the variable file. */
  weightRange: string;
  file: string;
  license: string;
  licenseFile: string;
  source: string;
};

export const EMBEDDED_FONT_FACES: readonly EmbeddedFontFace[] = Object.freeze([
  {
    id: "archivo-variable-latin",
    family: "Archivo",
    style: "normal",
    weightRange: "100 900",
    file: "archivo-latin.woff2",
    license: "OFL-1.1",
    licenseFile: "assets/fonts/OFL-archivo.txt",
    source:
      "Archivo variable (latin subset), The Archivo Project Authors, " +
      "https://github.com/Omnibus-Type/Archivo via Google Fonts",
  },
  {
    id: "literata-variable-latin",
    family: "Literata",
    style: "normal",
    weightRange: "200 900",
    file: "literata-latin.woff2",
    license: "OFL-1.1",
    licenseFile: "assets/fonts/OFL-literata.txt",
    source:
      "Literata variable (latin subset), The Literata Project Authors, " +
      "https://github.com/googlefonts/literata via Google Fonts",
  },
  {
    id: "literata-variable-latin-italic",
    family: "Literata",
    style: "italic",
    weightRange: "200 900",
    file: "literata-latin-italic.woff2",
    license: "OFL-1.1",
    licenseFile: "assets/fonts/OFL-literata.txt",
    source:
      "Literata variable italic (latin subset), The Literata Project " +
      "Authors, https://github.com/googlefonts/literata via Google Fonts",
  },
]);

export const FONTS_CSS_PATH = "src/styles/fonts.css";
export const FONTS_CSS_BANNER =
  "/* @generated by scripts/build-fonts.ts from assets/fonts; do not edit. */";

export async function generateFontsCss(root: string): Promise<string> {
  const blocks: string[] = [FONTS_CSS_BANNER];
  for (const face of EMBEDDED_FONT_FACES) {
    const path = resolve(root, "assets/fonts", face.file);
    const file = Bun.file(path);
    if (!(await file.exists())) {
      throw new Error(`FONT_ASSET_MISSING: ${face.file} is not checked in.`);
    }
    const bytes = new Uint8Array(await file.arrayBuffer());
    if (
      bytes[0] !== 0x77 || bytes[1] !== 0x4f || bytes[2] !== 0x46 ||
      bytes[3] !== 0x32
    ) {
      throw new Error(`FONT_ASSET_FORMAT: ${face.file} is not a woff2 file.`);
    }
    const base64 = Buffer.from(bytes).toString("base64");
    blocks.push(
      [
        `/* ${face.id}: sha256 ${await sha256Hex(bytes)}, ${String(bytes.byteLength)} bytes, ${face.license} */`,
        "@font-face {",
        `  font-family: '${face.family}';`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weightRange};`,
        "  font-display: swap;",
        `  src: url(data:font/woff2;base64,${base64}) format('woff2');`,
        "}",
      ].join("\n"),
    );
  }
  return `${blocks.join("\n\n")}\n`;
}

if (import.meta.main) {
  const root = process.cwd();
  const check = Bun.argv.includes("--check");
  const generated = await generateFontsCss(root);
  const outPath = resolve(root, FONTS_CSS_PATH);
  if (check) {
    const current = (await Bun.file(outPath).exists())
      ? await Bun.file(outPath).text()
      : null;
    if (current !== generated) {
      console.error(
        JSON.stringify({
          schema: "jcpe.build-fonts.v1",
          outcome: "fail",
          message:
            "FONT_CSS_DRIFT: src/styles/fonts.css does not match " +
            "assets/fonts; regenerate with bun scripts/build-fonts.ts.",
        }),
      );
      process.exit(1);
    }
    console.log(
      JSON.stringify({ schema: "jcpe.build-fonts.v1", outcome: "pass", mode: "check" }),
    );
  } else {
    await atomicWrite(outPath, new TextEncoder().encode(generated));
    console.log(
      JSON.stringify({
        schema: "jcpe.build-fonts.v1",
        outcome: "pass",
        mode: "write",
        path: FONTS_CSS_PATH,
        bytes: generated.length,
      }),
    );
  }
}
