/**
 * Materialize the reviewed web sample payloads as compact raw PCM resources
 * for FrankenJazz. The generated bytes are exactly the bytes already pinned
 * in the source modules; this script never reads a corpus or the network.
 *
 * Usage:
 *   bun scripts/build-ios-instrument-samples.ts
 *   bun scripts/build-ios-instrument-samples.ts --check
 */
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  UPRIGHT_BASS_SAMPLES_BASE64,
  UPRIGHT_BASS_SAMPLES_BYTE_LENGTH,
  UPRIGHT_BASS_SAMPLES_SHA256,
} from "../src/audio/wasm/upright-bass-samples";
import {
  VIBRAPHONE_SAMPLES_BASE64,
  VIBRAPHONE_SAMPLES_BYTE_LENGTH,
  VIBRAPHONE_SAMPLES_SHA256,
} from "../src/audio/wasm/vibraphone-samples";

const repositoryRoot = resolve(import.meta.dirname, "..");
const outputDirectory = resolve(
  repositoryRoot,
  "ios/Resources/InstrumentSamples",
);
const checkOnly = process.argv.includes("--check");

const payloads = [
  {
    name: "upright-bass-samples.pcm",
    base64: UPRIGHT_BASS_SAMPLES_BASE64,
    bytes: UPRIGHT_BASS_SAMPLES_BYTE_LENGTH,
    sha256: UPRIGHT_BASS_SAMPLES_SHA256,
  },
  {
    name: "vibraphone-samples.pcm",
    base64: VIBRAPHONE_SAMPLES_BASE64,
    bytes: VIBRAPHONE_SAMPLES_BYTE_LENGTH,
    sha256: VIBRAPHONE_SAMPLES_SHA256,
  },
] as const;

for (const payload of payloads) {
  const decoded = Buffer.from(payload.base64, "base64");
  if (decoded.byteLength !== payload.bytes) {
    throw new Error(
      `${payload.name}: byte length ${String(decoded.byteLength)} != ${String(payload.bytes)}`,
    );
  }
  const digest = createHash("sha256").update(decoded).digest("hex");
  if (digest !== payload.sha256) {
    throw new Error(`${payload.name}: source digest ${digest} != ${payload.sha256}`);
  }

  const outputPath = resolve(outputDirectory, payload.name);
  if (checkOnly) {
    let current: Buffer;
    try {
      current = await readFile(outputPath);
    } catch {
      throw new Error(`${payload.name}: generated iOS resource is missing`);
    }
    if (!current.equals(decoded)) {
      throw new Error(`${payload.name}: generated iOS resource has drifted`);
    }
    continue;
  }

  await mkdir(outputDirectory, { recursive: true });
  await writeFile(outputPath, decoded);
}

console.log(
  `${checkOnly ? "checked" : "wrote"} ${String(payloads.length)} FrankenJazz sample resources`,
);
