/**
 * Development-time generator for the embedded Concert Grand DSP module.
 *
 * `bun run build` never runs cargo: the wasm payload is checked-in source at
 * `src/audio/wasm/concert-grand-wasm.ts`, generated here from
 * `dsp/concert-grand`. Reproducing the payload requires the pinned Rust
 * toolchain recorded in the generated banner; `--check` rebuilds and fails on
 * any drift between the Rust source and the checked-in payload so the two
 * cannot silently diverge.
 *
 * Usage:
 *   bun scripts/build-dsp.ts            # regenerate the embedded module
 *   bun scripts/build-dsp.ts --check    # rebuild and verify zero drift
 */
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const crateDir = resolve(root, "dsp/concert-grand");
const modulePath = resolve(root, "src/audio/wasm/concert-grand-wasm.ts");
const wasmPath = resolve(
  process.env["CARGO_TARGET_DIR"] ?? resolve(crateDir, "target"),
  "wasm32-unknown-unknown/release/concert_grand.wasm",
);

async function run(): Promise<void> {
  const checkOnly = process.argv.includes("--check");

  const build = Bun.spawn(
    [
      "cargo",
      "build",
      "--release",
      "--locked",
      "--target",
      "wasm32-unknown-unknown",
    ],
    {
      cwd: crateDir,
      env: {
        ...process.env,
        RCH_CARGO_WRAPPER_BYPASS: "1",
        RUSTFLAGS: "-C link-arg=--export=__heap_base",
      },
      stdout: "pipe",
      stderr: "pipe",
    },
  );
  const exitCode = await build.exited;
  if (exitCode !== 0) {
    const stderr = await new Response(build.stderr).text();
    throw new Error(`DSP_CARGO_BUILD_FAILED\n${stderr}`);
  }

  const rustcVersion = (
    await new Response(
      Bun.spawn(["rustc", "--version"], { stdout: "pipe" }).stdout,
    ).text()
  ).trim();

  const wasm = await readFile(wasmPath);
  const sha256 = createHash("sha256").update(wasm).digest("hex");
  const base64 = wasm.toString("base64");

  const generated = `/**
 * @generated by scripts/build-dsp.ts — do not hand-edit.
 *
 * Source: dsp/concert-grand (Rust), compiled for wasm32-unknown-unknown with
 * opt-level=z, fat LTO, panic=abort, and --export=__heap_base.
 * Toolchain: ${rustcVersion}
 *
 * The payload is project-owned code under the repository license plus the
 * MIT/Apache-2.0 \`libm\` software-float library; both are recorded in the
 * build's license inventory. Regenerate with \`bun scripts/build-dsp.ts\`;
 * verify drift with \`--check\`.
 */

export const CONCERT_GRAND_WASM_SHA256 =
  "${sha256}";

export const CONCERT_GRAND_WASM_BYTE_LENGTH = ${String(wasm.byteLength)};

export const CONCERT_GRAND_WASM_BASE64 =
  "${base64}";
`;

  if (checkOnly) {
    const existing = await readFile(modulePath, "utf8").catch(() => null);
    if (existing === null) {
      throw new Error(`DSP_MODULE_MISSING: ${modulePath}`);
    }
    const existingHash = /CONCERT_GRAND_WASM_SHA256 =\n {2}"([0-9a-f]{64})"/u.exec(
      existing,
    )?.[1];
    if (existingHash !== sha256) {
      throw new Error(
        `DSP_MODULE_DRIFT: checked-in ${existingHash ?? "<none>"} != rebuilt ${sha256}`,
      );
    }
    process.stdout.write(`dsp-check ok sha256=${sha256}\n`);
    return;
  }

  await writeFile(modulePath, generated);
  process.stdout.write(
    `wrote ${modulePath} (${String(wasm.byteLength)} wasm bytes, sha256=${sha256})\n`,
  );
}

await run();
