"""Derive the offline print face; development-only FontTools 4.61.1 + Brotli.

Run through RCH from the repository root, then run build-fonts.ts. Normal
builds consume the checked-in outputs and require no Python dependencies.
"""
import argparse
import base64
import hashlib
import io
import json
from pathlib import Path

import fontTools
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
if fontTools.__version__ != "4.61.1":
    raise SystemExit("Print font derivation requires FontTools 4.61.1.")
source = Path("assets/fonts/archivo-latin.woff2").read_bytes()
if hashlib.sha256(source).hexdigest() != "8f704806dbedeaaeca334b11ec348bc3ac3a439d6431544b3afb54f534ee4967":
    raise SystemExit("Reviewed Archivo input changed; review before deriving.")
variable = TTFont(io.BytesIO(source), recalcTimestamp=False)
if {axis.axisTag for axis in variable["fvar"].axes} != {"wght"}:
    raise SystemExit("Unexpected font axes.")
font = instantiateVariableFont(variable, {"wght": 400}, inplace=False)
font.flavor = "woff2"
output = io.BytesIO()
font.save(output)
binary = output.getvalue()
digest = hashlib.sha256(binary).hexdigest()
if digest != "45c7395121feb0c53720989ee5483863dd18fc71c8979aca432b6bd137427a40":
    raise SystemExit("Static print font bytes drifted; review the derivation toolchain.")
# Preserve the reviewed repertoire, including the existing soft-hyphen refusal
# in printable-chart.ts. Do not automatically admit new cmap characters.
coverage = [*range(32, 127), *range(160, 256), 8211, 8212, 8216, 8217, 8220, 8221, 8226, 8230, 8364]
cmap = font.getBestCmap()
advances = {str(cp): font["hmtx"].metrics[cmap[cp]][0] / font["head"].unitsPerEm for cp in coverage}
compact = lambda value: json.dumps(value, ensure_ascii=True, separators=(",", ":"))
module = (
    "/** @generated by scripts/derive-print-font.py; Archivo at static weight 400. */\n"
    f"export const PRINT_FONT_SHA256={compact(digest)};\n"
    f"export const PRINT_FONT_DATA={compact('data:font/woff2;base64,' + base64.b64encode(binary).decode())};\n"
    f"export const PRINT_FONT_LICENSE={compact(Path('assets/fonts/OFL-archivo.txt').read_text())};\n"
    f"export const PRINT_FONT_ADVANCES:Readonly<Record<string,number>>=Object.freeze({compact(advances)});\n"
).encode()
for name, data in [("assets/fonts/archivo-print-400.woff2", binary), ("src/export/print-font.ts", module)]:
    path = Path(name)
    if args.check:
        if not path.exists() or path.read_bytes() != data:
            raise SystemExit(f"Print font output drift: {name}")
    else:
        path.write_bytes(data)
print(json.dumps({"mode": "check" if args.check else "write", "sha256": digest, "fontBytes": len(binary), "advances": len(advances)}))
