import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

type Obj = Record<string, unknown>;
export type Finding = Readonly<{ code: string; path: string; message: string }>;
export type Report = Readonly<{
  schema: "changes.validation.phs4-plucked-string-v2.v1";
  package: "PHS4";
  outcome: "pass" | "fail";
  counts: Readonly<{ targets: number; stringSets: number; bodies: number; physicsCases: number; metricCases: number; metricFamilies: number; authorities: number; traceRequirements: number; mutationControls: number }>;
  findings: readonly Finding[];
}>;
const ROOT = new URL("../tests/fixtures/plucked-string-v2", import.meta.url).pathname;
const LIMITS = { maximumStemEvents:128, maximumStrings:12, maximumFrets:36, maximumStringDelaySamples:65536, maximumBodyModes:64, maximumCqcPairs:32, maximumSympatheticStrings:12, maximumContactIterations:8, maximumSlideTransientFrames:24000, maximumAmpOversampleFactor:4, maximumStateBytes:262144, maximumStemSeconds:30, maximumSampleRateHz:96000 };
function obj(value: unknown): Obj { return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Obj : {}; }
function arr(value: unknown): unknown[] { return Array.isArray(value) ? value : []; }
function canon(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canon).join(",")}]`; if (typeof value === "object" && value !== null) return `{${Object.keys(value as Obj).sort().map((key) => `${JSON.stringify(key)}:${canon((value as Obj)[key])}`).join(",")}}`; return JSON.stringify(value); }
async function json(path: string): Promise<Obj> { return obj(JSON.parse(await readFile(path, "utf8")) as unknown); }
function add(findings: Finding[], code: string, path: string, message: string): void { findings.push({ code, path, message }); }
function row(rows: unknown[], id: string): Obj { return obj(rows.find((value) => obj(value)["id"] === id)); }

export async function validatePhs4Contract(fixtureRoot = ROOT): Promise<Report> {
  const root = resolve(fixtureRoot);
  const [contract, packs, physicsDoc, metricsDoc, provenanceDoc, traceDoc, mutationsDoc] = await Promise.all([
    json(resolve(root,"contract.json")), json(resolve(root,"instrument-packs.json")), json(resolve(root,"physics-cases.json")), json(resolve(root,"metric-cases.json")), json(resolve(root,"provenance-ledger.json")), json(resolve(root,"trace-ledger.json")), json(resolve(root,"mutation-controls.json")),
  ]);
  const findings: Finding[] = [], targets = arr(contract["recipeTargets"]), stringSets = arr(packs["stringSets"]), bodies = arr(packs["bodies"]), physics = arr(physicsDoc["cases"]), metrics = arr(metricsDoc["cases"]), authorities = arr(provenanceDoc["authorities"]), traces = arr(traceDoc["requirements"]), mutations = arr(mutationsDoc["controls"]);
  if (contract["schema"] !== "changes.fixtures.phs4-plucked-string-v2.v1" || contract["modelSchema"] !== "changes.dsp.plucked-string-family-v2.v1") add(findings,"PHS4_SCHEMA","/schema","Plucked-string schema changed");
  const target = (instrumentId: string): Obj => obj(targets.find((value) => obj(value)["instrumentId"] === instrumentId));
  if (targets.length !== 5 || target("guitar")["publicLabel"] !== "Clean Archtop" || target("blues-guitar")["publicLabel"] !== "Marshall-Class Electric" || target("blues-guitar")["target"] !== "strat-style solid-body electric through a Marshall-class asymmetric valve amp and closed-back cabinet" || target("physical-upright-bass")["arco"] !== "explicitly-deferred") add(findings,"PHS4_TARGETS","/recipeTargets","Honest target names or comparator scope changed");
  if (contract["waveLaw"] !== "two-polarization-bidirectional-stiff-string-with-frequency-dependent-loss") add(findings,"PHS4_WAVES","/waveLaw","Bidirectional stiff-string law changed");
  if (contract["bridgeLaw"] !== "per-sample passive shared multiport junction for every string and mass-normalized body mode; incoming work equals reflected string work plus body-energy delta plus radiated and dissipated loss" || contract["bodyLaw"] !== "offline DKT plate mesh with offset braces feeds mass-normalized coherent runtime modes carrying signed bridge residues b_k=phi^T f_bridge and radiation residues r_k; CQC is diagnostic-only and forbidden in coherent audio") add(findings,"PHS4_BRIDGE","/bridgeLaw","Bridge/body feedback law changed");
  if (contract["recipeBindingLaw"] !== "every-public-target-binds-exactly-one-reviewed-string-set-body-pickup-and-amp-combination; null-electric-stages-mean-unamplified-acoustic-radiation" || contract["pickupLaw"] !== "in-phase-sum-of-finite-aperture-string-velocity-taps-through-passive-rlc-loading; rw-rp reverses both coil and magnet while preserving string-signal phase and rejecting common-mode hum" || contract["ampLaw"] !== "authored-bounded-design-target with rate-policy-bound asymmetric triode and power stage, sag operating points, tone stack, and closed-back cabinet; measured Marshall similarity is not claimed until legal reference validation") add(findings,"PHS4_PACKS","/pickupLaw","Recipe binding, pickup, or amplifier design law changed");
  const controls = obj(contract["controls"]); if (canon(controls["pluckForceN"]) !== canon([0,12]) || canon(controls["slideVelocityMPerS"]) !== canon([-4,4]) || canon(controls["sympatheticAmount"]) !== canon([0,1])) add(findings,"PHS4_CONTROLS","/controls","Gesture units or ranges changed");
  if (arr(contract["retainedState"]).length !== 10) add(findings,"PHS4_STATE","/retainedState","Shared stem state changed");
  if (canon(contract["limits"]) !== canon(LIMITS)) add(findings,"PHS4_LIMITS","/limits","Deterministic bounds changed");
  const independence = obj(contract["independence"]); if (independence["productionImportsForbidden"] !== true || independence["productionOutputUsed"] !== false || independence["expectedValuesGenerated"] !== false || independence["frankensimRuntimeImported"] !== false) add(findings,"PHS4_INDEPENDENCE","/independence","Independent authority or license boundary changed");
  const ukuleleStrings = arr(row(stringSets,"nylon-reentrant-uke")["strings"]);
  const bindings = arr(packs["recipeBindings"]), pickups = arr(packs["pickups"]), amps = arr(packs["amps"]), marshall = row(amps,"marshall-class-drive"), bridgeMiddle = row(pickups,"bridge-middle-parallel"), neck = row(pickups,"neck"), middle = row(pickups,"middle"), bridge = row(pickups,"bridge");
  const expectedBindings = [{instrumentId:"guitar",stringSetId:"steel-archtop-12s",bodyId:"archtop",pickupId:"neck",ampId:"clean-compact"},{instrumentId:"blues-guitar",stringSetId:"electric-10s",bodyId:"solid-electric",pickupId:"bridge-middle-parallel",ampId:"marshall-class-drive"},{instrumentId:"dreadnought-guitar",stringSetId:"steel-dreadnought-13s",bodyId:"dreadnought",pickupId:null,ampId:null},{instrumentId:"ukulele",stringSetId:"nylon-reentrant-uke",bodyId:"ukulele",pickupId:null,ampId:null},{instrumentId:"physical-upright-bass",stringSetId:"upright-pizz-hybrid",bodyId:"upright-bass",pickupId:null,ampId:null}];
  const marshallPoints = obj(marshall["operatingPoints"]), marshallControls = obj(marshall["controls"]);
  const expectedPickups = [{id:"neck",positionOverScale:0.24,apertureM:0.018,coilWindingPolarity:1,magneticPolarity:1,stringSignalPolarity:1,parameterAuthorityId:"pickup-amp-authored-design-targets",electricalLoading:{inductanceH:4.2,seriesResistanceOhm:7600,windingCapacitanceF:0.00000000012,loadResistanceOhm:500000,loadCapacitanceF:0.00000000047}},{id:"middle",positionOverScale:0.16,apertureM:0.016,coilWindingPolarity:-1,magneticPolarity:-1,stringSignalPolarity:1,parameterAuthorityId:"pickup-amp-authored-design-targets",electricalLoading:{inductanceH:2.4,seriesResistanceOhm:5900,windingCapacitanceF:0.0000000001,loadResistanceOhm:250000,loadCapacitanceF:0.00000000047}},{id:"bridge",positionOverScale:0.09,apertureM:0.012,coilWindingPolarity:1,magneticPolarity:1,stringSignalPolarity:1,parameterAuthorityId:"pickup-amp-authored-design-targets",electricalLoading:{inductanceH:2.2,seriesResistanceOhm:6200,windingCapacitanceF:0.00000000011,loadResistanceOhm:250000,loadCapacitanceF:0.00000000047}}];
  const expectedBridgeMiddle = {id:"bridge-middle-parallel",components:["middle","bridge"],weights:[0.5,0.5],stringSignalPolarities:[1,1],commonModeHumPolarities:[-1,1],mixLaw:"in-phase-finite-aperture-string-velocity-sum-then-parallel-rlc-load; rw-rp-common-mode-hum-cancels",parameterAuthorityId:"pickup-amp-authored-design-targets",electricalLoading:{inductanceH:1.15,seriesResistanceOhm:3024,windingCapacitanceF:0.00000000021,loadResistanceOhm:250000,loadCapacitanceF:0.00000000047}};
  const expectedPoints = {clean:{drive:0.75,sagDepth:0.12},edge:{drive:1.35,sagDepth:0.24},crunch:{drive:2.2,sagDepth:0.34}};
  if (packs["schema"] !== "changes.fixtures.phs4-plucked-string-packs.v1" || stringSets.length !== 5 || bodies.length !== 5 || canon(bindings) !== canon(expectedBindings) || packs["differentiationLaw"] !== "only reviewed scale, string set, geometry-derived mass-normalized body modes with signed bridge and radiation residues, pickup, and amp packs differentiate targets; bridgeAdmittanceScale is a bounded calibration multiplier and never substitutes for modal residues" || arr(row(stringSets,"steel-archtop-12s")["strings"]).length !== 6 || arr(ukuleleStrings[0])[0] !== "g4" || row(bodies,"upright-bass")["helmholtzHz"] !== 75 || pickups.length !== 4 || canon([neck,middle,bridge]) !== canon(expectedPickups) || canon(bridgeMiddle) !== canon(expectedBridgeMiddle) || marshall["parameterAuthorityId"] !== "pickup-amp-authored-design-targets" || marshall["referenceStatus"] !== "authored-bounded-design-target-not-measured-marshall-fit" || marshall["nonlinearity"] !== "bounded-asymmetric-triode-plus-power-stage" || canon(marshall["oversamplePolicy"]) !== canon({44100:4,48000:4,96000:1}) || marshall["oversampleFilterLaw"] !== "four-stage-halfband-lowpass-before-decimation; native-96k-single-rate-is-admitted-only-under-the-closed-input-band-and-post-nonlinear-cabinet-alias-envelope" || marshall["native96kException"] !== "single-rate-at-96khz-only; no rate-conversion filter; same nonlinear stages and designed cabinet remain active" || marshall["defaultOperatingPoint"] !== "crunch" || canon(marshallPoints) !== canon(expectedPoints) || canon(marshallControls) !== canon({drive:[0.75,2.2],sagDepth:[0.12,0.34],operatingPoint:["clean","edge","crunch"]}) || canon(marshall["toneStackHz"]) !== canon([120,720,3200]) || canon(marshall["toneStackDb"]) !== canon([1.5,4,2]) || marshall["cabinetLowpassHz"] !== 5200 || marshall["cabinetKind"] !== "closed-back-4x12-authored-design-target" || canon(marshall["cabinetResonancesHz"]) !== canon([105,165,2400]) || marshall["pickupInput"] !== "bridge-middle-parallel") add(findings,"PHS4_PACKS","/instrument-packs","Reviewed recipe/string/body/pickup/amp packs changed");
  if (physics.length !== 16) add(findings,"PHS4_CASES","/physics-cases","Physics corpus changed");
  if (obj(row(physics,"ideal-string-e2")["expected"])["frequencyHz"] !== 82.327523683 || row(metrics,"octave-transposition")["expectedRatio"] !== 2) add(findings,"PHS4_KNOWN_ANSWER","/known-answers","Independent known answer changed");
  if (obj(row(physics,"active-bridge-mutation")["expected"])["outcome"] !== "refuse") add(findings,"PHS4_PASSIVITY","/physics-cases/active-bridge-mutation","Active bridge must refuse");
  if (row(physics,"cqc-correlated-pair")["kind"] !== "offline-cqc-energy-diagnostic" || obj(row(physics,"cqc-correlated-pair")["expected"])["combinedEnergy"] !== 3 || obj(row(physics,"cqc-correlated-pair")["expected"])["coherentRuntimeUseForbidden"] !== true) add(findings,"PHS4_CQC","/physics-cases/cqc-correlated-pair","Offline-only CQC diagnostic law changed");
  const metricFamilies = new Set(metrics.map((value) => String(obj(value)["metric"]))); for (const required of ["pitch","inharmonicity","decay-slope","body-admittance","pluck-null","pickup-comb","sympathetic-response","amp-alias","amp-transfer","transposition-relations"]) if (!metricFamilies.has(required)) add(findings,"PHS4_METRICS","/metric-cases",`Missing ${required}`);
  const ampAlias = row(metrics,"amp-alias"), ampTransfer = row(metrics,"amp-transfer-envelope"); if (ampAlias["ampId"] !== "marshall-class-drive" || ampAlias["defaultOperatingPoint"] !== "crunch" || ampAlias["targetDrive"] !== 2.2 || ampAlias["maximumAliasDbc"] !== -50 || canon(ampAlias["ratesHz"]) !== canon([44100,48000,96000]) || canon(ampAlias["oversampleFactors"]) !== canon([4,4,1]) || ampAlias["native96kException"] !== "single-rate-at-96khz-only" || canon(ampAlias["requiredStages"]) !== canon(["asymmetric-triode","sag","tone-stack","power-stage","closed-back-cabinet"]) || ampTransfer["authorityId"] !== "pickup-amp-authored-design-targets" || ampTransfer["referenceStatus"] !== "authored-bounded-design-target-not-measured-marshall-fit" || canon(ampTransfer["frequencyEnvelopeDb"]) !== canon([[80,-14,-8],[120,-6,1],[720,-1,5],[3200,-4,2],[5200,-12,-5],[8000,-30,-18]]) || canon(ampTransfer["thdPercentByOperatingPoint"]) !== canon({clean:[0.5,5],edge:[3,15],crunch:[8,30]}) || canon(ampTransfer["crunchSagGainReductionDb"]) !== canon([1.5,5.5]) || canon(ampTransfer["pickupElectricalResonanceHz"]) !== canon([2200,5200])) add(findings,"PHS4_METRICS","/metric-cases/amp-alias","Authored amplifier alias or transfer design target changed");
  if (metrics.length !== 15) add(findings,"PHS4_METRICS","/metric-cases","Metric corpus changed");
  const frankensim = row(authorities,"frankensim-solid-contact-concepts"), authoredAmp = row(authorities,"pickup-amp-authored-design-targets"); if (authorities.length !== 6 || row(authorities,"string-body-coupling")["location"] !== "https://hal.science/tel-01078150" || frankensim["revision"] !== "61f48c03d8984ba358605a89a73b2eb45da38aa2" || canon(frankensim["sourceCommits"]) !== canon(["19a625cd4b6a4338b2f25c25055edf78b269882c","6f76589023ebd77941db678cc8c86de63b691ae5"]) || frankensim["license"] !== "MIT License (with OpenAI/Anthropic Rider)" || frankensim["runtimeAuthority"] !== false || authoredAmp["kind"] !== "authored-bounded-design-target" || authoredAmp["measuredMarshallFit"] !== false || authoredAmp["releaseAuthority"] !== false) add(findings,"PHS4_PROVENANCE","/provenance-ledger","Authority boundary changed");
  if (traces.length !== 7) add(findings,"PHS4_TRACE","/trace-ledger","Requirement trace changed");
  if (mutations.length !== 35) add(findings,"PHS4_MUTATIONS","/mutation-controls","Mutation count changed");
  return { schema:"changes.validation.phs4-plucked-string-v2.v1", package:"PHS4", outcome:findings.length===0?"pass":"fail", counts:{targets:targets.length,stringSets:stringSets.length,bodies:bodies.length,physicsCases:physics.length,metricCases:metrics.length,metricFamilies:metricFamilies.size,authorities:authorities.length,traceRequirements:traces.length,mutationControls:mutations.length}, findings };
}
if (import.meta.main) { const report = await validatePhs4Contract(process.argv[2]); console.log(JSON.stringify(report,null,2)); if (report.outcome !== "pass") process.exitCode = 1; }
