import{describe,expect,test}from"bun:test";
import{cp,mkdtemp,readFile,rm,writeFile}from"node:fs/promises";
import{tmpdir}from"node:os";import{join}from"node:path";
import{validatePhs2Contract}from"../../scripts/validate-phs2-contract";
type Obj=Record<string,unknown>;const root=new URL("../fixtures/clarinet-v2",import.meta.url).pathname;
function obj(v:unknown):Obj{if(typeof v!=="object"||v===null||Array.isArray(v))throw new Error("PHS2_TEST_OBJECT");return v as Obj}async function readObj(p:string):Promise<Obj>{return obj(JSON.parse(await readFile(p,"utf8"))as unknown)}
function replace(doc:Obj,pointer:string,value:unknown):void{const parts=pointer.slice(1).split("/");let current:unknown=doc;for(const part of parts.slice(0,-1))current=Array.isArray(current)?current[Number(part)]:obj(current)[part];const last=parts.at(-1);if(last===undefined)throw new Error("PHS2_TEST_POINTER");if(Array.isArray(current))current[Number(last)]=value;else obj(current)[last]=value}
describe("PHS2 clarinet v2 contract",()=>{
 test("independent packet validates",async()=>{expect(await validatePhs2Contract()).toEqual({schema:"changes.validation.phs2-clarinet-v2.v1",package:"PHS2",outcome:"pass",counts:{physicsCases:12,metricCases:12,metricFamilies:8,authorities:3,mutationControls:11},findings:[]})});
 test("reviewed mutations produce named findings",async()=>{const controls=(await readObj(join(root,"mutation-controls.json")))["controls"];if(!Array.isArray(controls))throw new Error("PHS2_TEST_CONTROLS");for(const raw of controls){const control=obj(raw),temporary=await mkdtemp(join(tmpdir(),"phs2-contract-"));try{await cp(root,temporary,{recursive:true});const target=String(control["target"]),path=join(temporary,target),doc=await readObj(path);replace(doc,String(control["pointer"]),control["value"]);await writeFile(path,`${JSON.stringify(doc,null,2)}\n`);const report=await validatePhs2Contract(temporary);expect(report.findings.map(f=>f.code),String(control["id"])).toContain(String(control["expectedFindingCode"]));}finally{await rm(temporary,{recursive:true,force:true})}}});
 test("commands are registered",async()=>{const[p,a,v]=await Promise.all([readFile(new URL("../../package.json",import.meta.url),"utf8"),readFile(new URL("../../docs/ARCHITECTURE.md",import.meta.url),"utf8"),readFile(new URL("../../scripts/verify.ts",import.meta.url),"utf8")]);expect(p).toContain("validate:phs2-contract");expect(a).toContain("bun run validate:phs2-contract");expect(v).toContain("phs2-clarinet-v2-contract")});
});
