import { describe, expect, test } from "bun:test";

type ContractFixture = Readonly<{
  tokenDefinitions: Readonly<Record<string, Readonly<Record<string, string>>>>;
  allowedContrastPairs: readonly Readonly<{
    id: string;
    foregrounds: readonly string[];
    backgrounds: readonly string[];
    minimumRatio: number;
  }>[];
}>;

type CssAnalysis = Readonly<{
  baseDeclarations: Readonly<Record<string, string>>;
  darkMediaDeclarations: Readonly<Record<string, string>>;
  darkPinDeclarations: Readonly<Record<string, string>>;
  localDeclarations: Readonly<Record<string, readonly string[]>>;
  literalFindings: readonly string[];
  undefinedReferences: readonly string[];
  duplicateDeclarations: readonly string[];
}>;

const contract = await Bun.file(
  new URL("../fixtures/ui/u0-ui-contract.json", import.meta.url),
).json() as ContractFixture;

const TOKEN_DECLARATION = /^\s*(--[a-z][a-z0-9-]*)\s*:\s*([^;\r\n]+)\s*;/gmu;
const TOKEN_REFERENCE = /var\(\s*(--[a-z][a-z0-9-]*)/gu;
const COLOR_LITERAL = /#[0-9a-f]{3,8}\b|\brgba?\s*\(|\bhsla?\s*\(|\boklch\s*\(/giu;
const DARK_MEDIA_MARKER = "@media (prefers-color-scheme: dark)";
const DARK_PIN_MARKER = ':root[data-theme="dark"]';
const LOCAL_CUSTOM_PROPERTY_OWNERS = Object.freeze({
  "--studio-collapsed-rail": "src/styles/studio.css",
  /* System column count set inline per system by the engraved chart (V2R-2). */
  "--studio-system-columns": "src/ui/studio/ChartWorkspace.tsx",
  /* Meter-bar heights set inline by the tour illustration (V2R-11). */
  "--tour-bar-height": "src/ui/studio/TourDialog.tsx",
  "--ui-tree-level": "src/ui/primitives/StructuredViews.tsx",
} as const);
/**
 * fonts.css is generated by scripts/build-fonts.ts and holds only @font-face
 * data-url payloads; it declares no tokens and paints no colors, but its
 * base64 bodies are megabyte-scale strings the literal scanner must still
 * visit, so it stays in the sweep rather than being exempted.
 */

async function styleSources(): Promise<Readonly<Record<string, string>>> {
  const paths: string[] = [];
  const glob = new Bun.Glob("src/styles/*.css");
  for await (const path of glob.scan({ cwd: process.cwd(), onlyFiles: true })) {
    paths.push(path.replaceAll("\\", "/"));
  }
  paths.sort();
  return Object.fromEntries(
    await Promise.all(paths.map(async (path) => [path, await Bun.file(path).text()] as const)),
  );
}

type ThemeScope = "base" | "dark-media" | "dark-pin";

/**
 * Only tokens.css may carry theme scopes. Its base scope holds the paper
 * (light) theme; the night theme appears twice with machine-checked identical
 * maps — once behind the OS-preference media block, once behind the explicit
 * [data-theme="dark"] pin the theme toggle writes. Every other stylesheet
 * contributes to the base scope and may not redeclare shared tokens at all.
 */
function themeScopesOf(
  path: string,
  source: string,
): readonly (readonly [scope: ThemeScope, text: string])[] {
  if (path !== "src/styles/tokens.css") return [["base", source]];
  const mediaStart = source.indexOf(DARK_MEDIA_MARKER);
  if (mediaStart < 0) return [["base", source]];
  const pinStart = source.indexOf(DARK_PIN_MARKER, mediaStart + DARK_MEDIA_MARKER.length);
  if (pinStart < 0) {
    return [
      ["base", source.slice(0, mediaStart)],
      ["dark-media", source.slice(mediaStart)],
    ];
  }
  return [
    ["base", source.slice(0, mediaStart)],
    ["dark-media", source.slice(mediaStart, pinStart)],
    ["dark-pin", source.slice(pinStart)],
  ];
}

const THEMED_OWNER_SET = [
  "src/styles/tokens.css#base",
  "src/styles/tokens.css#dark-media",
  "src/styles/tokens.css#dark-pin",
].join(",");

function analyzeCss(sources: Readonly<Record<string, string>>): CssAnalysis {
  const baseDeclarations: Record<string, string> = {};
  const darkMediaDeclarations: Record<string, string> = {};
  const darkPinDeclarations: Record<string, string> = {};
  const declarationOwners = new Map<string, string[]>();
  const literalFindings: string[] = [];
  const references = new Set<string>();

  for (const [path, source] of Object.entries(sources).sort(([left], [right]) => left.localeCompare(right))) {
    for (const [scope, text] of themeScopesOf(path, source)) {
      for (const match of text.matchAll(TOKEN_DECLARATION)) {
        const name = match[1];
        const value = match[2];
        if (name === undefined || value === undefined) continue;
        if (!(name in LOCAL_CUSTOM_PROPERTY_OWNERS)) {
          if (scope === "dark-media") darkMediaDeclarations[name] = value.trim();
          else if (scope === "dark-pin") darkPinDeclarations[name] = value.trim();
          else baseDeclarations[name] = value.trim();
        }
        const owners = declarationOwners.get(name) ?? [];
        owners.push(`${path}#${scope}`);
        declarationOwners.set(name, owners);
      }
    }
    for (const match of source.matchAll(TOKEN_REFERENCE)) {
      const name = match[1];
      if (name !== undefined) references.add(name);
    }
    if (path !== "src/styles/tokens.css") {
      for (const match of source.matchAll(COLOR_LITERAL)) {
        literalFindings.push(`${path}:${String(match.index)}:${match[0]}`);
      }
    }
  }

  return {
    baseDeclarations,
    darkMediaDeclarations,
    darkPinDeclarations,
    localDeclarations: Object.fromEntries(
      [...declarationOwners]
        .filter(([name]) => name in LOCAL_CUSTOM_PROPERTY_OWNERS)
        .map(([name, owners]) => [
          name,
          owners.map((owner) => owner.replace(/#(?:base|dark-media|dark-pin)$/u, "")),
        ] as const),
    ),
    literalFindings,
    undefinedReferences: [...references]
      .filter(
        (name) =>
          !(name in baseDeclarations) && !(name in LOCAL_CUSTOM_PROPERTY_OWNERS),
      )
      .sort(),
    duplicateDeclarations: [...declarationOwners]
      .filter(([, owners]) => {
        const joined = owners.join(",");
        return (
          joined !== "src/styles/tokens.css#base" &&
          joined !== THEMED_OWNER_SET &&
          !(owners.length === 1 && owners[0]?.endsWith("#base"))
        );
      })
      .map(([name, owners]) => `${name}:${owners.join(",")}`)
      .sort(),
  };
}

/** Base expectations: every group except the dark-theme override group. */
function expectedBaseTokens(): Readonly<Record<string, string>> {
  return Object.fromEntries(
    Object.entries(contract.tokenDefinitions)
      .filter(([group]) => group !== "colorDark")
      .flatMap(([, group]) => Object.entries(group)),
  );
}

function expectedDarkTokens(): Readonly<Record<string, string>> {
  return { ...contract.tokenDefinitions["colorDark"] };
}

function rgb(hex: string): readonly [number, number, number] {
  const match = /^#([0-9a-f]{6})$/iu.exec(hex);
  if (match?.[1] === undefined) throw new Error(`Opaque contrast token is not six-digit hex: ${hex}`);
  const value = Number.parseInt(match[1], 16);
  return [(value >> 16) & 255, (value >> 8) & 255, value & 255];
}

function luminance(hex: string): number {
  const channels = rgb(hex).map((value) => {
    const normalized = value / 255;
    return normalized <= 0.04045
      ? normalized / 12.92
      : ((normalized + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * (channels[0] ?? 0) + 0.7152 * (channels[1] ?? 0) + 0.0722 * (channels[2] ?? 0);
}

function contrast(left: string, right: string): number {
  const a = luminance(left);
  const b = luminance(right);
  return (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05);
}

function contrastFindings(
  tokens: Readonly<Record<string, string>>,
  theme: string,
): readonly string[] {
  const findings: string[] = [];
  for (const pair of contract.allowedContrastPairs) {
    for (const foreground of pair.foregrounds) {
      for (const background of pair.backgrounds) {
        const foregroundValue = tokens[foreground];
        const backgroundValue = tokens[background];
        if (foregroundValue === undefined || backgroundValue === undefined) {
          findings.push(`${theme}:${pair.id}:${foreground}:${background}:missing`);
          continue;
        }
        const ratio = contrast(foregroundValue, backgroundValue);
        if (ratio + Number.EPSILON < pair.minimumRatio) {
          findings.push(`${theme}:${pair.id}:${foreground}:${background}:${ratio.toFixed(4)}`);
        }
      }
    }
  }
  return findings;
}

describe("TR-U0-TOKENS independently checked production CSS", () => {
  test("U0-CONTRAST-001 U0-CONTRAST-002 U0-CONTRAST-003 U0-CONTRAST-004 U0-CONTRAST-005 U0-CONTRAST-006 U0-CONTRAST-007 U0-CONTRAST-008 U0-CONTRAST-009 actual token values satisfy every declared contrast cross-product in both themes", async () => {
    const analysis = analyzeCss(await styleSources());
    expect(analysis.baseDeclarations).toEqual(expectedBaseTokens());
    expect(analysis.darkMediaDeclarations).toEqual(expectedDarkTokens());
    expect(analysis.darkPinDeclarations).toEqual(expectedDarkTokens());
    expect(contrastFindings(analysis.baseDeclarations, "light")).toEqual([]);
    const darkMerged = {
      ...analysis.baseDeclarations,
      ...analysis.darkMediaDeclarations,
    };
    expect(contrastFindings(darkMerged, "dark")).toEqual([]);
  });

  test("the explicit dark pin never drifts from the OS-preference dark map", async () => {
    const analysis = analyzeCss(await styleSources());
    expect(analysis.darkPinDeclarations).toEqual(analysis.darkMediaDeclarations);
  });

  test("U0-PRIM-012 U0-PRIM-013 U0-VIEW-005 component CSS uses declared semantic tokens without copied color literals", async () => {
    const analysis = analyzeCss(await styleSources());
    const structuredSource = await Bun.file(
      new URL("../../src/ui/primitives/StructuredViews.tsx", import.meta.url),
    ).text();
    expect(analysis.literalFindings).toEqual([]);
    expect(analysis.undefinedReferences).toEqual([]);
    expect(analysis.duplicateDeclarations).toEqual([]);
    expect(analysis.localDeclarations).toEqual({
      "--studio-collapsed-rail": ["src/styles/studio.css"],
    });
    expect(structuredSource).toContain(
      'style={`--ui-tree-level: ${String(item.level)}`}',
    );
  });

  test("every dark-theme override names a token the base theme declares", async () => {
    const analysis = analyzeCss(await styleSources());
    const orphans = Object.keys(analysis.darkMediaDeclarations).filter(
      (name) => !(name in analysis.baseDeclarations),
    );
    expect(orphans).toEqual([]);
  });

  test("U0-CONTRAST-001 semantic counterfactual detects a low-contrast production token", async () => {
    const analysis = analyzeCss(await styleSources());
    const damaged = { ...analysis.baseDeclarations, "--text-primary": "#f8f3e8" };
    expect(contrastFindings(damaged, "light").length).toBeGreaterThan(0);
    const damagedDark = {
      ...analysis.baseDeclarations,
      ...analysis.darkMediaDeclarations,
      "--text-primary": "#1a1611",
    };
    expect(contrastFindings(damagedDark, "dark").length).toBeGreaterThan(0);
  });

  test("U0-PRIM-013 mutation controls detect copied literals, undefined references, and duplicate declarations", () => {
    const analysis = analyzeCss({
      "src/styles/tokens.css": [
        ":root {",
        "  --surface-app: #000000;",
        "  --surface-app: #000000;",
        "}",
      ].join("\n"),
      "src/styles/component.css": ".x { color: #ffffff; background: var(--missing); }",
    });
    expect(analysis.literalFindings).toHaveLength(1);
    expect(analysis.undefinedReferences).toEqual(["--missing"]);
    expect(analysis.duplicateDeclarations).toEqual([
      "--surface-app:src/styles/tokens.css#base,src/styles/tokens.css#base",
    ]);
  });

  test("a dark map missing from either scope is reported as drift", () => {
    const analysis = analyzeCss({
      "src/styles/tokens.css": [
        ":root {",
        "  --surface-app: #ffffff;",
        "}",
        "@media (prefers-color-scheme: dark) {",
        '  :root:not([data-theme="light"]) {',
        "    --surface-app: #000000;",
        "  }",
        "}",
      ].join("\n"),
    });
    expect(analysis.darkPinDeclarations).toEqual({});
    expect(analysis.darkMediaDeclarations).not.toEqual(analysis.darkPinDeclarations);
    expect(analysis.duplicateDeclarations).toEqual([
      "--surface-app:src/styles/tokens.css#base,src/styles/tokens.css#dark-media",
    ]);
  });
});
